### ISSUE TITLE
ImportError: cannot import name xxx

### ISSUE THREAD

**Issue by rtransformation** [pyscf/pyscf#1026]
Excuse me for being stupid, I install the pyscf under the instruction from https://pyscf.org/install.html#installation-without-network (the "Installation without network" part).
When I just "import pyscf" nothing went wrong.
But when I excute the example file 00-simple_hf.py i got:

Traceback (most recent call last):
  File "00-simple_hf.py", line 15, in <module>
    mol = pyscf.M(
AttributeError: module 'pyscf' has no attribute 'M'

The example file 01-h2o.py i got:

Traceback (most recent call last):
  File "01-h2o.py", line 25, in <module>
    from pyscf import gto, scf
ImportError: cannot import name 'gto'

how can I sovle this problem?

**Comment by verena-neufeld** [comment]
How did you include pyscf in your PYTHONPATH?

**Comment by rtransformation** [comment]
> How did you include pyscf in your PYTHONPATH?

Thank you for your reply.

I install the pyscf in /home/lab/pyscf and the directory hierarchy of this route is as the following:

pyscf
├── [  30]  cint_and_xc/
│   ├── [  38]  include/
│   └── [  65]  lib/
└── [4.0K]  pyscf/
    ├── [  67]  conda/
    ├── [  38]  docker/
    ├── [  60]  doc_legacy/
    ├── [4.0K]  examples/
    ├── [4.0K]  pyscf/
    ├── [ 40K]  CHANGELOG
    ├── [7.0K]  CONTRIBUTING.md
    ├── [7.2K]  FEATURES
    ├── [ 11K]  LICENSE
    ├── [ 388]  MANIFEST.in
    ├── [2.2K]  NOTICE
    ├── [3.4K]  README.md
    ├── [  59]  setup.cfg
    ├── [5.5K]  setup.py*
    └── [ 971]  TODO

I install the libcint etc in the cint_and_xc/ directory (i.e. /home/lab/pyscf/cint_and_xc) and the pyscf in the pyscf directory (i.e. /home/lab/pyscf/pyscf). 

And I set export PYTHONPATH=/home/lab/pyscf:$PYTHONPATH in the .zshrc file.

**Comment by hebrewsnabla** [comment]
I think the correct path is
```
export PYTHONPATH=/home/lab/pyscf/pyscf:$PYTHONPATH
```
because your actual pyscf.scf directory is `/home/lab/pyscf/pyscf/pyscf/scf`.

**Comment by rtransformation** [comment]
> I think the correct path is
> 
> ```
> export PYTHONPATH=/home/lab/pyscf/pyscf:$PYTHONPATH
> ```
> 
> because your actual pyscf.scf directory is `/home/lab/pyscf/pyscf/pyscf/scf`.

thanks for replying.

I used to set this, but when I run a script I got these:

Traceback (most recent call last):
  File "/home/lab/pyscf/pyscf/pyscf/lib/misc.py", line 53, in load_library
    return numpy.ctypeslib.load_library(libname, _loaderpath)
  File "/home/lab/psi4/lib/python3.6/site-packages/numpy/ctypeslib.py", line 152, in load_library
    return ctypes.cdll[libpath]
  File "/home/lab/psi4/lib/python3.6/ctypes/__init__.py", line 423, in __getitem__
    return getattr(self, name)
  File "/home/lab/psi4/lib/python3.6/ctypes/__init__.py", line 418, in __getattr__
    dll = self._dlltype(name)
  File "/home/lab/psi4/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/lab/pyscf/pyscf/pyscf/lib/libnp_helper.so: undefined symbol: _gfortran_transfer_character_write

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "rhf.py", line 4, in <module>
    from pyscf import gto, scf, lib
  File "/home/lab/pyscf/pyscf/pyscf/__init__.py", line 113, in <module>
    from pyscf import lib
  File "/home/lab/pyscf/pyscf/pyscf/lib/__init__.py", line 24, in <module>
    from pyscf.lib import numpy_helper
  File "/home/lab/pyscf/pyscf/pyscf/lib/numpy_helper.py", line 39, in <module>
    _np_helper = misc.load_library('libnp_helper')
  File "/home/lab/pyscf/pyscf/pyscf/lib/misc.py", line 61, in load_library
    return numpy.ctypeslib.load_library(libname, libpath)
  File "/home/lab/psi4/lib/python3.6/site-packages/numpy/ctypeslib.py", line 152, in load_library
    return ctypes.cdll[libpath]
  File "/home/lab/psi4/lib/python3.6/ctypes/__init__.py", line 423, in __getitem__
    return getattr(self, name)
  File "/home/lab/psi4/lib/python3.6/ctypes/__init__.py", line 418, in __getattr__
    dll = self._dlltype(name)
  File "/home/lab/psi4/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/lab/pyscf/pyscf/pyscf/lib/libnp_helper.so: undefined symbol: _gfortran_transfer_character_write

**Comment by hebrewsnabla** [comment]
> 
> 
> > I think the correct path is
> > ```
> > export PYTHONPATH=/home/lab/pyscf/pyscf:$PYTHONPATH
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > because your actual pyscf.scf directory is `/home/lab/pyscf/pyscf/pyscf/scf`.
> 
> thanks for replying.
> 
> I used to set this, but when I run a script I got these:
> 
> Traceback (most recent call last):
> File "/home/lab/pyscf/pyscf/pyscf/lib/misc.py", line 53, in load_library
> return numpy.ctypeslib.load_library(libname, _loaderpath)
> File "/home/lab/psi4/lib/python3.6/site-packages/numpy/ctypeslib.py", line 152, in load_library
> return ctypes.cdll[libpath]
> File "/home/lab/psi4/lib/python3.6/ctypes/**init**.py", line 423, in **getitem**
> return getattr(self, name)
> File "/home/lab/psi4/lib/python3.6/ctypes/**init**.py", line 418, in **getattr**
> dll = self._dlltype(name)
> File "/home/lab/psi4/lib/python3.6/ctypes/**init**.py", line 348, in **init**
> self._handle = _dlopen(self._name, mode)
> OSError: /home/lab/pyscf/pyscf/pyscf/lib/libnp_helper.so: undefined symbol: _gfortran_transfer_character_write
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "rhf.py", line 4, in
> from pyscf import gto, scf, lib
> File "/home/lab/pyscf/pyscf/pyscf/**init**.py", line 113, in
> from pyscf import lib
> File "/home/lab/pyscf/pyscf/pyscf/lib/**init**.py", line 24, in
> from pyscf.lib import numpy_helper
> File "/home/lab/pyscf/pyscf/pyscf/lib/numpy_helper.py", line 39, in
> _np_helper = misc.load_library('libnp_helper')
> File "/home/lab/pyscf/pyscf/pyscf/lib/misc.py", line 61, in load_library
> return numpy.ctypeslib.load_library(libname, libpath)
> File "/home/lab/psi4/lib/python3.6/site-packages/numpy/ctypeslib.py", line 152, in load_library
> return ctypes.cdll[libpath]
> File "/home/lab/psi4/lib/python3.6/ctypes/**init**.py", line 423, in **getitem**
> return getattr(self, name)
> File "/home/lab/psi4/lib/python3.6/ctypes/**init**.py", line 418, in **getattr**
> dll = self._dlltype(name)
> File "/home/lab/psi4/lib/python3.6/ctypes/**init**.py", line 348, in **init**
> self._handle = _dlopen(self._name, mode)
> OSError: /home/lab/pyscf/pyscf/pyscf/lib/libnp_helper.so: undefined symbol: _gfortran_transfer_character_write

Looks like conflict between multiple python environments in your machine. Usually pyscf should not invoke numpy in `/home/lab/psi4/lib`. You may need to determine which python you are using now (python from anaconda, system, or elsewhere) and reinstall numpy with corresponding manager, like conda or pip.

**Comment by rtransformation** [comment]
> > > I think the correct path is
> > > ```
> > > export PYTHONPATH=/home/lab/pyscf/pyscf:$PYTHONPATH
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > because your actual pyscf.scf directory is `/home/lab/pyscf/pyscf/pyscf/scf`.
> > 
> > 
> > thanks for replying.
> > I used to set this, but when I run a script I got these:
> > Traceback (most recent call last):
> > File "/home/lab/pyscf/pyscf/pyscf/lib/misc.py", line 53, in load_library
> > return numpy.ctypeslib.load_library(libname, _loaderpath)
> > File "/home/lab/psi4/lib/python3.6/site-packages/numpy/ctypeslib.py", line 152, in load_library
> > return ctypes.cdll[libpath]
> > File "/home/lab/psi4/lib/python3.6/ctypes/**init**.py", line 423, in **getitem**
> > return getattr(self, name)
> > File "/home/lab/psi4/lib/python3.6/ctypes/**init**.py", line 418, in **getattr**
> > dll = self._dlltype(name)
> > File "/home/lab/psi4/lib/python3.6/ctypes/**init**.py", line 348, in **init**
> > self._handle = _dlopen(self._name, mode)
> > OSError: /home/lab/pyscf/pyscf/pyscf/lib/libnp_helper.so: undefined symbol: _gfortran_transfer_character_write
> > During handling of the above exception, another exception occurred:
> > Traceback (most recent call last):
> > File "rhf.py", line 4, in
> > from pyscf import gto, scf, lib
> > File "/home/lab/pyscf/pyscf/pyscf/**init**.py", line 113, in
> > from pyscf import lib
> > File "/home/lab/pyscf/pyscf/pyscf/lib/**init**.py", line 24, in
> > from pyscf.lib import numpy_helper
> > File "/home/lab/pyscf/pyscf/pyscf/lib/numpy_helper.py", line 39, in
> > _np_helper = misc.load_library('libnp_helper')
> > File "/home/lab/pyscf/pyscf/pyscf/lib/misc.py", line 61, in load_library
> > return numpy.ctypeslib.load_library(libname, libpath)
> > File "/home/lab/psi4/lib/python3.6/site-packages/numpy/ctypeslib.py", line 152, in load_library
> > return ctypes.cdll[libpath]
> > File "/home/lab/psi4/lib/python3.6/ctypes/**init**.py", line 423, in **getitem**
> > return getattr(self, name)
> > File "/home/lab/psi4/lib/python3.6/ctypes/**init**.py", line 418, in **getattr**
> > dll = self._dlltype(name)
> > File "/home/lab/psi4/lib/python3.6/ctypes/**init**.py", line 348, in **init**
> > self._handle = _dlopen(self._name, mode)
> > OSError: /home/lab/pyscf/pyscf/pyscf/lib/libnp_helper.so: undefined symbol: _gfortran_transfer_character_write
> 
> Looks like conflict between multiple python environments in your machine. Usually pyscf should not invoke numpy in `/home/lab/psi4/lib`. You may need to determine which python you are using now (python from anaconda, system, or elsewhere) and reinstall numpy with corresponding manager, like conda or pip.

Thanks, the default python in my environment is indeed the one under the Psi4 program installation directory. I used to intall the lower version of pyscf and it worked. I am very confused what is happening now.😢

**Comment by rtransformation** [comment]
> Looks like conflict between multiple python environments in your machine. Usually pyscf should not invoke numpy in `/home/lab/psi4/lib`. You may need to determine which python you are using now (python from anaconda, system, or elsewhere) and reinstall numpy with corresponding manager, like conda or pip.

Thanks, the default python in my environment is indeed the one under the Psi4 program installation directory. I used to intall the lower version of pyscf and it worked. I am very confused what is happening now.😢

**Comment by verena-neufeld** [comment]
Hi @rtransformation , has this been resolved?

**Comment by sunqm** [comment]
It is likely a problem caused by runtime management. It cannot be fixed by pyscf package. To avoid messing up your python runtime environments, python virtualenv or conda virtual environment are often considered.
