### ISSUE TITLE
Error getting 1rdm after KCCSD calculation

### ISSUE THREAD

**Issue by tanvipg** [pyscf/pyscf#1040]
Hello,

Can you please help me resolve the following issue: I am trying to obtain a 1rdm after performing a KCCSD calculation for a single k point that is not the gamma point, as shown below (PySCF v1.7.6) :

```
import numpy
from   pyscf.pbc import gto,scf,cc,mp
cell = gto.M(a       = numpy.eye(3)*3.5668,
             atom    = '''Mg 0 0 0''',
             basis   = 'gth-dzv',
             pseudo  = 'gth-pade',
             verbose = 4)

kpts = numpy.ones((1,3))*0.1
mf   = scf.KRHF(cell,kpts).density_fit()
mf.kernel()
c = mp.KMP2(mf)
c.kernel()
c.make_rdm1()

c = cc.KCCSD(mf)
c.kernel()
c.make_rdm1()
```

The above code was able to produce the KMP2 based 1 body RDM, but fails when called for KCCSD with the following error:

```
Traceback (most recent call last):
  File "pyscf_1rdm_error.py", line 20, in <module>
    c.make_rdm1()
  File ".../lib/python3.8/site-packages/pyscf/cc/ccsd.py", line 1139, in make_rdm1
    if l1 is None: l1, l2 = self.solve_lambda(t1, t2)
  File ".../lib/python3.8/site-packages/pyscf/cc/ccsd.py", line 1079, in solve_lambda
    ccsd_lambda.kernel(self, eris, t1, t2, l1, l2,
  File ".../lib/python3.8/site-packages/pyscf/cc/ccsd_lambda.py", line 51, in kernel
    imds = fintermediates(mycc, t1, t2, eris)
  File ".../lib/python3.8/site-packages/pyscf/cc/ccsd_lambda.py", line 81, in make_intermediates
    nocc, nvir = t1.shape
ValueError: too many values to unpack (expected 2)

```

Is there a way to resolve this error and obtain a 1RDM for a KCCSD calculation at a single k point which is not the gamma point, please? 

Thank you very much for the help!

**Comment by xwang862** [comment]
1-RDM has been implemented for KMP2, but not for KCCSD. This error appeared because it tried to use the molecular CCSD's `make_rdm1()`, thus the `too many values to unpack` error. Here the `t1.shape` should be (nkpts, nocc, nvir).

If you are interested in gamma-point calculations, you can use `pbc/scf/RHF` (instead of `KRHF`), followed by molecular (DF-)MP2 and (DF-)CCSD. For example:

```
import numpy
from   pyscf.pbc import gto,scf,cc,mp
cell = gto.M(a       = numpy.eye(3)*3.5668,
             atom    = '''Mg 0 0 0''',
             basis   = 'gth-dzv',
             pseudo  = 'gth-pade',
             verbose = 4)

#kpts = numpy.ones((1,3))*0.1
mf   = scf.RHF(cell).density_fit()
mf.kernel()

from pyscf import mp, cc
c = mp.MP2(mf)
c.kernel()
c.make_rdm1()

c = cc.CCSD(mf)
c.kernel()
c.make_rdm1()
```

One caveat is that you might encounter complex number issues when feeding a non-gamma k point to `pbc/scf/RHF` to molecular CC.

**Comment by tanvipg** [comment]
Thank you for the response, Xiao. If possible, can you please comment if the functionality to get 1rdm for non-gamma k-points from KCCSD calculations will be available in the next few releases?

**Comment by tanvipg** [comment]
Sorry for closing and re-opening the issue. I was not sure if I should be closing the issue or not. If there is any guidance on this kindly let me know. Thank you for the help and tagging this issue as feature request.
