### ISSUE TITLE
ImportError: cannot import name 'tblis_einsum' from 'pyscf.lib'

### ISSUE THREAD

**Issue by Lancashire3000** [pyscf/pyscf#1108]
Hi,

  I tried to use `TBLIS` by

```
from pyscf import lib
from pyscf.lib import tblis_einsum
```

  the code leads to `ImportError: cannot import name 'tblis_einsum' from 'pyscf.lib' (/home/usr/intel/oneapi/intelpython/latest/lib/python3.7/site-packages/pyscf/lib/__init__.py)`
  
I did `pip3 install --upgrade pyscf` and get 
```
Requirement already satisfied: pyscf in /home/usr/intel/oneapi/intelpython/python3.7/lib/python3.7/site-packages (2.0.1)
Requirement already satisfied: numpy!=1.16,!=1.17,>=1.13 in /home/usr/intel/oneapi/intelpython/python3.7/lib/python3.7/site-packages (from pyscf) (1.20.3)
Requirement already satisfied: h5py>=2.7 in /home/usr/intel/oneapi/intelpython/python3.7/lib/python3.7/site-packages (from pyscf) (3.5.0)
Requirement already satisfied: scipy!=1.5.0,!=1.5.1 in /home/usr/intel/oneapi/intelpython/python3.7/lib/python3.7/site-packages (from pyscf) (1.6.2)
Requirement already satisfied: cached-property in /home/usr/intel/oneapi/intelpython/python3.7/lib/python3.7/site-packages (from h5py>=2.7->pyscf) (1.5.2)
```

I tried `pip3 install pyscf-tblis`, and got

```
Building wheel for pyscf-tblis (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/usr/intel/oneapi/intelpython/latest/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-mn7341w8/pyscf-tblis_e06722b049834019a923c5f236bd1759/setup.py'"'"'; __file__='"'"'/tmp/pip-install-mn7341w8/pyscf-tblis_e06722b049834019a923c5f236bd1759/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-6py51m6n
       cwd: /tmp/pip-install-mn7341w8/pyscf-tblis_e06722b049834019a923c5f236bd1759/
  Complete output (7 lines):
  running bdist_wheel
  running build
  running build_ext
  Configuring extensions
  cmake -S/tmp/pip-install-mn7341w8/pyscf-tblis_e06722b049834019a923c5f236bd1759/pyscf/tblis_einsum -Bbuild/temp.linux-x86_64-3.7
  unable to execute 'cmake': No such file or directory
  error: command 'cmake' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for pyscf-tblis
  Running setup.py clean for pyscf-tblis
Failed to build pyscf-tblis
Installing collected packages: pyscf-tblis
    Running setup.py install for pyscf-tblis ... error
    ERROR: Command errored out with exit status 1:
     command: /home/usr/intel/oneapi/intelpython/latest/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-mn7341w8/pyscf-tblis_e06722b049834019a923c5f236bd1759/setup.py'"'"'; __file__='"'"'/tmp/pip-install-mn7341w8/pyscf-tblis_e06722b049834019a923c5f236bd1759/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-gk98d6v5/install-record.txt --single-version-externally-managed --compile --install-headers /home/usr/intel/oneapi/intelpython/latest/include/python3.7m/pyscf-tblis
         cwd: /tmp/pip-install-mn7341w8/pyscf-tblis_e06722b049834019a923c5f236bd1759/
    Complete output (7 lines):
    running install
    running build
    running build_ext
    Configuring extensions
    cmake -S/tmp/pip-install-mn7341w8/pyscf-tblis_e06722b049834019a923c5f236bd1759/pyscf/tblis_einsum -Bbuild/temp.linux-x86_64-3.7
    unable to execute 'cmake': No such file or directory
    error: command 'cmake' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/usr/intel/oneapi/intelpython/latest/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-mn7341w8/pyscf-tblis_e06722b049834019a923c5f236bd1759/setup.py'"'"'; __file__='"'"'/tmp/pip-install-mn7341w8/pyscf-tblis_e06722b049834019a923c5f236bd1759/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-gk98d6v5/install-record.txt --single-version-externally-managed --compile --install-headers /home/usr/intel/oneapi/intelpython/latest/include/python3.7m/pyscf-tblis Check the logs for full command output.

```

any solution? thanks

**Comment by Lancashire3000** [comment]
After `pip install cmake`, I got

```
  Building wheel for pyscf-tblis (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/usr/intel/oneapi/intelpython/latest/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-zhs9djs6/pyscf-tblis_12ca81ffeb36404b87fa612f2f78a922/setup.py'"'"'; __file__='"'"'/tmp/pip-install-zhs9djs6/pyscf-tblis_12ca81ffeb36404b87fa612f2f78a922/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-muoz8ysq
       cwd: /tmp/pip-install-zhs9djs6/pyscf-tblis_12ca81ffeb36404b87fa612f2f78a922/
  Complete output (8 lines):
  running bdist_wheel
  running build
  running build_ext
  Configuring extensions
  cmake -S/tmp/pip-install-zhs9djs6/pyscf-tblis_12ca81ffeb36404b87fa612f2f78a922/pyscf/tblis_einsum -Bbuild/temp.linux-x86_64-3.7
  CMake Error: The source directory "/tmp/pip-install-zhs9djs6/pyscf-tblis_12ca81ffeb36404b87fa612f2f78a922/pyscf/tblis_einsum" does not appear to contain CMakeLists.txt.
  Specify --help for usage, or press the help button on the CMake GUI.
  error: command 'cmake' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for pyscf-tblis
  Running setup.py clean for pyscf-tblis
Failed to build pyscf-tblis
Installing collected packages: pyscf-tblis
    Running setup.py install for pyscf-tblis ... error
    ERROR: Command errored out with exit status 1:
     command: /home/usr/intel/oneapi/intelpython/latest/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-zhs9djs6/pyscf-tblis_12ca81ffeb36404b87fa612f2f78a922/setup.py'"'"'; __file__='"'"'/tmp/pip-install-zhs9djs6/pyscf-tblis_12ca81ffeb36404b87fa612f2f78a922/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-su15fz1t/install-record.txt --single-version-externally-managed --compile --install-headers /home/usr/intel/oneapi/intelpython/latest/include/python3.7m/pyscf-tblis
         cwd: /tmp/pip-install-zhs9djs6/pyscf-tblis_12ca81ffeb36404b87fa612f2f78a922/
    Complete output (8 lines):
    running install
    running build
    running build_ext
    Configuring extensions
    cmake -S/tmp/pip-install-zhs9djs6/pyscf-tblis_12ca81ffeb36404b87fa612f2f78a922/pyscf/tblis_einsum -Bbuild/temp.linux-x86_64-3.7
    CMake Error: The source directory "/tmp/pip-install-zhs9djs6/pyscf-tblis_12ca81ffeb36404b87fa612f2f78a922/pyscf/tblis_einsum" does not appear to contain CMakeLists.txt.
    Specify --help for usage, or press the help button on the CMake GUI.
    error: command 'cmake' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/usr/intel/oneapi/intelpython/latest/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-zhs9djs6/pyscf-tblis_12ca81ffeb36404b87fa612f2f78a922/setup.py'"'"'; __file__='"'"'/tmp/pip-install-zhs9djs6/pyscf-tblis_12ca81ffeb36404b87fa612f2f78a922/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-su15fz1t/install-record.txt --single-version-externally-managed --compile --install-headers /home/usr/intel/oneapi/intelpython/latest/include/python3.7m/pyscf-tblis Check the logs for full command output.
```

**Comment by jamesETsmith** [comment]
@Lancashire3000, thanks for letting us know, this problem (of CMakeLists.txt files not showing up on Pip) has shown up in some other [places too](https://github.com/pyscf/pyscf/issues/1096#issuecomment-963257819). The sources were added to the package on pip yesterday so they should work now. Let us know if they're still giving you trouble!

**Comment by Lancashire3000** [comment]
@jamesETsmith  Thank you very much. I tried `pip install pyscf-tblis` and got 
```
Collecting pyscf-tblis
  Downloading pyscf-tblis-0.1.3.tar.gz (8.9 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in /home/cwang-3/intel/oneapi/intelpython/python3.7/lib/python3.7/site-packages (from pyscf-tblis) (1.20.3)
Building wheels for collected packages: pyscf-tblis
  Building wheel for pyscf-tblis (setup.py) ... done
  Created wheel for pyscf-tblis: filename=pyscf_tblis-0.1.3-cp37-cp37m-linux_x86_64.whl size=40825 sha256=78f698adf9afe28fb2acd6f02185e69c3ee97aa745e11f85fc9613db3b73fc5b
  Stored in directory: /home/usr/.cache/pip/wheels/02/21/dd/011683e41312e781fc23d44f4a43255977da86bd91cf22b98b
Successfully built pyscf-tblis

Installing collected packages: pyscf-tblis
Successfully installed pyscf-tblis-0.1.3
```

Then,
```
>>> from pyscf import lib
>>> from pyscf.lib import tblis_einsum
```
but still met 
```
  from pyscf.lib import tblis_einsum
ImportError: cannot import name 'tblis_einsum' from 'pyscf.lib' (/home/usr/intel/oneapi/intelpython/latest/lib/python3.7/site-packages/pyscf/lib/__init__.py)
```

**Comment by Lancashire3000** [comment]
@jamesETsmith  Thank you very much. I tried `pip install pyscf-tblis` and got 
```
Collecting pyscf-tblis
  Downloading pyscf-tblis-0.1.3.tar.gz (8.9 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in /home/usr/intel/oneapi/intelpython/python3.7/lib/python3.7/site-packages (from pyscf-tblis) (1.20.3)
Building wheels for collected packages: pyscf-tblis
  Building wheel for pyscf-tblis (setup.py) ... done
  Created wheel for pyscf-tblis: filename=pyscf_tblis-0.1.3-cp37-cp37m-linux_x86_64.whl size=40825 sha256=78f698adf9afe28fb2acd6f02185e69c3ee97aa745e11f85fc9613db3b73fc5b
  Stored in directory: /home/usr/.cache/pip/wheels/02/21/dd/011683e41312e781fc23d44f4a43255977da86bd91cf22b98b
Successfully built pyscf-tblis

Installing collected packages: pyscf-tblis
Successfully installed pyscf-tblis-0.1.3
```


Then,
```
>>> from pyscf import lib
>>> from pyscf.lib import tblis_einsum
```
but still met 
```
  from pyscf.lib import tblis_einsum
ImportError: cannot import name 'tblis_einsum' from 'pyscf.lib' (/home/usr/intel/oneapi/intelpython/latest/lib/python3.7/site-packages/pyscf/lib/__init__.py)
```

I am not sure if `https://python.hotexamples.com/examples/pyscf.lib.tblis_einsum/-/_contract/python-_contract-function-examples.html` is a right example, as `from pyscf.lib import tblis_einsum`

**Comment by fishjojo** [comment]
The library files are not correctly included in the built wheel currently. There will be a fix.

**Comment by Lancashire3000** [comment]
Thanks for the information. Is there any other way to use tblis via python at this moment?  In https://github.com/pyscf/pyscf/issues/835, 
```You can try to compile the TBLIS interface when compiling the C extensions. http://pyscf.org/pyscf/install.html#tblis```
the link is `404` at this moment

**Comment by jamesETsmith** [comment]
@Lancashire3000 I think that link is pointing to outdated docs which is why you can't see them any more (updated docs about extensions are [here](https://pyscf.org/install.html#extension-modules)). Since the library files aren't correctly included in the built wheel, you can try pip installing from git wth `pip install git+git@github.com:pyscf/pyscf-tblis.git` which will build the wheel locally for you.

**Comment by Lancashire3000** [comment]
@jamesETsmith  Thank you very much. I tried `pip install git+git@github.com:pyscf/pyscf-tblis.git`, and got 
```
ERROR: Invalid requirement: 'git+git@github.com:pyscf/pyscf-tblis.git'
Hint: It looks like a path. File 'git+git@github.com:pyscf/pyscf-tblis.git' does not exist.
``` 
Do I need to replace anything in `git+git`? or better wait until the fix is released?

**Comment by Lancashire3000** [comment]
@jamesETsmith thanks. I tried `pip install git+https://github.com/pyscf/pyscf-tblis.git` on two windows subsystem linux, ubuntu on Windows 16.04 & 20. Ubuntu 16 one gives me  
```
Collecting git+https://github.com/pyscf/pyscf-tblis.git
  Cloning https://github.com/pyscf/pyscf-tblis.git to /tmp/pip-req-build-0xk_oc0o
  Running command git clone -q https://github.com/pyscf/pyscf-tblis.git /tmp/pip-req-build-0xk_oc0o
Requirement already satisfied: numpy in /home/usr/anaconda3/lib/python3.8/site-packages (from pyscf-tblis==0.1.3) (1.21.2)
Building wheels for collected packages: pyscf-tblis
  Building wheel for pyscf-tblis (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/usr/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-0xk_oc0o/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-0xk_oc0o/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-_47nbu6n
       cwd: /tmp/pip-req-build-0xk_oc0o/
  Complete output (7 lines):
  running bdist_wheel
  running build
  running build_ext
  Configuring extensions
  cmake -S/tmp/pip-req-build-0xk_oc0o/pyscf/tblis_einsum -Bbuild/temp.linux-x86_64-3.8
  cmake: relocation error: cmake: symbol _ZTVNSt7__cxx1115basic_stringbufIcSt11char_traitsIcESaIcEEE, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference
  error: command 'cmake' failed with exit status 127
  ----------------------------------------
  ERROR: Failed building wheel for pyscf-tblis
  Running setup.py clean for pyscf-tblis
Failed to build pyscf-tblis
Installing collected packages: pyscf-tblis
    Running setup.py install for pyscf-tblis ... error
    ERROR: Command errored out with exit status 1:
     command: /home/usr/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-0xk_oc0o/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-0xk_oc0o/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-cr3sdw2m/install-record.txt --single-version-externally-managed --compile --install-headers /home/usr/anaconda3/include/python3.8/pyscf-tblis
         cwd: /tmp/pip-req-build-0xk_oc0o/
    Complete output (7 lines):
    running install
    running build
    running build_ext
    Configuring extensions
    cmake -S/tmp/pip-req-build-0xk_oc0o/pyscf/tblis_einsum -Bbuild/temp.linux-x86_64-3.8
    cmake: relocation error: cmake: symbol _ZTVNSt7__cxx1115basic_stringbufIcSt11char_traitsIcESaIcEEE, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference
    error: command 'cmake' failed with exit status 127
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/usr/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-0xk_oc0o/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-0xk_oc0o/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-cr3sdw2m/install-record.txt --single-version-externally-managed --compile --install-headers /home/usr/anaconda3/include/python3.8/pyscf-tblis Check the logs for full command output.
```

on ubuntu 20 it gives me
```
Collecting git+https://github.com/pyscf/pyscf-tblis.git
  Cloning https://github.com/pyscf/pyscf-tblis.git to /tmp/pip-req-build-kp4v7aqn
  Running command git clone --filter=blob:none -q https://github.com/pyscf/pyscf-tblis.git /tmp/pip-req-build-kp4v7aqn
  Resolved https://github.com/pyscf/pyscf-tblis.git to commit b8bb984894696dac6aae43151e86ffedee74abfb
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in /home/usr-3/intel/oneapi/intelpython/python3.7/lib/python3.7/site-packages (from pyscf-tblis==0.1.3) (1.20.3)
```
 then import  `from pyscf import tblis_einsum` leads to
```
Traceback (most recent call last):
  File "srci_v99_py3_einsum_deltatensor.py", line 12, in <module>
    from pyscf import tblis_einsum
  File "/home/usr-3/intel/oneapi/intelpython/latest/lib/python3.7/site-packages/pyscf/tblis_einsum/__init__.py", line 3, in <module>
    from .tblis_einsum import contract
  File "/home/usr-3/intel/oneapi/intelpython/latest/lib/python3.7/site-packages/pyscf/tblis_einsum/tblis_einsum.py", line 21, in <module>
    libtblis = numpy.ctypeslib.load_library('libtblis_einsum', os.path.dirname(__file__))
  File "/home/usr-3/intel/oneapi/intelpython/latest/lib/python3.7/site-packages/numpy/ctypeslib.py", line 153, in load_library
    raise OSError("no file with expected extension")
OSError: no file with expected extension
``` 
:(

**Comment by sunqm** [comment]
I updated the build script of pyscf-tblis in recent updates. `pip install git+https://github.com/pyscf/pyscf-tblis.git` is working now on linux platform.

**Comment by Lancashire3000** [comment]
Thank you so much. I think I get it work on Ubuntu 20.04.3 LTS on windows 10, after a few attempts. I am not sure if my miserable experience related to some complexities of the versions I have installed, though I think I tried to update them.

Let me starts from a summary
`sudo pip3 install`;
package to the same directory
check `_contract` vs `contract` in `tblis`

1)
` pip install git+https://github.com/pyscf/pyscf-tblis.git` leads to

```
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Defaulting to user installation because normal site-packages is not writeable
Collecting git+https://github.com/pyscf/pyscf-tblis.git
  Cloning https://github.com/pyscf/pyscf-tblis.git to /tmp/pip-req-build-RlVeyV
  Running command git clone -q https://github.com/pyscf/pyscf-tblis.git /tmp/pip-req-build-RlVeyV
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python2 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-RlVeyV/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-RlVeyV/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-vsFLvK
         cwd: /tmp/pip-req-build-RlVeyV/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-RlVeyV/setup.py", line 57
        cmd = ['cmake', f'-S{src_dir}', f'-B{self.build_temp}']
                                     ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

2)
`pip3 install git+https://github.com/pyscf/pyscf-tblis.git` leads to
```
Collecting git+https://github.com/pyscf/pyscf-tblis.git
  Cloning https://github.com/pyscf/pyscf-tblis.git to /tmp/pip-req-build-m7pjairk
  Running command git clone --filter=blob:none -q https://github.com/pyscf/pyscf-tblis.git /tmp/pip-req-build-m7pjairk
  Resolved https://github.com/pyscf/pyscf-tblis.git to commit a1efbc00577ae8d0fdefa0a0cc07d615877c937c
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in ./intel/oneapi/intelpython/python3.7/lib/python3.7/site-packages (from pyscf-tblis==0.1.3) (1.21.4)
```

3)
`sudo pip3 install git+https://github.com/pyscf/pyscf-tblis.git` leads to 
```
Collecting git+https://github.com/pyscf/pyscf-tblis.git
  Cloning https://github.com/pyscf/pyscf-tblis.git to /tmp/pip-req-build-ofabqqf_
  Running command git clone -q https://github.com/pyscf/pyscf-tblis.git /tmp/pip-req-build-ofabqqf_
Requirement already satisfied (use --upgrade to upgrade): pyscf-tblis==0.1.3 from git+https://github.com/pyscf/pyscf-tblis.git in /usr/local/lib/python3.8/dist-packages
Requirement already satisfied: numpy in /usr/local/lib/python3.8/dist-packages (from pyscf-tblis==0.1.3) (1.21.4)
Building wheels for collected packages: pyscf-tblis
  Building wheel for pyscf-tblis (setup.py) ... done
  Created wheel for pyscf-tblis: filename=pyscf_tblis-0.1.3-cp38-cp38-linux_x86_64.whl size=7301668 sha256=f132cb4804c882e6cecbb9925d21b7a28581873a3311a1bb60f1317b0768ca6e
  Stored in directory: /tmp/pip-ephem-wheel-cache-5afaea4l/wheels/61/98/fc/d59879be5db98e21f85a1850f3ad45cab78a5ef8f9b7f2d118
Successfully built pyscf-tblis
```
looks good. 

4) the subsequent thing is, if I `from pyscf import tblis_einsum`, it asks the library at the other path `/home/usr/intel/oneapi/intelpython/latest/lib/python3.7/site-packages/pyscf`, like in my previous comment
I can copy the directory in `/usr/local/lib/python3.8/dist-packages` to `/home/usr/intel/oneapi/intelpython/latest/lib/python3.7/site-packages/pyscf` , then it starts to work

5) I tried similar calculations as https://python.hotexamples.com/examples/pyscf.lib.tblis_einsum/-/_contract/python-_contract-function-examples.html, I got something like (don't remember exactly, tried lot of things)

```
  File "/home/usr/intel/oneapi/intelpython/latest/lib/python3.7/site-packages/pyscf/lib/numpy_helper.py", line 116, in _contract
    return tblis_einsum._contract(idx_str, A, B, **kwargs)
AttributeError: module 'pyscf.tblis_einsum' has no attribute '_contract'
```
  The thing is, there is `         return tblis_einsum._contract(idx_str, A, B, **kwargs)` in `numpy_helper.py` and the https://github.com/pyscf/pyscf-tblis/blob/master/pyscf/tblis_einsum/tblis_einsum.py
  used `def contract(subscripts, *tensors, **kwargs):`

  once I set to consistent (in my case I used `_contract`), everything works.

Epilogue 
  I tried `c0 = tblis_einsum._contract('ijk,jlk,li->', a, b, c1)` got `ValueError: more operands provided to einstein sum function than specified in the subscripts string`, seems `tblis` supports `GEMM` type operation https://github.com/devinamatthews/tblis/wiki/Tensor-Operations

  then for multiple contractions, perhaps one has to somehow fit `tblis` into binary level of `einsum` or `opt-einsum`, or factorized the contractions at binary level.
