### ISSUE TITLE
NameError: name 'pbc' is not defined and other errors

### ISSUE THREAD

**Issue by jeffhammond** [pyscf/pyscf#1131]
I think I have installed PySCF successfully:
```
jhammond@nuclear:~/pyscf/examples/2-benchmark$ pip install pyscf
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pyscf in /home/jhammond/.local/lib/python3.8/site-packages (2.0.0a0)
Requirement already satisfied: numpy!=1.16,!=1.17,>1.8 in /home/jhammond/.local/lib/python3.8/site-packages (from pyscf) (1.20.3)
Requirement already satisfied: scipy!=1.5.0,!=1.5.1 in /home/jhammond/.local/lib/python3.8/site-packages (from pyscf) (1.6.3)
Requirement already satisfied: h5py>=2.6 in /home/jhammond/.local/lib/python3.8/site-packages (from pyscf) (3.2.1)
```

None of the examples work.  I suspect I know how to solve the clock/time one, but the gto and pbc errors suggest something is wrong with PySCF specifically.

```
jhammond@nuclear:~/pyscf/examples/2-benchmark$ python3 ./bz.py 
model name	: 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
MemTotal:       16048388 kB
OMP_NUM_THREADS=None

Traceback (most recent call last):
  File "./bz.py", line 34, in <module>
    cpu0 = time.clock(), time.time()
AttributeError: module 'time' has no attribute 'clock'
jhammond@nuclear:~/pyscf/examples/2-benchmark$ python3 ./c60.py 
model name	: 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
MemTotal:       16048388 kB
OMP_NUM_THREADS=None

Traceback (most recent call last):
  File "./c60.py", line 24, in <module>
    cpu0 = time.clock(), time.time()
AttributeError: module 'time' has no attribute 'clock'
jhammond@nuclear:~/pyscf/examples/2-benchmark$ python3 ./ccsd_iteration.py 
model name	: 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
MemTotal:       16048388 kB
OMP_NUM_THREADS=None

Traceback (most recent call last):
  File "./ccsd_iteration.py", line 19, in <module>
    mol = gto.M(atom=['H 0 0 %f' % i for i in range(n)],
NameError: name 'gto' is not defined
jhammond@nuclear:~/pyscf/examples/2-benchmark$ python3 ./fci_iteration.py 
model name	: 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
MemTotal:       16048388 kB
OMP_NUM_THREADS=None

Traceback (most recent call last):
  File "./fci_iteration.py", line 29, in <module>
    cpu0 = time.clock(), time.time()
AttributeError: module 'time' has no attribute 'clock'
jhammond@nuclear:~/pyscf/examples/2-benchmark$ python3 ./fock_multigrid.py 
model name	: 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
MemTotal:       16048388 kB
OMP_NUM_THREADS=None

Traceback (most recent call last):
  File "./fock_multigrid.py", line 223, in <module>
    cell = pbc.tools.super_cell(cell0, images)
NameError: name 'pbc' is not defined
```

Do you have any suggestions for how I should debug/fix this?

Thanks!

**Comment by jeffhammond** [comment]
Other examples work fine, so this is something specific to the benchmarks, it seems.
```
jhammond@nuclear:~/pyscf/examples/cc$ python3  00-simple_ccsd.py 
converged SCF energy = -99.9873974403488
E(CCSD) = -100.2037350702557  E_corr = -0.2163376299069311
CCSD correlation energy -0.21633762990693114
jhammond@nuclear:~/pyscf/examples/cc$ python3  00-simple_ccsd_t.py 
converged SCF energy = -99.9873974403487
E(CCSD) = -100.2037350702095  E_corr = -0.2163376298607412
CCSD(T) correction = -0.00241369115753732
CCSD(T) correlation energy -0.2187513210182785
converged SCF energy = -99.9873974403486  <S^2> = 5.4178884e-13  2S+1 = 1
E(UCCSD) = -100.2037349606915  E_corr = -0.2163375203428591
UCCSD(T) correction = -0.0024136901009891
UCCSD(T) correlation energy -0.21875121044384818
```

**Comment by verena-neufeld** [comment]
Hi Jeff,

thanks for pointing this out. It seems that either something like pbc.tools needs to be changed to “pyscf.pbc.tools” or pbc needs to be explicitly imported like “from pyscf import pbc”. This should probably be updated in the examples.

thanks, Verena

**Comment by jamesETsmith** [comment]
For the the other benchmarks, there was a change in Python's native `time` module so we need to replace `time.clock` with `time.perf_counter` (same as #368 and #702). I'll open a PR later today to address these changes and the ones @verena-neufeld mentioned.
