### ISSUE TITLE
Dynamic level shift fails with UHF

### ISSUE THREAD

**Issue by susilehtola** [pyscf/pyscf#1216]
```
import pyscf

mol = pyscf.M(
    atom = 'H 0 0 0; F 0 0 1.1',  # in Angstrom
    basis = 'ccpvdz',
    symmetry = True,
    charge = 1,
    spin = 1,
    verbose = 4
)

myhf = mol.UHF()
pyscf.scf.addons.dynamic_level_shift_(myhf, factor=0.5)
myhf.kernel()
```
leads to
```
Traceback (most recent call last):
  File "/tmp/level.py", line 27, in <module>
    myhf.kernel()
  File "/home/work/pyscf/pyscf/lib/misc.py", line 638, in aliased_fn
    return getattr(self, fname)(*args, **kwargs)
  File "/home/work/pyscf/pyscf/scf/hf.py", line 1667, in scf
    kernel(self, self.conv_tol, self.conv_tol_grad,
  File "/home/work/pyscf/pyscf/scf/hf.py", line 171, in kernel
    fock = mf.get_fock(h1e, s1e, vhf, dm, cycle, mf_diis)
  File "/home/work/pyscf/pyscf/scf/addons.py", line 205, in get_fock
    ehf =(numpy.einsum('ij,ji', h1e, dm) +
  File "<__array_function__ internals>", line 5, in einsum
  File "/usr/lib64/python3.10/site-packages/numpy/core/einsumfunc.py", line 1359, in einsum
    return c_einsum(*operands, **kwargs)
ValueError: operand has more dimensions than subscripts given in einstein sum, but no '...' ellipsis provided to broadcast the extra dimensions.
```

**Comment by susilehtola** [comment]
Looks like the dynamic level shifting is also limited to HF...
