### ISSUE TITLE
Pull request #1209 broke nuclear gradients of symmetric molecules in unconventional orientations

### ISSUE THREAD

**Issue by MatthewRHermes** [pyscf/pyscf#1238]
Ever since PR #1209, nuclear gradients of symmetric molecules seem to be broken unless the molecules are specified in some 'conventional' choice of axes. This is separate from the issue being addressed by PR #1237. The same molecule gives different gradients or even crashes if I choose the axes differently:

```
from pyscf import gto, scf

print ("LiH")
mol = gto.M (atom = 'Li 0 0 0; H 0 0 1', basis='sto-3g', symmetry=True,
    verbose=0)
print (scf.RHF (mol).run ().nuc_grad_method ().kernel ())
mol = gto.M (atom = 'Li 0 0 0; H 1 0 0', basis='sto-3g', symmetry=True,
    verbose=0)
print (scf.RHF (mol).run ().nuc_grad_method ().kernel ())
mol = gto.M (atom = 'Li 0 0 0; H 0 1 0', basis='sto-3g', symmetry=True,
    verbose=0)
print (scf.RHF (mol).run ().nuc_grad_method ().kernel ())

print ("\nH2")
mol = gto.M (atom = 'H 0 0 0; H 0 0 1', basis='sto-3g', symmetry=True,
    verbose=0)
print (scf.RHF (mol).run ().nuc_grad_method ().kernel ())
mol = gto.M (atom = 'H 0 0 0; H 1 0 0', basis='sto-3g', symmetry=True,
    verbose=0)
print (scf.RHF (mol).run ().nuc_grad_method ().kernel ())
mol = gto.M (atom = 'H 0 0 0; H 0 1 0', basis='sto-3g', symmetry=True,
    verbose=0)
print (scf.RHF (mol).run ().nuc_grad_method ().kernel ())
```

The output of this should be (this is from commit 1e874d18e, the last time this worked):

```
LiH
[[ 0.          0.          0.26651453]
 [ 0.          0.         -0.26651453]]
[[ 2.66514530e-01  0.00000000e+00  5.91781135e-17]
 [-2.66514530e-01  0.00000000e+00 -5.91781135e-17]]
[[ 1.63193083e-17  2.66514530e-01  5.91781135e-17]
 [-1.63193083e-17 -2.66514530e-01 -5.91781135e-17]]

H2
[[ 0.          0.         -0.14857157]
 [ 0.          0.          0.14857157]]
[[-1.48571575e-01  0.00000000e+00 -3.29895166e-17]
 [ 1.48571575e-01  0.00000000e+00  3.29895166e-17]]
[[-9.09738516e-18 -1.48571575e-01 -3.29895166e-17]
 [ 9.09738516e-18  1.48571575e-01  3.29895166e-17]]
 ```

Using either 5b3fdd618 or 6eeeff99a, I get this obviously wrong output:

```
LiH
[[ 0.          0.          0.26651453]
 [ 0.          0.         -0.26651453]]
[[ 0.00000000e+00  0.00000000e+00  1.73688689e-17]
 [ 0.00000000e+00  0.00000000e+00 -1.73688689e-17]]
[[ 0.00000000e+00  0.00000000e+00  1.73688689e-17]
 [ 0.00000000e+00  0.00000000e+00 -1.73688689e-17]]

H2
[[ 0.          0.         -0.14857157]
 [ 0.          0.          0.14857157]]
Traceback (most recent call last):
  File "h2_grad.py", line 20, in <module>
    print (scf.RHF (mol).run ().nuc_grad_method ().kernel ())
  File "/home/herme068/anaconda3/envs/pyscf/lib/python3.7/site-packages/pyscf/grad/rhf.py", line 395, in kernel
    self.de = self.symmetrize(self.de, atmlst)
  File "/home/herme068/anaconda3/envs/pyscf/lib/python3.7/site-packages/pyscf/grad/rhf.py", line 363, in symmetrize
    return symmetrize(self.mol, de, atmlst)
  File "", line 211, in symmetrize
    a_id = pmol.irrep_id.index(0)
ValueError: 0 is not in list
```

By commenting out lines 394 and 395 of pyscf/grad/rhf.py, I confirmed that the problem for both molecules lies in the "symmetrize" function. But I don't understand what's going on in that function, so I can't offer a bugfix.

**Comment by sunqm** [comment]
Thanks @MatthewRHermes for catching this bug. It's fixed in the latest commit of PR 1237

**Comment by MatthewRHermes** [comment]
Thanks, that seems to fix the issue.
