### ISSUE TITLE
Reading density matrix with mf.from_chk() fails in periodic systems

### ISSUE THREAD

**Issue by cychow2** [pyscf/pyscf#1317]
Hi, I notice reading the density matrix from a check file produced from a calculation with a smaller basis set, using `mf.from_chk()`, and projecting to a larger basis set, works fine for molecules, but maybe not for periodic systems.

### Here's a **working example** (a molecule):

Small basis calculation that produces mol_dz.hdf5
```
from pyscf import gto, dft

cell = gto.M(
    atom = '''H     0.      0.      0.    
              F     0.  0.  1.72''',
    basis = 'ccpvdz',
    verbose = 3,
)

mf = dft.KS(cell).density_fit()
mf.chkfile='mol_dz.hdf5'
mf.kernel()
```

Output
`converged SCF energy = -99.6313841565319`

Larger basis calculation that takes in mol_dz.hdf5 and projects the density matrix to its larger basis
```
from pyscf import gto, dft

cell = gto.M(
    atom = '''H     0.      0.      0.    
              F     0.  0.  1.72''',
    basis = 'ccpvtz',
    verbose = 3,
)

mf = dft.KS(cell).density_fit()
dm = mf.from_chk("mol_dz.hdf5")
mf.kernel(dm)
```

Output
`converged SCF energy = -99.6796310048301`

### Here's a **failing example** (a periodic system):

Small basis calculation that produces periodic_sz.hdf5
```
from pyscf.pbc import gto, dft
import numpy

cell = gto.M(
    a = numpy.eye(3)*3.5668,
    atom = '''C     0.      0.      0.    
              C     0.8917  0.8917  0.8917
              C     1.7834  1.7834  0.    
              C     2.6751  2.6751  0.8917
              C     1.7834  0.      1.7834
              C     2.6751  0.8917  2.6751
              C     0.      1.7834  1.7834
              C     0.8917  2.6751  2.6751''',
    basis = 'gth-szv',
    pseudo = 'gth-pade',
    verbose = 3,
)

kmesh = cell.make_kpts([2,2,2])
kmf = dft.KRKS(cell, kmesh).density_fit()
kmf.xc = 'm06,m06'
kmf.chkfile='periodic_sz.hdf5'
kmf.kernel()
```

Output
`converged SCF energy = -45.3857849498665`

Larger basis calculation that takes in periodic_sz.hdf5 and projects the density matrix to its larger basis
```
from pyscf.pbc import gto, dft
import numpy

cell = gto.M(
    a = numpy.eye(3)*3.5668,
    atom = '''C     0.      0.      0.    
              C     0.8917  0.8917  0.8917
              C     1.7834  1.7834  0.    
              C     2.6751  2.6751  0.8917
              C     1.7834  0.      1.7834
              C     2.6751  0.8917  2.6751
              C     0.      1.7834  1.7834
              C     0.8917  2.6751  2.6751''',
    basis = 'gth-dzv',
    pseudo = 'gth-pade',
    verbose = 3,
)

kmesh = cell.make_kpts([2,2,2])
kmf = dft.KRKS(cell, kmesh).density_fit()
kmf.xc = 'm06,m06'
dm = kmf.from_chk("periodic_sz.hdf5")
kmf.kernel(dm)
```

Output
```
Traceback (most recent call last):
  File "periodic_read_sz.py", line 22, in <module>
    dm = kmf.from_chk("periodic_sz.hdf5")
  File "/home/chunyu/.local/lib/python3.8/site-packages/pyscf/pbc/scf/khf.py", line 729, in from_chk
    return self.init_guess_by_chkfile(chk, project, kpts)
  File "/home/chunyu/.local/lib/python3.8/site-packages/pyscf/pbc/scf/khf.py", line 727, in init_guess_by_chkfile
    return init_guess_by_chkfile(self.cell, chk, project, kpts)
  File "/home/chunyu/.local/lib/python3.8/site-packages/pyscf/pbc/scf/khf.py", line 356, in init_guess_by_chkfile
    dm = kuhf.init_guess_by_chkfile(cell, chkfile_name, project, kpts)
  File "/home/chunyu/.local/lib/python3.8/site-packages/pyscf/pbc/scf/kuhf.py", line 348, in init_guess_by_chkfile
    dm = makedm((mo, mo), (mo_occa, mo_occb))
  File "/home/chunyu/.local/lib/python3.8/site-packages/pyscf/pbc/scf/kuhf.py", line 331, in makedm
    mos =([fproj(mo, None) for mo in moa],
  File "/home/chunyu/.local/lib/python3.8/site-packages/pyscf/pbc/scf/kuhf.py", line 331, in <listcomp>
    mos =([fproj(mo, None) for mo in moa],
  File "/home/chunyu/.local/lib/python3.8/site-packages/pyscf/pbc/scf/kuhf.py", line 324, in fproj
    norm = np.einsum('pi,pi->i', c.conj(), s[k].dot(c))
ValueError: shapes (64,64) and (32,) not aligned: 64 (dim 1) != 32 (dim 0)
```

It seems that this error only occurs when the basis sets are not the same and the system is periodic.

**Comment by hebrewsnabla** [comment]
I think that's caused by a bug here
https://github.com/pyscf/pyscf/blob/f985dde7358409e4e71095575172327af795a6cb/pyscf/pbc/scf/kuhf.py#L318-L333

At line 333, `fproj(mo, None)` is called with a single-k-point mo and no kpts info, but in function fproj, there's always a loop over k-point.
I suggest changing L332-333 into
```
mos = (fproj(moa, kpts), fproj(mob, kpts))
```
