### ISSUE TITLE
initial guess bug when GTH pseudo potential is used

### ISSUE THREAD

**Issue by zhcui** [pyscf/pyscf#1361]
Hi all,

I encountered a bug when using GTH pseudopotential. The script is the following:

```
#!/usr/bin/env python

import numpy as np
from pyscf.pbc import gto, dft 

cell = gto.Cell()
cell.a = np.eye(3) * 10.0
cell.atom = [['Cu', [0.0, 0.0, 0.0]],
             ['O', [0.0, 0.0, 1.0]]]
cell.basis = {'Cu': 'gth-szv-molopt-sr', "O": 'gth-szv-molopt-sr'}
cell.pseudo = {'Cu': 'GTH-PBE-q19', "O": 'GTH-PBE'}
cell.verbose = 5 
cell.build()

kmf = dft.KRKS(cell, cell.make_kpts([1, 1, 1])).density_fit()
dm0 = kmf.get_init_guess()
```

The error in output is like the following:
```
 Traceback (most recent call last):
  File "test.py", line 16, in <module>
    dm0 = kmf.get_init_guess()
  File "/home/zhcui/program/pyscf_ZHC_kpt_symm/pyscf/pbc/scf/khf.py", line 578, in get_init_guess
    dm = self.init_guess_by_minao(cell)
  File "/home/zhcui/program/pyscf_ZHC_kpt_symm/pyscf/scf/hf.py", line 1532, in init_guess_by_minao
    return init_guess_by_minao(mol)
  File "/home/zhcui/program/pyscf_ZHC_kpt_symm/pyscf/scf/hf.py", line 436, in init_guess_by_minao
    occ_add, basis_add = minao_basis(symb, nelec_ecp)
  File "/home/zhcui/program/pyscf_ZHC_kpt_symm/pyscf/scf/hf.py", line 400, in minao_basis
    occ_l[ndocc] = frac
IndexError: index 1 is out of bounds for axis 0 with size 1
```

Could take a look? Thanks!

Best,
Zhihao

**Comment by fishjojo** [comment]
I don't think the logics of MINAO initial guess for ECP basis works for GTH basis. A simple fix would be skipping the ECP part, i.e., by adding
```
if mol.pseudo:
            return occ, basis_ano
```
at https://github.com/pyscf/pyscf/blob/2bd16d760ddcbbcec4ca5d7b7b480b953743459b/pyscf/scf/hf.py#L372

**Comment by zhcui** [comment]
I am confused. Isn't the MINAO the default guess? I think it is always used.

**Comment by zhcui** [comment]
Ok, after discussing with Xing, it is due to the minimal basis does not have enough basis for small core PP.
