### ISSUE TITLE
Example in dft not working or outdated

### ISSUE THREAD

**Issue by maizorin97** [pyscf/pyscf#1466]
When runing example 
https://github.com/pyscf/pyscf/blob/7b91b3ce5a00947654c9057bdf1a22499278b2bf/examples/dft/24-define_xc_functional.py 
i got the following stacktrace:
```
Traceback (most recent call last):
  File "example.py", line 51, in <module>
    mf.kernel()
  File "<string>", line 2, in kernel
  File "/opt/conda/lib/python3.8/site-packages/pyscf/scf/hf.py", line 1692, in scf
    kernel(self, self.conv_tol, self.conv_tol_grad,
  File "/opt/conda/lib/python3.8/site-packages/pyscf/scf/hf.py", line 128, in kernel
    vhf = mf.get_veff(mol, dm)
  File "/opt/conda/lib/python3.8/site-packages/pyscf/dft/rks.py", line 80, in get_veff
    n, exc, vxc = ni.nr_rks(mol, ks.grids, ks.xc, dm, max_memory=max_memory)
  File "/opt/conda/lib/python3.8/site-packages/pyscf/dft/numint.py", line 1168, in nr_rks
    for i, ao, mask, wv in block_loop(ao_deriv):
  File "/opt/conda/lib/python3.8/site-packages/pyscf/dft/numint.py", line 1148, in block_loop
    exc, vxc = ni.eval_xc_eff(xc_code, rho, deriv=1, xctype=xctype)[:2]
  File "/opt/conda/lib/python3.8/site-packages/pyscf/dft/numint.py", line 2751, in eval_xc_eff
    exc, vxc, fxc, kxc = self.eval_xc(xc_code, rhop, spin, 0, deriv, omega, verbose)
TypeError: eval_xc() takes from 2 to 6 positional arguments but 7 were given
```
When running following lines, i debugged the problem and it is in `mf.kernel()`
https://github.com/pyscf/pyscf/blob/7b91b3ce5a00947654c9057bdf1a22499278b2bf/examples/dft/24-define_xc_functional.py#L49-L52

Woking with pyscf 2.1.1 in python 3.8

**Comment by maizorin97** [comment]
this is the output in jupyer notebook, i think is easier to see
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In [1], line 50
     48 mf = mf.define_xc_(eval_xc, 'GGA', hyb=hybrid_coeff)
     49 mf.verbose = 4
---> 50 mf.kernel()
     52 # half exact exchange in which 40% of the exchange is computed with short
     53 # range part of the range-separation Coulomb operator (omega = 0.8)
     54 beta = 0.2

File <string>:2, in kernel(self, dm0, **kwargs)

File /opt/conda/lib/python3.8/site-packages/pyscf/scf/hf.py:1692, in SCF.scf(self, dm0, **kwargs)
   1687 self.build(self.mol)
   1689 if self.max_cycle > 0 or self.mo_coeff is None:
   1690     self.converged, self.e_tot, \
   1691             self.mo_energy, self.mo_coeff, self.mo_occ = \
-> 1692             kernel(self, self.conv_tol, self.conv_tol_grad,
   1693                    dm0=dm0, callback=self.callback,
   1694                    conv_check=self.conv_check, **kwargs)
   1695 else:
   1696     # Avoid to update SCF orbitals in the non-SCF initialization
   1697     # (issue #495).  But run regular SCF for initial guess if SCF was
   1698     # not initialized.
   1699     self.e_tot = kernel(self, self.conv_tol, self.conv_tol_grad,
...
   2753                                   verbose)
   2754 if deriv > 2:
   2755     kxc = xc_deriv.transform_kxc(rhop, fxc, kxc, xctype, spin)

TypeError: eval_xc() takes from 2 to 6 positional arguments but 7 were given
```
