### ISSUE TITLE
libomp.dylib not found, macOS arm

### ISSUE THREAD

**Issue by jagunther** [pyscf/pyscf#1469]
Dear all, I am trying to get PySCF running on my MacBook (ARM).

I had trouble installing it with pip, so I compiled it from source, as described [here](https://pyscf.org/install.html#compiling-from-source-code).

The compilation worked fine, however, importing pyscf in python gives me an error, saying that libomp.dylib was not found. Libomp was installed with homebrew.
I am not familiar with installing software like this (usually I just pip/conda install), so it would be great if someone could give me some advice.

```>>> import pyscf
Traceback (most recent call last):
  File "/Users/vrn738/opt/anaconda3/lib/python3.9/site-packages/pyscf/lib/misc.py", line 55, in load_library
    return numpy.ctypeslib.load_library(libname, _loaderpath)
  File "/Users/vrn738/opt/anaconda3/lib/python3.9/site-packages/numpy/ctypeslib.py", line 149, in load_library
    return ctypes.cdll[libpath]
  File "/Users/vrn738/opt/anaconda3/lib/python3.9/ctypes/__init__.py", line 457, in __getitem__
    return getattr(self, name)
  File "/Users/vrn738/opt/anaconda3/lib/python3.9/ctypes/__init__.py", line 452, in __getattr__
    dll = self._dlltype(name)
  File "/Users/vrn738/opt/anaconda3/lib/python3.9/ctypes/__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/vrn738/opt/anaconda3/lib/python3.9/site-packages/pyscf/lib/libnp_helper.dylib, 0x0006): Library not loaded: '/usr/local/opt/libomp/lib/libomp.dylib'
  Referenced from: '/Users/vrn738/opt/anaconda3/lib/python3.9/site-packages/pyscf/lib/libnp_helper.dylib'
  Reason: tried: '/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/usr/local/lib/libomp.dylib' (no such file), '/usr/lib/libomp.dylib' (no such file)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/vrn738/opt/anaconda3/lib/python3.9/site-packages/pyscf/__init__.py", line 113, in <module>
    from pyscf import lib
  File "/Users/vrn738/opt/anaconda3/lib/python3.9/site-packages/pyscf/lib/__init__.py", line 24, in <module>
    from pyscf.lib import numpy_helper
  File "/Users/vrn738/opt/anaconda3/lib/python3.9/site-packages/pyscf/lib/numpy_helper.py", line 39, in <module>
    _np_helper = misc.load_library('libnp_helper')
  File "/Users/vrn738/opt/anaconda3/lib/python3.9/site-packages/pyscf/lib/misc.py", line 63, in load_library
    return numpy.ctypeslib.load_library(libname, libpath)
  File "/Users/vrn738/opt/anaconda3/lib/python3.9/site-packages/numpy/ctypeslib.py", line 149, in load_library
    return ctypes.cdll[libpath]
  File "/Users/vrn738/opt/anaconda3/lib/python3.9/ctypes/__init__.py", line 457, in __getitem__
    return getattr(self, name)
  File "/Users/vrn738/opt/anaconda3/lib/python3.9/ctypes/__init__.py", line 452, in __getattr__
    dll = self._dlltype(name)
  File "/Users/vrn738/opt/anaconda3/lib/python3.9/ctypes/__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/vrn738/opt/anaconda3/lib/python3.9/site-packages/pyscf/lib/libnp_helper.dylib, 0x0006): Library not loaded: '/usr/local/opt/libomp/lib/libomp.dylib'
  Referenced from: '/Users/vrn738/opt/anaconda3/lib/python3.9/site-packages/pyscf/lib/libnp_helper.dylib'
  Reason: tried: '/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/usr/local/lib/libomp.dylib' (no such file), '/usr/lib/libomp.dylib' (no such file)'''

**Comment by pwkj** [comment]
I did `brew install libomp` but still it doesn't work.

**Comment by jagunther** [comment]
I could resolve the issue with help of #1511. I had to install Command Line Developer Tools with `xcode-select --install` as well
