### ISSUE TITLE
Error arises when running CCSD(T) with DFT orbitals

### ISSUE THREAD

**Issue by anbonimus** [pyscf/pyscf#1566]
Hi, I am running PES calculation for LiF using CCSD with DFT orbitals. Roughly the first 50  points the code ran without any problem, but as the bound length gets larger, I got this error msg saying CCSD gives a one dimensional matrix and it cannot compute the eigenvalue of that:

WARN:  diis singular, eigh(h) [-5.38193872e-01 -3.27841835e-14  4.45787149e-13  5.76601749e+00
  5.11657754e+02  1.05175618e+03  3.58015611e+04]

Traceback (most recent call last):
  File "/gpfs/home/ruishi/research/h3+.py", line 29, in <module>
    mycc = cc.CCSD(temp).run()
  File "/gpfs/home/ruishi/anaconda3/envs/Qiskit/lib/python3.9/site-packages/pyscf/lib/misc.py", line 534, in run
    self.kernel(*args)
  File "/gpfs/home/ruishi/anaconda3/envs/Qiskit/lib/python3.9/site-packages/pyscf/cc/ccsd.py", line 1076, in kernel
    return self.ccsd(t1, t2, eris)
  File "/gpfs/home/ruishi/anaconda3/envs/Qiskit/lib/python3.9/site-packages/pyscf/cc/ccsd.py", line 1091, in ccsd
    kernel(self, eris, t1, t2, max_cycle=self.max_cycle,
  File "/gpfs/home/ruishi/anaconda3/envs/Qiskit/lib/python3.9/site-packages/pyscf/cc/ccsd.py", line 83, in kernel
    t1, t2 = mycc.run_diis(t1, t2, istep, normt, eccsd-eold, adiis)
  File "/gpfs/home/ruishi/anaconda3/envs/Qiskit/lib/python3.9/site-packages/pyscf/cc/ccsd.py", line 1243, in run_diis
    t1, t2 = self.vector_to_amplitudes(adiis.update(vec))
  File "/gpfs/home/ruishi/anaconda3/envs/Qiskit/lib/python3.9/site-packages/pyscf/lib/diis.py", line 237, in update
    self._xprev = xnew = self.extrapolate(nd)
  File "/gpfs/home/ruishi/anaconda3/envs/Qiskit/lib/python3.9/site-packages/pyscf/lib/diis.py", line 264, in extrapolate
    raise e
  File "/gpfs/home/ruishi/anaconda3/envs/Qiskit/lib/python3.9/site-packages/pyscf/lib/diis.py", line 261, in extrapolate
    c = numpy.linalg.solve(h, g)
  File "<__array_function__ internals>", line 200, in solve
  File "/gpfs/home/ruishi/anaconda3/envs/Qiskit/lib/python3.9/site-packages/numpy/linalg/linalg.py", line 386, in solve
    r = gufunc(a, b, signature=signature, extobj=extobj)
  File "/gpfs/home/ruishi/anaconda3/envs/Qiskit/lib/python3.9/site-packages/numpy/linalg/linalg.py", line 89, in _raise_linalgerror_singular
    raise LinAlgError("Singular matrix")
numpy.linalg.LinAlgError: Singular matrix

Here is my code:

Eslist = {}
for i in range(100):
    l = 1.4 + i/20
    mol = gto.Mole(
        atom = 'f;li 1 '+str(l),  # in Angstrom
        basis = 'ccpvqz',
        symmetry = True,
    )
    mol.build(parse_arg=False)
    
    mf=dft.RKS(mol)
    mf.xc = 'B3LYP'
    mf.kernel()
    temp = mf.to_hf()

    mycc = cc.CCSD(temp).run()
    
    ehf = mycc.e_tot + mycc.ccsd_t()
    Eslist[l] = ehf

The attached is the output file.
[test.txt](https://github.com/pyscf/pyscf/files/10369213/test.txt)

**Comment by tberkel** [comment]
Both DFT/HF and CC calculations are notoriously difficult to converge for stretched bond lengths. A solution that usually helps is to re-use the density matrix from a previously converged calculation at a smaller bond length. See the example in `pyscf/examples/scf/16-h2_scan.py`.

**Comment by anbonimus** [comment]
But if you check the output file, there are a few calculations at large
distance that didn't converge but still ran through without any bug. So I
don't think this has anything to do with this.

**Comment by tberkel** [comment]
The error message is a problem in the DIIS algorithm used to accelerate convergence of the CC iterations, and the problem is caused by the challenge of converging the CC iterations at large bond length. You problem probably requires reusing both the density matrix and the t1/t2 amplitudes. The below script successfully converges the HF and CC energies throughout the range you are interested in (I changed the bond increment and basis set just to speed up testing).

```
import pyscf
from pyscf import gto, dft, cc

print(pyscf.__version__)

energies = list()
dm = None
t1 = None
t2 = None
for i in range(50):
    b = 1.4 + i/10
    mol = gto.Mole(
        atom = f'f;li 1 {b}',  # in Angstrom
        basis = 'ccpvdz', # smaller than ccpv5z for testing
        symmetry = True, # or False
        verbose = 0,
    )
    mol.build(parse_arg=False)
    mf = dft.RKS(mol)
    mf.xc = 'b3lyp'
    emf = mf.kernel(dm)
    dm = mf.make_rdm1()
    temp = mf.to_hf()

    mycc = cc.CCSD(temp)
    ecc, t1, t2 = mycc.kernel(t1=t1, t2=t2)

    print(f'{b} {emf} {int(mf.converged)} {mycc.e_tot} {int(mycc.converged)}')
```

**Comment by anbonimus** [comment]
I see. Thank you so much for the help!

Yours
Ruiren
