### ISSUE TITLE
Error with DMRG-NEVPT2 since pyscf 2.0?

### ISSUE THREAD

**Issue by HehnLukas** [pyscf/pyscf#1575]
i have been getting this error (bottom of post) when trying to use DMRG-NEVPT2 with block version 1.5 with this line of code:

`E_NEVPT2 = mrpt.NEVPT(mc, root=0).compress_approx(maxM=maxm).kernel()`

The pyscf version is 2.0.1. The exact same code works with pyscf 1.7.5 though.
I find the block error messages very hard to figure out, has anyone else experieced this? Or did I make some mistake?

```
Traceback (most recent call last):
  File "/gpfs/backup/software/app/pyscf.org/pyscf/2.0.1/rt_gcc_openmpi/7.2.0-3.0.0/intelpython3.6-2019.1/lib/python3.6/site-packages/pyscf/dmrgscf/nevpt_mpi.py", line 506, in <module>
    nevpt_integral_mpi(sys.argv[1],sys.argv[2],sys.argv[3],sys.argv[4])
  File "/gpfs/backup/software/app/pyscf.org/pyscf/2.0.1/rt_gcc_openmpi/7.2.0-3.0.0/intelpython3.6-2019.1/lib/python3.6/site-packages/pyscf/dmrgscf/nevpt_mpi.py", line 286, in nevpt_integral_mpi
    f.write(nevpt_conf)
TypeError: write() argument must be str, not bytes

ERROR:  /gpfs/backup/software/app/pyscf.org/pyscf/2.0.1/rt_gcc_openmpi/7.2.0-3.0.0/intelpython3.6-2019.1/lib/python3.6/site-packages/pyscf/dmrgscf/nevpt_mpi.py /scratch/pbs.13779367.pbsp1/7669/nevpt_perturb_integral /software/app/pyscf.org/pyscf/2.0.1/rt_gcc_openmpi/7.2.0-3.0.0/intelpython3.6-2019.1/bin/block.spin_adapted.lnk /scratch/pbs.13779367.pbsp1/7669 /scratch/pbs.13779367.pbsp1/7669

ERROR:  /gpfs/backup/software/app/pyscf.org/pyscf/2.0.1/rt_gcc_openmpi/7.2.0-3.0.0/intelpython3.6-2019.1/lib/python3.6/site-packages/pyscf/dmrgscf/nevpt_mpi.py /scratch/pbs.13779367.pbsp1/7669/nevpt_perturb_integral /software/app/pyscf.org/pyscf/2.0.1/rt_gcc_openmpi/7.2.0-3.0.0/intelpython3.6-2019.1/bin/block.spin_adapted.lnk /scratch/pbs.13779367.pbsp1/7669 /scratch/pbs.13779367.pbsp1/7669
Traceback (most recent call last):
  File "/gpfs/backup/users/home/hehnl/maniqu_nobackup/pyscf/mrsub_test/quick_test_o2/copy/mrsub_run.py", line 15, in <module>
    mrsub(path, gaussian)
  File "/gpfs/nobackup/projects/quantumchemistry/maniqu/scripts/mrsub/mrsub.py", line 679, in mrsub
    E_NEVPT2 = mrpt.NEVPT(mc, root=0).compress_approx(maxM=maxm).kernel()
  File "/software/app/pyscf.org/pyscf/2.0.1/rt_gcc_openmpi/7.2.0-3.0.0/intelpython3.6-2019.1/lib/python3.6/site-packages/pyscf/mrpt/nevpt2.py", line 783, in kernel
    tol=self.tol)
  File "/software/app/pyscf.org/pyscf/2.0.1/rt_gcc_openmpi/7.2.0-3.0.0/intelpython3.6-2019.1/lib/python3.6/site-packages/pyscf/dmrgscf/nevpt_mpi.py", line 250, in DMRG_COMPRESS_NEVPT
    raise err
  File "/software/app/pyscf.org/pyscf/2.0.1/rt_gcc_openmpi/7.2.0-3.0.0/intelpython3.6-2019.1/lib/python3.6/site-packages/pyscf/dmrgscf/nevpt_mpi.py", line 247, in DMRG_COMPRESS_NEVPT
    subprocess.check_call(cmd, shell=True)
  File "/software/app/intel/parallel_studio_xe/2019.1/intelpython3/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command ' /gpfs/backup/software/app/pyscf.org/pyscf/2.0.1/rt_gcc_openmpi/7.2.0-3.0.0/intelpython3.6-2019.1/lib/python3.6/site-packages/pyscf/dmrgscf/nevpt_mpi.py /scratch/pbs.13779367.pbsp1/7669/nevpt_perturb_integral /software/app/pyscf.org/pyscf/2.0.1/rt_gcc_openmpi/7.2.0-3.0.0/intelpython3.6-2019.1/bin/block.spin_adapted.lnk /scratch/pbs.13779367.pbsp1/7669 /scratch/pbs.13779367.pbsp1/7669' returned non-zero exit status 1.
```

**Comment by HehnLukas** [comment]
So I believe the problem here was caused by an outdated dmrgscf extension in the pyscf 2.0.1 install, where line 286 didn't have this try except block:
```
        try:
            f.write(nevpt_conf)
        except TypeError:
            f.write(str(nevpt_conf,"utf-8"))
```
adding this seems to have fixed the issue.

Also, from issue 1601 I learned that I actually have stackblock 1.5.3 installed, and not block, I think. That is why compress_approx works now, but dmrg nevpt2 without it does not work
