### ISSUE TITLE
Error in davidson of ext. stab. analysis

### ISSUE THREAD

**Issue by HehnLukas** [pyscf/pyscf#1589]
The external stability check fails occasionally. In my case, mainly when using the PBE functional, throwing the following error:

```
Traceback (most recent call last):
  File "/gpfs/nobackup/projects/quantumchemistry/maniqu/scripts/mrsub/mrsub.py", line 620, in mrsub
    _,_, = mf.stability(internal = False, external = True)
  File "/software/app/pyscf.org/pyscf/2.0.1/rt_gcc_openmpi/7.2.0-3.0.0/intelpython3.6-2019.1/lib/python3.6/site-packages/pyscf/scf/hf.py", line 2006, in stability
    return rhf_stability(self, internal, external, verbose)
  File "/software/app/pyscf.org/pyscf/2.0.1/rt_gcc_openmpi/7.2.0-3.0.0/intelpython3.6-2019.1/lib/python3.6/site-packages/pyscf/scf/stability.py", line 60, in rhf_stability
    mo_e = rhf_external(mf, verbose=verbose)
  File "/software/app/pyscf.org/pyscf/2.0.1/rt_gcc_openmpi/7.2.0-3.0.0/intelpython3.6-2019.1/lib/python3.6/site-packages/pyscf/scf/stability.py", line 263, in rhf_external
    e3, v3 = lib.davidson(hop2, x0, precond, tol=1e-4, verbose=log)
  File "/software/app/pyscf.org/pyscf/2.0.1/rt_gcc_openmpi/7.2.0-3.0.0/intelpython3.6-2019.1/lib/python3.6/site-packages/pyscf/lib/linalg_helper.py", line 286, in davidson
    follow_state)[1:]
  File "/software/app/pyscf.org/pyscf/2.0.1/rt_gcc_openmpi/7.2.0-3.0.0/intelpython3.6-2019.1/lib/python3.6/site-packages/pyscf/lib/linalg_helper.py", line 447, in davidson1
    dtype = numpy.result_type(ax[0].dtype, xs[0].dtype)
IndexError: list index out of range
```

It prints this warning before this error:
`WARN: QR decomposition removed 1 vectors.  The davidson may fail.`

To reproduce: 
```
from pyscf import gto, scf, dft
mol = gto.Mole()
mol.atom='''
O    -3.6803126  -14.2580571    5.8361046
O    -4.3300167  -13.2732483    6.3285196
O    -4.0432508  -12.1161346    5.8666858
'''
mol.basis = 'cc-pVTZ'
mol.unit = 'A'
mol.verbose = 4
mol.spin = 0
mol.charge = 0
mol.build()

mf = dft.RKS(mol)
mf.max_cycle = 999
mf.xc = 'pbe'
mf.kernel()
mf.stability(external=True)

```

This happens with PBE, it works fine with SVWN (ext. stable) and with B3Lyp (ext. instable)

**Comment by hebrewsnabla** [comment]
Here, the davidson for RHF external instability takes the eigenvector of real2complex instability
https://github.com/pyscf/pyscf/blob/0df2ead0cc9b80a1b8bf0f26b5d1755baf1a472f/pyscf/scf/stability.py#L387-L390

But in this case, real2complex instability eigenvalue is very close to 0 so sometimes the eigenvector is pathetic, and kicked out by this `if`.
https://github.com/pyscf/pyscf/blob/0df2ead0cc9b80a1b8bf0f26b5d1755baf1a472f/pyscf/lib/linalg_helper.py#L1528-L1532

A quick fix is to build the x0 from hdiag, as the x0 of real2complex one.

**Comment by sunqm** [comment]
> Here, the davidson for RHF external instability takes the eigenvector of real2complex instability as x0
> 
> https://github.com/pyscf/pyscf/blob/0df2ead0cc9b80a1b8bf0f26b5d1755baf1a472f/pyscf/scf/stability.py#L387-L390
> 
> But in this case, real2complex instability eigenvalue is very close to 0 so sometimes the eigenvector has a too small norm, and get kicked out by this `if`.
> 
> https://github.com/pyscf/pyscf/blob/0df2ead0cc9b80a1b8bf0f26b5d1755baf1a472f/pyscf/lib/linalg_helper.py#L1528-L1532
> 
> A quick fix is to build the x0 from hdiag, as the x0 of real2complex one.

Thanks for the suggestion. It is used in PR #1633
