### ISSUE TITLE
"GGA_X_HERMAN" functional (104) does not work

### ISSUE THREAD

**Issue by MatthewRHermes** [pyscf/pyscf#1692]
The following:
```
from pyscf import gto, dft
ks = dft.RKS (gto.M (atom='He 0 0 0'), xc='GGA_X_HERMAN').run ()
```
results in the following:
```
XC functional 104 not found
XC functional 104 not found
Traceback (most recent call last):
  File "he.py", line 2, in <module>
    ks = dft.RKS (gto.M (atom='He 0 0 0'), xc='GGA_X_HERMAN').run ()
  File "/home/herme068/anaconda3/envs/pyscf/lib/python3.7/site-packages/pyscf/lib/misc.py", line 591, in run
    self.kernel(*args)
  File "<string>", line 2, in kernel
  File "/home/herme068/anaconda3/envs/pyscf/lib/python3.7/site-packages/pyscf/scf/hf.py", line 1699, in scf
    conv_check=self.conv_check, **kwargs)
  File "/home/herme068/anaconda3/envs/pyscf/lib/python3.7/site-packages/pyscf/scf/hf.py", line 128, in kernel
    vhf = mf.get_veff(mol, dm)
  File "/home/herme068/anaconda3/envs/pyscf/lib/python3.7/site-packages/pyscf/dft/rks.py", line 80, in get_veff
    n, exc, vxc = ni.nr_rks(mol, ks.grids, ks.xc, dm, max_memory=max_memory)
  File "/home/herme068/anaconda3/envs/pyscf/lib/python3.7/site-packages/pyscf/dft/numint.py", line 1164, in nr_rks
    for i, ao, mask, wv in block_loop(ao_deriv):
  File "/home/herme068/anaconda3/envs/pyscf/lib/python3.7/site-packages/pyscf/dft/numint.py", line 1150, in block_loop
    exc, vxc = ni.eval_xc_eff(xc_code, rho, deriv=1, xctype=xctype)[:2]
  File "/home/herme068/anaconda3/envs/pyscf/lib/python3.7/site-packages/pyscf/dft/numint.py", line 2762, in eval_xc_eff
    verbose)
  File "/home/herme068/anaconda3/envs/pyscf/lib/python3.7/site-packages/pyscf/dft/numint.py", line 2704, in eval_xc
    omega, verbose)
  File "/home/herme068/anaconda3/envs/pyscf/lib/python3.7/site-packages/pyscf/dft/libxc.py", line 1405, in eval_xc
    return _eval_xc(hyb, fn_facs, rho, spin, relativity, deriv, verbose)
  File "/home/herme068/anaconda3/envs/pyscf/lib/python3.7/site-packages/pyscf/dft/libxc.py", line 1441, in _eval_xc
    raise NotImplementedError('laplacian in meta-GGA method')
NotImplementedError: laplacian in meta-GGA method
```
Which I believe is due to every boolean query function (`needs_laplacian`,`is_meta_gga`,etc.) in _itrf returning the error code -1, which is not properly handled in libxc.py:
```
from pyscf.dft.libxc import _itrf, parse_xc, needs_laplacian
print (needs_laplacian (104))
print (_itrf.LIBXC_needs_laplacian(104))
```
results in
```
XC functional 104 not found
True
XC functional 104 not found
-1
```
 I suspect the _itrf error code is ultimately due to GGA_X_HERMAN being [removed](https://gitlab.com/libxc/libxc/-/merge_requests/601) from libxc recently.

**Comment by susilehtola** [comment]
Yes, that functional should never even have been in Libxc since it is not at all what was described by Herman and coworkers. This is a problem caused by #48

**Comment by MatthewRHermes** [comment]
I could make a PR partially addressing this which just checks for -1 returns in libxc.py and raises a more informative and correct exception, but it looks like there is some plan already to modify the behavior of libxc_itrf.c:
```
// TODO: register python signal
#define raise_error     return
```
which probably involves some technology that I don't know about.
