### ISSUE TITLE
Error when doing CASSCF using MWB53 ECP basis set for Eu

### ISSUE THREAD

**Issue by szppp** [pyscf/pyscf#1722]
Hi all:

My PySCF version is 2.2.1. When I calculate gradient with CASSCF program and use MWB53 ECP basis set for Eu, the program stops with error as follows after completing CASSCF calculation.

```
1-step CASSCF converged in  11 macro (213 JK  39 micro) steps
CASSCF canonicalization
where_natorb [0, 1, 3, 2, 4, 5, 6, 8, 7, 9, 10, 11]
Natural occ [1.91880306 1.90609649 1.90154207 1.90090374 1.88897855 1.18920935
 0.81040982 0.15034582 0.12261257 0.07166861 0.07046605 0.06896386]
Natural orbital (expansion on meta-Lowdin AOs) in CAS space
Traceback (most recent call last):
  File "/szp/work/eu+2/eucl/casscf/tmp/mokit_uno2CASSCF.py", line 530, in <module>
    mc.kernel()
  File "/szp/soft/pyscf_221/pyscf/mcscf/mc1step.py", line 842, in kernel
    _kern(self, mo_coeff,
  File "/szp/soft/pyscf_221/pyscf/mcscf/mc1step.py", line 486, in kernel
    casscf.canonicalize(mo, fcivec, eris, casscf.sorting_mo_energy,
  File "/szp/soft/pyscf_221/pyscf/mcscf/casci.py", line 493, in canonicalize
    mo_coeff1, ci, mc.mo_occ = mc.cas_natorb(mo_coeff, ci, eris, sort, casdm1,
  File "/szp/soft/pyscf_221/pyscf/mcscf/casci.py", line 1023, in cas_natorb
    return cas_natorb(self, mo_coeff, ci, eris, sort, casdm1, verbose,
  File "/szp/soft/pyscf_221/pyscf/mcscf/casci.py", line 392, in cas_natorb
    label = mc.mol.ao_labels()
  File "/szp/soft/pyscf_221/pyscf/gto/mole.py", line 1604, in ao_labels
    return mol.sph_labels(fmt, base)
  File "/szp/soft/pyscf_221/pyscf/gto/mole.py", line 1523, in sph_labels
    coreshl = core_configuration(nelec_ecp, atom_symbol=symb)
  File "/szp/soft/pyscf_221/pyscf/gto/ecp.py", line 154, in core_configuration
    raise RuntimeError('Core configuration for %d core electrons is not available.' % nelec_core)
RuntimeError: Core configuration for 53 core electrons is not available.

Orthonormality check: j= 123 i= 120 maxv= 2.83802725E-05

```

And my input file is as follows:

```
from pyscf import gto, scf
from mokit.lib.fch2py import fch2py
from mokit.lib.ortho import check_orthonormal
from pyscf import mcscf, lib
from mokit.lib.py2fch import py2fch
from shutil import copyfile
import numpy as np

lib.num_threads(56)

mol = gto.M()
<geometry and custom basis sets including ecp>

# Remember to check the charge and spin
mol.charge = 2
mol.spin = 0
mol.verbose = 4
mol.build()

mf = scf.RHF(mol)
mf.max_cycle = 1
mf.init_guess = '1e'
mf.max_memory = 230000 # MB
mf.kernel()

# read MOs from .fch(k) file
nbf = mf.mo_coeff.shape[0]
nif = mf.mo_coeff.shape[1]
mf.mo_coeff = fch2py('mokit_uno.fch', nbf, nif, 'a')
# read done

# check if input MOs are orthonormal
S = mol.intor_symmetric('int1e_ovlp')
check_orthonormal(nbf, nif, mf.mo_coeff, S)

#dm = mf.make_rdm1()
#mf.max_cycle = 10
#mf.kernel(dm)

mc = mcscf.CASSCF(mf,12,(6,6))
mc.fcisolver.max_memory = 46000 # MB
mc.fcisolver.spin = 0
mc.fcisolver.max_cycle = 200
mc.max_memory = 184000 # MB
mc.max_cycle = 200
mc.natorb = True
mc.verbose = 5
mc.kernel()

# save NOs into .fch file
copyfile('mokit_uno.fch','mokit_uno2CASSCF_NO.fch')
py2fch('mokit_uno2CASSCF_NO.fch',nbf,nif,mc.mo_coeff,'a',mc.mo_occ,True)
from pyscf import grad
mcg = mc.Gradients()
mcg.max_memory = 230000 # MB
mcg.kernel()
```

It says "Core configuration for 53 core electrons is not available.", but when I see the .../pyscf/gto/ecp.py file, 53 core electrons is allowed for lanthanides. In fact, if I don't use "mf.init_guess = '1e'" in the input file (the MOs in the .fch file is converged so that HF in PySCF can be skipped), the same error would occur at the beginning of the run. So why does this error occur? Is it practical to allow MWB53 for Eu and all large nuclear pseudopotentials in calculation? Thanks a lot!

**Comment by bogdanoff** [comment]
Hello, could you please verify that the changes in #1723 fix the problem?

**Comment by hebrewsnabla** [comment]
Looks like the error came from `sph_labels()` but that's unchanged in #1723, and it looks fine before #1723 (it did pass the symbol). So it remains a question why there's such error.

**Comment by bogdanoff** [comment]
Indeed, a full input with geometry and basis specification would be helpful to debug the issue.

**Comment by szppp** [comment]
The geometry and basis specification are just like what shows below. Because the input file is generated by MOKIT through a .fch file, basis sets are in custom form.

```
mol = gto.M()
# 18 atom(s)
mol.atom = '''
Eu1        
'''

mol.basis = {
'Eu1': gto.basis.parse('''
Eu    S
    0.749719700E+01   -0.288775043E+00
    0.617255600E+01    0.708008105E+00
    0.260816600E+01   -0.136569920E+01
Eu    S
    0.530389000E+00    0.100000000E+01
Eu    S
    0.254033000E+00    0.100000000E+01
Eu    S
    0.522020000E-01    0.100000000E+01
Eu    S
    0.221100000E-01    0.100000000E+01
Eu    P
    0.399434200E+01    0.110821693E+01
    0.350361700E+01   -0.152518191E+01
    0.722399000E+00    0.119866293E+01
Eu    P
    0.324354000E+00    0.100000000E+01
Eu    P
    0.127842000E+00    0.100000000E+01
Eu    P
    0.330280000E-01    0.100000000E+01
Eu    D
    0.206170800E+01   -0.127297005E+00
    0.967971000E+00    0.377785014E+00
    0.369101000E+00    0.765795028E+00
Eu    D
    0.128958000E+00    0.100000000E+01
Eu    D
    0.419270000E-01    0.100000000E+01
'''),
......
mol.ecp = {
'Eu1': gto.basis.parse_ecp('''
Eu nelec  53
Eu ul
2      1.0000000000        0.0000000000
Eu S
2      5.1852000000      172.7978960000
2      2.5926000000      -10.0922600000
Eu P
2      4.3588000000      111.3150270000
2      2.1794000000       -3.4025580000
Eu D
2      2.8902000000       41.8677290000
2      1.4451000000       -1.2874330000
Eu F
2      5.3988000000      -63.6010500000
'''),
......
```

**Comment by szppp** [comment]
So should I modify related codes in the source code of 2.2.1 release and then make it?

**Comment by bogdanoff** [comment]
There is no need to recompile, as only the python files are changed. You can just modify the files according to #1723.
If you installed pyscf from source using git you can also do the following:
```
git remote add bogdanoff https://github.com/bogdanoff/pyscf.git
git fetch bogdanoff
git checkout f-in-core-ECPs_more
```
to come back to the release just do `git checkout master`.

**Comment by szppp** [comment]
It works! Very thanks for your patient replies and help!
