### ISSUE TITLE
Numpy memory error in PBE with spin-free X2C1e

### ISSUE THREAD

**Issue by gauravharsha** [pyscf/pyscf#1767]
I am running a periodic all electron DFT calculation (details below) with spin-free X2C1e. Unexpectedly, I notice that the `mf.get_hcore()` function throws a memory error because NumPy cannot allocate space for a matrix.

I do not encounter this error in older versions of PySCF, particularly in this [fork](https://github.com/cnyeh/pyscf) which was later merged into the main branch in pull request #1314.

Any suggestions to fix this would be of great help.

### Details about the calculation and relevant script
```python
# Density fitting
# k-mesh corresponds to 4x4x4 k-mesh
mydf = df.GDF(mycell)
mydf.auxbasis = df.aug_etb(mycell, beta=2.0)
mydf.kpts = kmesh
mydf.build()

# DFT
mf = dft.KUKS(mycell, mydf.kpts).density_fit().sfx2c1e()
mf.xc = 'pbe'
mf.with_df = mydf
mf.kernel()
```
| number of AOs in unit cell | 120 |
|-|-|
| number of auxiliary AOs for density fitting | 1009 |

### Error message
```bash
Traceback (most recent call last):
  File "/home/gharsha/script.py", line 275, in <module>
    mf.kernel()
  File "<string>", line 2, in kernel
  File "/home/gharsha/miniconda3/lib/python3.9/site-packages/pyscf-2.2.0-py3.9-linux-x86_64.egg/pyscf/scf/hf.py", line 1697, in scf
    kernel(self, self.conv_tol, self.conv_tol_grad,
  File "/home/gharsha/miniconda3/lib/python3.9/site-packages/pyscf-2.2.0-py3.9-linux-x86_64.egg/pyscf/scf/hf.py", line 127, in kernel
    h1e = mf.get_hcore(mol)
  File "/home/gharsha/miniconda3/lib/python3.9/site-packages/pyscf-2.2.0-py3.9-linux-x86_64.egg/pyscf/pbc/x2c/sfx2c1e.py", line 101, in get_hcore
    hcore = self.with_x2c.get_hcore(cell, kpts)
  File "/home/gharsha/miniconda3/lib/python3.9/site-packages/pyscf-2.2.0-py3.9-linux-x86_64.egg/pyscf/pbc/x2c/sfx2c1e.py", line 170, in get_hcore
    w = get_pnucp(with_df, kpts_lst)
  File "/home/gharsha/miniconda3/lib/python3.9/site-packages/pyscf-2.2.0-py3.9-linux-x86_64.egg/pyscf/pbc/x2c/sfx2c1e.py", line 258, in get_pnucp
    wj = mydf._int_nuc_vloc(nuccell, kpts_lst, 'int3c2e_pvp1')
  File "/home/gharsha/miniconda3/lib/python3.9/site-packages/pyscf-2.2.0-py3.9-linux-x86_64.egg/pyscf/pbc/df/aft.py", line 218, in _int_nuc_vloc
    return dfbuilder._int_nuc_vloc(nuccell, intor, aosym)
  File "/home/gharsha/miniconda3/lib/python3.9/site-packages/pyscf-2.2.0-py3.9-linux-x86_64.egg/pyscf/pbc/df/incore.py", line 465, in _int_nuc_vloc
    int3c = self.gen_int3c_kernel(intor, aosym, comp=comp, j_only=True,
  File "/home/gharsha/miniconda3/lib/python3.9/site-packages/pyscf-2.2.0-py3.9-linux-x86_64.egg/pyscf/pbc/df/incore.py", line 247, in gen_int3c_kernel
    ovlp_mask, cell0_ovlp_mask = self.get_ovlp_mask(supmol.precision, supmol, cintopt)
  File "/home/gharsha/miniconda3/lib/python3.9/site-packages/pyscf-2.2.0-py3.9-linux-x86_64.egg/pyscf/pbc/df/incore.py", line 445, in get_ovlp_mask
    _Int3cBuilder.get_ovlp_mask(self, cutoff, supmol, cintopt)
  File "/home/gharsha/miniconda3/lib/python3.9/site-packages/pyscf-2.2.0-py3.9-linux-x86_64.egg/pyscf/pbc/df/incore.py", line 389, in get_ovlp_mask
    ovlp_mask = np.empty((nbas, nbas), dtype=np.int8)
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 1.16 TiB for an array with shape (1130496, 1130496) and data type int8
```

**Comment by sunqm** [comment]
The x2c basis by default is decontracted orbital basis. It is generally not recommended to use the orbital basis in x. This may lead to  variational collapse.

Memory footprint for PBC integrals was optimized in pyscf-2.3. Does the latest version work in your system?

**Comment by verena-neufeld** [comment]
Hi @gauravharsha , thanks for raising this issue. Has it been resolved now? If yes, this issue can probably be closed.

**Comment by gauravharsha** [comment]
I believe this issue is resolved. At least, the discussion here helped me understand the x2c code better.
