### ISSUE TITLE
example-pbc: 40-customize_kpts_hamiltonian.py

### ISSUE THREAD

**Issue by buralin** [pyscf/pyscf#1819]
Hi all,
I tried to run 40-customize_kpts_hamiltonian.py, but got the error:

'''
Traceback (most recent call last):
  File "/home/jtolle/Software/pyscf_master/pyscf/examples/pbc/40-customize_kpts_hamiltonian.py", line 33, in <module>
    cell = pbc.gto.M(
  File "/home/jtolle/Software/pyscf_master/pyscf/pyscf/pbc/gto/cell.py", line 73, in M
    cell.build(**kwargs)
  File "/home/jtolle/Software/pyscf_master/pyscf/pyscf/pbc/gto/cell.py", line 1522, in build
    atom_boundary_max = scaled_atom_coords[:,:self.dimension].max(axis=0)
  File "/home/jtolle/anaconda3/lib/python3.9/site-packages/numpy/core/_methods.py", line 41, in _amax
    return umr_maximum(a, axis, None, out, keepdims, initial, where)
ValueError: zero-size array to reduction operation maximum which has no identity
'''
(using the current master)

Using this commit: 71391d862c3db83db28553bbb1518acee466662c it works.
Would be great if someone can help to resolve this issue.
Best regards,
Johannes

**Comment by verena-neufeld** [comment]
Seems like the DF refactoring merge broke this. https://github.com/pyscf/pyscf/commit/10ccd8222199626c2c0a02ad3979f8118fa02f96

**Comment by verena-neufeld** [comment]
@sunqm @fishjojo @hongzhouye  probably know this refactoring best

**Comment by verena-neufeld** [comment]
Is this fixed now and can be closed? Thanks for raising this issue Johannes and for fixing it Xing!
