### ISSUE TITLE
Erroneous assert in density functional code

### ISSUE THREAD

**Issue by susilehtola** [pyscf/pyscf#1842]
Trying to run the example of #1839, I obtain a crash in the current master branch. Reduced test case

```
import pyscf
from pyscf import gto, scf

mol = gto.M(atom='Ne')
mol.basis = 'aug-pc-1'
mol.build()
mf = scf.UKS(mol)
mf.xc = "spw92"
edft = mf.kernel()
```

Obtained result
```
$ python test.py 
/home/work/pyscf/pyscf/dft/libxc.py:772: UserWarning: Since PySCF-2.3, B3LYP (and B3P86) are changed to the VWN-RPA variant, corresponding to the original definition by Stephens et al. (issue 1480) and the same as the B3LYP functional in Gaussian. To restore the VWN5 definition, you can put the setting "B3LYP_WITH_VWN5 = True" in pyscf_conf.py
  warnings.warn('Since PySCF-2.3, B3LYP (and B3P86) are changed to the VWN-RPA variant, '
Traceback (most recent call last):
  File "/tmp/test.py", line 9, in <module>
    edft = mf.kernel()
           ^^^^^^^^^^^
  File "<string>", line 2, in kernel
  File "/home/work/pyscf/pyscf/scf/hf.py", line 1685, in scf
    kernel(self, self.conv_tol, self.conv_tol_grad,
  File "/home/work/pyscf/pyscf/scf/hf.py", line 128, in kernel
    vhf = mf.get_veff(mol, dm)
          ^^^^^^^^^^^^^^^^^^^^
  File "/home/work/pyscf/pyscf/dft/uks.py", line 51, in get_veff
    n, exc, vxc = ni.nr_uks(mol, ks.grids, ks.xc, dm, max_memory=max_memory)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/work/pyscf/pyscf/dft/numint.py", line 1278, in nr_uks
    for i, ao, mask, wv in block_loop(ao_deriv):
  File "/home/work/pyscf/pyscf/dft/numint.py", line 1260, in block_loop
    exc, vxc = ni.eval_xc_eff(xc_code, rho, deriv=1, xctype=xctype)[:2]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/work/pyscf/pyscf/dft/numint.py", line 2782, in eval_xc_eff
    exc, vxc, fxc, kxc = self.eval_xc(xc_code, rhop, spin, 0, deriv, omega,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/work/pyscf/pyscf/dft/numint.py", line 2724, in eval_xc
    return self.libxc.eval_xc(xc_code, rho, spin, relativity, deriv,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/work/pyscf/pyscf/dft/libxc.py", line 1412, in eval_xc
    return _eval_xc(hyb, fn_facs, rho, spin, relativity, deriv, verbose)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/work/pyscf/pyscf/dft/libxc.py", line 1452, in _eval_xc
    all((is_lda(x) for x in fn_ids))):
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/work/pyscf/pyscf/dft/libxc.py", line 1452, in <genexpr>
    all((is_lda(x) for x in fn_ids))):
         ^^^^^^^^^
  File "/home/work/pyscf/pyscf/dft/libxc.py", line 902, in is_lda
    return xc_type(xc_code) == 'LDA'
           ^^^^^^^^^^^^^^^^
  File "/home/work/pyscf/pyscf/dft/libxc.py", line 887, in xc_type
    assert isinstance(xc_code, int)
AssertionError
```

**Comment by susilehtola** [comment]
So, the reason for the crash is that the type that gets fed in is not `int` but `numpy.int32`. The generalization in #1843 fixes this problem.
