### ISSUE TITLE
Correct syntax when starting from a mf calc

### ISSUE THREAD

**Issue by pkozlows** [pyscf/pyscf#1966]
I have the following code, which looks fine:
```
import pyscf.pbc.tools.pyscf_ase as pyscf_ase
from pyscf.pbc import gto, scf
import pyscf.pbc.gw as pbcgw
import pyscf.pbc.dft as pbcdft
import numpy as np
import os
from ase.lattice import bulk
from ase.dft.kpoints import sc_special_points as special_points
from ase.dft.kpoints import bandpath


ase_cell = bulk('GaN', 'wurtzite', a=3.19, c=5.19)
cell = gto.Cell()
cell.atom = pyscf_ase.ase_atoms_to_pyscf(ase_cell)
cell.a = np.array(ase_cell.cell)
cell.exp_to_discard = 0.1

cell.basis = 'gth-szv'
cell.pseudo = 'gth-pade'
cell.verbose = 5
cell.build(None, None)

# define the special points here
points = special_points['hexagonal']
G = points['G']
K = points['K']
M = points['M']
A = points['A']
L = points['L']
H = points['H']

# Choose an appropriate path for the band structure calculation
path = bandpath([G, M, K, G, A, L, H, A], ase_cell.cell, npoints=50)
kpts = path.kpts
kpath, sp_points, labels = path.get_linear_kpoint_axis()

old_path = os.path.join(os.getcwd(), 'previous.chk')
kmf = pbcdft.KRKS(cell, cell.make_kpts([1, 1, 1]))
kmf.xc = 'PBE'
kmf.__dict__.update(scf.chkfile.load(old_path, 'scf'))
# starred AGW calculation based off of the mean field object that is given in the check fail
new_path = os.path.join(os.getcwd(), 'new.chk')
gw = pbcgw.KRGW(kmf)
gw.chkfile = new_path
gw.kernel()
```
but I am getting the message
```
Traceback (most recent call last):
  File "/central/home/pkozlows/ch121b/gan/dft/g0w0/pbe/szv/111/1/g0s1.py", line 43, in <module>
    gw = pbcgw.KRGW(kmf)
         ^^^^^^^^^^^^^^^
  File "/groups/wag/pkozlows/miniconda3/envs/pyscf/lib/python3.11/site-packages/pyscf/gw/gw_slow.py", line 332, in __init__
    self.imds = self.base_imds(td, eri=eri)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/groups/wag/pkozlows/miniconda3/envs/pyscf/lib/python3.11/site-packages/pyscf/pbc/gw/kgw_slow.py", line 38, in __init__
    gw_slow.AbstractIMDS.__init__(self, td, eri=eri)
  File "/groups/wag/pkozlows/miniconda3/envs/pyscf/lib/python3.11/site-packages/pyscf/gw/gw_slow.py", line 40, in __init__
    self.eri = td.eri
               ^^^^^^
AttributeError: 'KRKS' object has no attribute 'eri'. Did you mean: '_eri'?
```
I am not sure where the reference to eris is coming from.
I have been doing some searching, but if someone could point me to an example of how to do this, that would be much appreciated :)

**Comment by tberkel** [comment]
I created a PR #1967 that should make it easier for anyone to use the PBC GW. But while you wait for it to be merged, you can do
```
from pyscf.pbc.gw import krgw_ac
mygw = krgw_ac.KRGWAC(kmf)
mygw.kernel()
```

**Comment by pkozlows** [comment]
I am getting
```
Traceback (most recent call last):
  File "/central/home/pkozlows/ch121b/gan/dft/g0w0/pbe/szv/111/1/g0s1.py", line 43, in <module>
    mygw = krgw_ac.KRGWAC(kmf).density_fit()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'KRGWAC' object has no attribute 'density_fit'
```
when I run
```
import pyscf.pbc.tools.pyscf_ase as pyscf_ase
from pyscf.pbc import gto, scf
from pyscf.pbc.gw import krgw_ac
import pyscf.pbc.dft as pbcdft
import numpy as np
import os
from ase.lattice import bulk
from ase.dft.kpoints import sc_special_points as special_points
from ase.dft.kpoints import bandpath


ase_cell = bulk('GaN', 'wurtzite', a=3.19, c=5.19)
cell = gto.Cell()
cell.atom = pyscf_ase.ase_atoms_to_pyscf(ase_cell)
cell.a = np.array(ase_cell.cell)
cell.exp_to_discard = 0.1

cell.basis = 'gth-szv'
cell.pseudo = 'gth-pade'
cell.verbose = 5
cell.build(None,None)

# define the special points here
points = special_points['hexagonal']
G = points['G']
K = points['K']
M = points['M']
A = points['A']
L = points['L']
H = points['H']

# Choose an appropriate path for the band structure calculation
path = bandpath([G, M, K, G, A, L, H, A], ase_cell.cell, npoints=50)
kpts = path.kpts
kpath, sp_points, labels = path.get_linear_kpoint_axis()

old_path = os.path.join(os.getcwd(), 'previous.chk')
kmf = pbcdft.KRKS(cell, cell.make_kpts([1,1,1]))
kmf.xc = 'PBE'
kmf.__dict__.update(scf.chkfile.load(old_path, 'scf'))
# starred AGW calculation based off of the mean field object that is  given in the check fail
new_path = os.path.join(os.getcwd(), 'new.chk')
mygw = krgw_ac.KRGWAC(kmf).density_fit()
mygw.chkfile = new_path
mygw.kernel()
```
The message makes a bit of sense; looking at [the documentation](https://pyscf.org/user/pbc/df.html) it seems like the density fitting should have been automatically for my mean field calculation when interested in doing a post SCF calculation.
However, having instead just
```
mygw = krgw_ac.KRGWAC(kmf)
```
was giving me
```
Traceback (most recent call last):
  File "/central/home/pkozlows/ch121b/gan/dft/g0w0/pbe/szv/111/1/g0s1.py", line 45, in <module>
    mygw.kernel()
  File "/groups/wag/pkozlows/miniconda3/envs/pyscf/lib/python3.11/site-packages/pyscf/pbc/gw/krgw_ac.py", line 639, in kernel
    kernel(self, mo_energy, mo_coeff, orbs=orbs,
  File "/groups/wag/pkozlows/miniconda3/envs/pyscf/lib/python3.11/site-packages/pyscf/pbc/gw/krgw_ac.py", line 86, in kernel
    raise RuntimeError('Found incompatible integral scheme %s.'
RuntimeError: Found incompatible integral scheme <class 'pyscf.pbc.df.fft.FFTDF'>.KGWAC can be only used with GDF integrals
```
A more robust example of how to use [this code](https://pubs.acs.org/doi/10.1021/acs.jctc.0c00704) would be helpful.
If this is just going to take some time, I understand, but I just wanted to express that I am interested in this :)

**Comment by tberkel** [comment]
You have to apply density fitting to the DFT calculation,
`kmf = pbcdft.KRKS(cell, cell.make_kpts([1, 1, 1])).density_fit()`

If you look at my recent PR #1967, I have added an example that shows how to do a periodic DFT+GW calculation.

**Comment by tberkel** [comment]
If you just do
```
from pyscf.pbc import gw
mygw = gw.KRGW(...)
```
it will call the functions in the file `gw_slow.py`, which I think are defunct and need to be deleted or updated. So you have to import and use the ACGW or CDGW specifically.

**Comment by verena-neufeld** [comment]
Hi Patryk, thanks for posting this question. Has it been resolved for you now?

**Comment by pkozlows** [comment]
Resolved
