### ISSUE TITLE
Issue install pySCF extension modules

### ISSUE THREAD

**Issue by nmaskara** [pyscf/pyscf#1980]
I've install pyscf via pip, but am getting the folowing error message when i try to install the geomopt extension
```

Collecting geometric>=0.9.7.2 (from pyscf[geomopt])
  Using cached geometric-1.0.1.tar.gz (429 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      /private/var/folders/s3/3_6505pn269_dtgjnx_5zxxr0000gn/T/pip-install-4l9o2yyd/geometric_72cb9561ac8d4622af2dba861b9a0dcf/versioneer.py:421: SyntaxWarning: invalid escape sequence '\s'
        LONG_VERSION_PY['git'] = '''
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/s3/3_6505pn269_dtgjnx_5zxxr0000gn/T/pip-install-4l9o2yyd/geometric_72cb9561ac8d4622af2dba861b9a0dcf/setup.py", line 30, in <module>
          version=versioneer.get_version(),
                  ^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/s3/3_6505pn269_dtgjnx_5zxxr0000gn/T/pip-install-4l9o2yyd/geometric_72cb9561ac8d4622af2dba861b9a0dcf/versioneer.py", line 1480, in get_version
          return get_versions()["version"]
                 ^^^^^^^^^^^^^^
        File "/private/var/folders/s3/3_6505pn269_dtgjnx_5zxxr0000gn/T/pip-install-4l9o2yyd/geometric_72cb9561ac8d4622af2dba861b9a0dcf/versioneer.py", line 1412, in get_versions
          cfg = get_config_from_root(root)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/s3/3_6505pn269_dtgjnx_5zxxr0000gn/T/pip-install-4l9o2yyd/geometric_72cb9561ac8d4622af2dba861b9a0dcf/versioneer.py", line 342, in get_config_from_root
          parser = configparser.SafeConfigParser()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

Any suggestions for how to proceed or help fixing the issue would be appreciated!

**Comment by fishjojo** [comment]
If you try `pip install geometric`, does it work?

**Comment by nmaskara** [comment]
Ah! No, it doesn't work. The same error message appears when I run `pip install geometric`

**Comment by fishjojo** [comment]
What python version did you use? 3.12? It's probably that `versioneer` not compatible with your python. Python 3.11 should work.
You may also post the issue on `geometric`'s Github page.

**Comment by nmaskara** [comment]
that worked. thanks!
