### ISSUE TITLE
MINDO is not found after semiempirical extension installed

### ISSUE THREAD

**Issue by histhinking** [pyscf/pyscf#1982]
Hi All,

I followed the guide to install semiempirical extension after installing pyscf 2.4.0 using pip install.
https://pyscf.org/install.html

pip install pyscf
pip install pyscf[semiempirical]

Then I opened python and tried the example given by the same webpage

>>> import pyscf
>>> from pyscf.semiempirical import MINDO3
>>> mol = pyscf.M(atom='N 0 0 0; N 0 0 1')
>>> MINDO(mol).run()

The error message shows that MINO is not defined

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'MINDO' is not defined

Then I tried  MINDO3(mol).run()

The error message shows that name 'mol' is not defined

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/$USER/.conda/envs/test/lib/python3.6/site-packages/pyscf/lib/misc.py", line 599, in run
    self.kernel(*args)
  File "<string>", line 2, in kernel
  File "/home/$USER/.conda/envs/test/lib/python3.6/site-packages/pyscf/scf/hf.py", line 1712, in scf
    self.dump_flags()
  File "/home/$USER/.conda/envs/test/lib/python3.6/site-packages/pyscf/semiempirical/mindo3.py", line 173, in dump_flags
    log = logger.new_logger(mol, verbose)

NameError: name 'mol' is not defined

How to fix it? 

Thanks.

**Comment by sunqm** [comment]
New version for the extension is released on pypi. This error has been fixed in the new version.
