### ISSUE TITLE
Setting SO3 Symmetry

### ISSUE THREAD

**Issue by szgoger** [pyscf/pyscf#1992]
I am trying to run some calculations for free atoms with a forced `SO3` symmetry. I reckon this should be available in the code (I am using version `2.4.0` as installed by `pip`. However, the following simple initialization

```
mol = gto.M(
    atom = [['He', (0.0, 0.0, 0.0)]],
    basis = 'aug-cc-pvdz',
    spin=0,
    charge=0,
    verbose=2,
    symmetry='SO3'
)
mol.build() #Molecule object
```

raises the error

```
Traceback (most recent call last):
  File "r_test.py", line 8, in <module>
    mol = gto.M(
  File "/mnt/irisgpfs/users/sgoger/R4_atoms/pyscf_env/lib/python3.8/site-packages/pyscf/gto/mole.py", line 114, in M
    mol.build(*args, **kwargs)
  File "/mnt/irisgpfs/users/sgoger/R4_atoms/pyscf_env/lib/python3.8/site-packages/pyscf/gto/mole.py", line 2577, in build
    self._build_symmetry()
  File "/mnt/irisgpfs/users/sgoger/R4_atoms/pyscf_env/lib/python3.8/site-packages/pyscf/gto/mole.py", line 2606, in _build_symmetry
    if symm.check_symm(self.symmetry, self._atom, self._basis):
  File "/mnt/irisgpfs/users/sgoger/R4_atoms/pyscf_env/lib/python3.8/site-packages/pyscf/symm/geom.py", line 530, in check_symm
    ops = [opdic[op] for op in OPERATOR_TABLE[gpname]]
KeyError: 'SO3'
```

Indeed, the error message makes _some_ sense, as there is no `SO3` listed in the 'OPERATOR_TABLE' of 'symm/params.py'. From other parts of the code, however, it seems that the 'SO3' symmetry should be supported.

Am I setting the symmetry wrong, or is there something missing in the code? For reference, other symmetries listed in the table seem to work.

**Comment by fishjojo** [comment]
Setting `symmetry=True` should automatically use the SO3 symmetry.

**Comment by szgoger** [comment]
It seems to be true, even for open-shell atoms. That solves my specific issue. Still, I think the code should not crash when trying to explicitly set this symmetry.

**Comment by szgoger** [comment]
Actually, I seem to be getting an error raised: `TODO: total wave-function symmetry for SO3`. Is this concerning for applications requiring matrix elements calculated from 2RDM?
