### ISSUE TITLE
PySCF does not work when ENABLE_XCFUN=OFF

### ISSUE THREAD

**Issue by susilehtola** [pyscf/pyscf#2016]
Seeing if #1517 was solved, I tried to run the test calculation in the master branch. The result is the following
```
converged SCF energy = -14.8697593368284
/home/work/pyscf/pyscf/dft/libxc.py:772: UserWarning: Since PySCF-2.3, B3LYP (and B3P86) are changed to the VWN-RPA variant, corresponding to the original definition by Stephens et al. (issue 1480) and the same as the B3LYP functional in Gaussian. To restore the VWN5 definition, you can put the setting "B3LYP_WITH_VWN5 = True" in pyscf_conf.py
  warnings.warn('Since PySCF-2.3, B3LYP (and B3P86) are changed to the VWN-RPA variant, '
Traceback (most recent call last):
  File "/tmp/tes.py", line 20, in <module>
    mci = fci.FCI(mol, mf.mo_coeff, singlet=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/work/pyscf/pyscf/fci/__init__.py", line 136, in FCI
    if getattr(mol, 'pbc_intor', None):  # cell object has pbc_intor method
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/work/pyscf/pyscf/gto/mole.py", line 3707, in __getattr__
    from pyscf import __all__  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/work/pyscf/pyscf/__all__.py", line 2, in <module>
    from .post_scf import *  # noqa: F403
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/work/pyscf/pyscf/post_scf.py", line 1, in <module>
    from . import mp, ci, cc, mcscf, fci, tdscf
  File "/home/work/pyscf/pyscf/tdscf/__init__.py", line 21, in <module>
    from pyscf.tdscf import ghf
  File "/home/work/pyscf/pyscf/tdscf/ghf.py", line 28, in <module>
    from pyscf import dft
  File "/home/work/pyscf/pyscf/dft/__init__.py", line 34, in <module>
    from pyscf.dft import xcfun
  File "/home/work/pyscf/pyscf/dft/xcfun.py", line 255, in <module>
    MAX_DERIV_ORDER = ctypes.c_int.in_dll(_itrf, 'XCFUN_max_deriv_order').value
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
The offensive change originates from @sunqm commit 7de9150598

**Comment by verena-neufeld** [comment]
Does this work now with PR #2040 merged?

**Comment by susilehtola** [comment]
Yes, this is fixed; but again found a new bug elsewhere.

**Comment by verena-neufeld** [comment]
Thanks @susilehtola ! As you know, feel free to post the new bug in a new issue if it's also related to pyscf. Thanks!
