### ISSUE TITLE
pyscf.pbc.gto.parse bug

### ISSUE THREAD

**Issue by ZihangL** [pyscf/pyscf#2043]
Dear,
I encounter a small bug of `pyscf.pbc.gto.parse` when I am using pyscf2.4. In pyscf2.3, the code runs correctly.

My code
```python
import numpy as np
from pyscf.pbc import gto
cell = gto.Cell()
cell.unit = 'B'
cell.atom = '''H     4.1965594  4.227266   4.30915   
               H     1.2282612  2.5588777  4.30915   
               H     0.51177555 1.2794389  0.51177555
               H     2.5588777  0.         0.        '''
cell.spin = 0
cell.basis = {'H':gto.parse('''#BASIS SET
                               H SZV-GTH
                               1
                               1  0  0  4  1
                                       8.3744350009  -0.0283380461
                                       1.8058681460  -0.1333810052
                                       0.4852528328  -0.3995676063
                                       0.1658236932  -0.5531027541
                               #''')}
cell.a = np.eye(3) * 5.117755447140034
cell.build()
print(cell)
```

Run in pyscf 2.4
```bash
Traceback (most recent call last):
  File "/home/lizh/hydrogen/hydrogen/main/src/temp/pyscf24bug.py", line 10, in <module>
    cell.basis = {'H':gto.parse('''#BASIS SET
  File "/home/lizh/.local/lib/python3.9/site-packages/pyscf/gto/basis/__init__.py", line 496, in parse
    return parse_cp2k.parse(string, symb, optimize)
TypeError: parse() takes from 1 to 2 positional arguments but 3 were given
```

Run in pyscf 2.3
```bash
<pyscf.pbc.gto.cell.Cell object at 0x2aaab1fefe50>
```

**Comment by verena-neufeld** [comment]
Thanks @ZihangL for reporting this bug! I haven't closely looked, but it does seem that in https://github.com/pyscf/pyscf/blob/35835bcb950b525aa89df6d8eb6e0f0366627549/pyscf/gto/basis/__init__.py#L494 , the line should be `return parse_cp2k_pp.parse(string)` and in https://github.com/pyscf/pyscf/blob/35835bcb950b525aa89df6d8eb6e0f0366627549/pyscf/gto/basis/__init__.py#L496 , the line should be `return parse_cp2k.parse(string, optimize)`.

**Comment by ZihangL** [comment]
Thanks for your reply!

**Comment by verena-neufeld** [comment]
I think this has been fixed now thanks to @fishjojo PR
