### ISSUE TITLE
UKS gradient fails w/ density fitting

### ISSUE THREAD

**Issue by corinwagen** [pyscf/pyscf#2054]
Here's a minimal reproducible example, on the allyl radical: 

```
import pyscf

xyz = """ C         -0.86337805    0.49973124    0.70910031
 C          0.15258387    0.40261370   -0.20812769
 C          0.75922269   -0.77472711   -0.56700188
 H         -1.30923057    1.44465208    0.95942545
 H         -1.24385452   -0.37533224    1.20633972
 H          0.49822196    1.31479859   -0.67961425
 H          0.45403495   -1.70891595   -0.12897521
 H          1.55239964   -0.80282021   -1.29114640"""

mol = pyscf.M(
    atom=xyz,
    basis="6-31G(d)",
    charge=0,
    spin=1,
    symmetry=True
)

mf = pyscf.scf.KS(mol)
mf.xc = "B3LYP"

mf = mf.density_fit()

energy = mf.kernel()
grad = mf.Gradients().kernel()
```

When I run this (pyscf 2.4.0 py311h38a7831_1 conda-forge), I get this error:

```
Traceback (most recent call last):
  File "/Users/cwagen/business_code/pyscf/uks_grad.py", line 26, in <module>
    grad = mf.Gradients().kernel()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/aimnet2/lib/python3.11/site-packages/pyscf/grad/rhf.py", line 415, in kernel
    de = self.grad_elec(mo_energy, mo_coeff, mo_occ, atmlst)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/aimnet2/lib/python3.11/site-packages/pyscf/grad/uhf.py", line 51, in grad_elec
    vhf = mf_grad.get_veff(mol, dm0)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/aimnet2/lib/python3.11/site-packages/pyscf/df/grad/uks.py", line 84, in get_veff
    vj, vk = ks_grad.get_jk(mol, dm)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/aimnet2/lib/python3.11/site-packages/pyscf/df/grad/rhf.py", line 498, in get_jk
    return get_jk(self, mol, dm, hermi, with_j, with_k)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/aimnet2/lib/python3.11/site-packages/pyscf/df/grad/rhf.py", line 96, in get_jk
    orbol, orbor = _decompose_rdm1 (mf_grad, mol, dm)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/aimnet2/lib/python3.11/site-packages/pyscf/df/grad/rhf.py", line 359, in _decompose_rdm1
    nmo = mo_occ.shape[-1]
          ^^^^^^^^^^^^
AttributeError: 'tuple' object has no attribute 'shape'
```

It looks like there's a missing call to ``np.stack()`` somewhere? 

The code runs fine if I don't use density fitting.

**Comment by verena-neufeld** [comment]
Seems to be fixed now

**Comment by verena-neufeld** [comment]
Thanks for having reported these issues @corinwagen !

**Comment by corinwagen** [comment]
Yep this works for me! Thanks @sunqm @verena-neufeld for speedy response
