### ISSUE TITLE
SGX Fails When PJS=True

### ISSUE THREAD

**Issue by corinwagen** [pyscf/pyscf#2065]
This is benzene, HF/def2-SVP - 

```
import pyscf

xyz = """C                 -0.71618036    2.71883299    0.00000000
C                  0.67897964    2.71883299    0.00000000
C                  1.37651764    3.92658399    0.00000000
C                  0.67886364    5.13509299   -0.00119900
C                 -0.71596136    5.13501499   -0.00167800
C                 -1.41356236    3.92680899   -0.00068200
H                 -1.26593936    1.76651599    0.00045000
H                  1.22848764    1.76631999    0.00131500
H                  2.47619764    3.92666399    0.00063400
H                  1.22906364    6.08723599   -0.00125800
H                 -1.26608336    6.08729599   -0.00263100
H                 -2.51316636    3.92699199   -0.00086200"""


mol = pyscf.M(
    atom=xyz,
    basis="def2-SVP",
    charge=0,
    spin=0,
    symmetry=True
)

mf = pyscf.scf.HF(mol)

mf = pyscf.sgx.sgx_fit(mf, pjs=True)

energy = mf.kernel()
```

And here's what I get:

```
Traceback (most recent call last):
  File "/Users/cwagen/business_code/pyscf/sgx_fail.py", line 32, in <module>
    energy = mf.kernel()
             ^^^^^^^^^^^
  File "<string>", line 2, in kernel
  File "/opt/miniconda3/envs/aimnet2/lib/python3.11/site-packages/pyscf/scf/hf.py", line 1713, in scf
    self.build(self.mol)
  File "/opt/miniconda3/envs/aimnet2/lib/python3.11/site-packages/pyscf/sgx/sgx.py", line 141, in build
    self.with_df.build(level=self.with_df.grids_level_i)
  File "/opt/miniconda3/envs/aimnet2/lib/python3.11/site-packages/pyscf/sgx/sgx.py", line 316, in build
    self._opt = _make_opt(self.mol, pjs=self.pjs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/aimnet2/lib/python3.11/site-packages/pyscf/sgx/sgx.py", line 239, in _make_opt
    vhfopt = _vhf.SGXOpt(mol, 'int1e_grids', 'SGXnr_ovlp_prescreen',
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: SGXOpt.__init__() got an unexpected keyword argument 'direct_scf_tol'
```

This works fine when PJS = False.

**Comment by tomfay** [comment]
Bumping this. I'm finding the same issue!
