### ISSUE TITLE
PBC Geometry Optimization

### ISSUE THREAD

**Issue by arturlyssenko12** [pyscf/pyscf#2068]
Hi,

I am new to PySCF and was trying to run pbc optimization of a simple unit cell case. I found the following example in the source code and adapted it:

from pyscf.pbc import gto, scf, grad
from pyscf.pbc.geomopt.geometric_solver import optimize, GeometryOptimizer
cell = gto.Cell()
cell.atom = '''
C 0.000000000000 0.000000000000 0.000000000000
C 1.685068664391 1.685068664391 1.685068664391
'''
cell.atom= [['C', [0.0, 0.0, 0.0]], ['C', [1.685068664391,1.685068664391,1.685068664391]]]
cell.a = '''
0.000000000, 3.370137329, 3.370137329
3.370137329, 0.000000000, 3.370137329
3.370137329, 3.370137329, 0.000000000'''
cell.basis = 'gth-szv'
cell.verbose= 4
cell.pseudo = 'gth-pade'
cell.unit = 'bohr'
cell.build()

kpts = cell.make_kpts([1,1,3])
mf = scf.KRHF(cell, kpts, exxdiv=None)
mf.conv_tol = 1e-14
mf.conv_tol_grad = 1e-8
conv_params = {
'convergence_energy': 1e-4,  # Eh
'convergence_grms': 1e-5,    # Eh/Bohr
'convergence_gmax': 1e-5,  # Eh/Bohr
'convergence_drms': 1.2e-2,  # Angstrom
'convergence_dmax': 1.8e-2,  # Angstrom
}
opt = GeometryOptimizer(mf).set(params=conv_params)#.run()
opt.run()
cell = opt.cell

However, I get the following errors:
Traceback (most recent call last):
  File "/home/alyssenko/mims/example.py", line 31, in <module>
    opt.run()
  File "/home/alyssenko/miniforge3/envs/htvs/lib/python3.9/site-packages/pyscf/lib/misc.py", line 599, in run
    self.kernel(*args)
  File "/home/alyssenko/miniforge3/envs/htvs/lib/python3.9/site-packages/pyscf/pbc/geomopt/geometric_solver.py", line 204, in kernel
    kernel(self.method, callback=self.callback,
  File "/home/alyssenko/miniforge3/envs/htvs/lib/python3.9/site-packages/pyscf/pbc/geomopt/geometric_solver.py", line 146, in kernel
    geometric.optimize.run_optimizer(customengine=engine, input=tmpf,
  File "/home/alyssenko/miniforge3/envs/htvs/lib/python3.9/site-packages/geometric/optimize.py", line 808, in run_optimizer
    logging.config.fileConfig(logIni,defaults={'logfilename': logfilename},disable_existing_loggers=False)
  File "/home/alyssenko/miniforge3/envs/htvs/lib/python3.9/logging/config.py", line 71, in fileConfig
    formatters = _create_formatters(cp)
  File "/home/alyssenko/miniforge3/envs/htvs/lib/python3.9/logging/config.py", line 104, in _create_formatters
    flist = cp["formatters"]["keys"]
  File "/home/alyssenko/miniforge3/envs/htvs/lib/python3.9/configparser.py", line 963, in __getitem__
    raise KeyError(key)
KeyError: 'formatters'

I am wondering if I am missing a dependency for pyscf? If not could someone please help point me to the root of the problem? Thank you!

**Comment by fishjojo** [comment]
I was able to run your script with no issue. Please try to upgrade the [geometric](https://github.com/leeping/geomeTRIC) package.
