### ISSUE TITLE
SG1 Prune Not Defined For Heavy Atoms

### ISSUE THREAD

**Issue by corinwagen** [pyscf/pyscf#2082]
Here's a minimal reproducible example, with VV10 settings adapted from [Narbe's demo code](https://github.com/pyscf/pyscf/blob/master/examples/dft/33-nlc_functionals.py):

```
import pyscf

xyz = """ H    0    0    -1.403
Br   0    0    0.040"""


mol = pyscf.M(
    atom=xyz,
    basis={"H": "cc-pVTZ", "Br": "cc-pVTZ-PP"},
    ecp={"Br": "cc-pVTZ-PP"},
    charge=0,
    spin=0,
    symmetry=True
)

mf = pyscf.scf.KS(mol)
mf.xc = "wB97MV"

mf.nlc = "vv10"
mf.nlcgrids.atom_grid = (50, 194)
mf.nlcgrids.prune = pyscf.dft.gen_grid.sg1_prune

energy = mf.kernel()
```

This gives an error: 

```
Traceback (most recent call last):
  File "/Users/cwagen/business_code/pyscf/ecp_atom_guess.py", line 23, in <module>
    energy = mf.kernel()
             ^^^^^^^^^^^
  File "<string>", line 2, in kernel
  File "/opt/miniconda3/envs/aimnet2/lib/python3.11/site-packages/pyscf/scf/hf.py", line 1779, in scf
    kernel(self, self.conv_tol, self.conv_tol_grad,
  File "/opt/miniconda3/envs/aimnet2/lib/python3.11/site-packages/pyscf/scf/hf.py", line 124, in kernel
    vhf = mf.get_veff(mol, dm)
          ^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/aimnet2/lib/python3.11/site-packages/pyscf/dft/rks.py", line 69, in get_veff
    ks.initialize_grids(mol, dm)
  File "/opt/miniconda3/envs/aimnet2/lib/python3.11/site-packages/pyscf/dft/rks.py", line 477, in initialize_grids
    self.nlcgrids.build(with_non0tab=True)
  File "/opt/miniconda3/envs/aimnet2/lib/python3.11/site-packages/pyscf/dft/gen_grid.py", line 548, in build
    atom_grids_tab = self.gen_atomic_grids(
                     ^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 6, in gen_atomic_grids
  File "/opt/miniconda3/envs/aimnet2/lib/python3.11/site-packages/pyscf/dft/gen_grid.py", line 258, in gen_atomic_grids
    angs = prune(chg, rad, n_ang)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/aimnet2/lib/python3.11/site-packages/pyscf/dft/gen_grid.py", line 116, in sg1_prune
    r_atom = radii[nuc] + 1e-200
             ~~~~~^^^^^
IndexError: index 35 is out of bounds for axis 0 with size 19
```

This makes some degree of sense, since SG1 doesn't mention atoms past Ar (cf. [Table 4](https://rsc.anu.edu.au/~pgill/papers/038SG1.pdf)). But this is also somewhat frustrating behavior, since SG1 is the recommended grid for VV10 (cf. [Mardirossian 2014](https://pubs.rsc.org/en/content/articlelanding/2014/cp/c3cp54374a)) - it seems to be that a decent fallback behavior would just be to suppress pruning for heavier atoms, which is what SG2 and SG3 do (Herbert/Dasgupta *JCC* **2017** *38* 869–882). I imagine this is also what QChem does for SG1, although I'm not 100% sure?

**Comment by fishjojo** [comment]
There is a little pruning but not much. You probably need to consult the qchem team.

**Comment by corinwagen** [comment]
> There is a little pruning but not much. You probably need to consult the qchem team.

I contacted someone at Q-Chem, but they said they couldn't divulge this because of their NDA. Sorry...
