### ISSUE TITLE
using PE (polarized embedding) give error with the latest version

### ISSUE THREAD

**Issue by marwafar** [pyscf/pyscf#2091]
I used to run the code with the previous version and it was working. After updating to the latest version, running the simulation with polarized embedding hamiltonian gives the following error:

Traceback (most recent call last):
  File "/home/Solvation/pyscf-pe.py", line 87, in <module>
    mf = solvent.PE(myhf, 'water.pot').run()
  File "/home/.local/lib/python3.10/site-packages/pyscf/solvent/__init__.py", line 98, in PE
    from pyscf.solvent import pol_embed
  File "/home/.local/lib/python3.10/site-packages/pyscf/solvent/pol_embed.py", line 49, in <module>
    from packaging.version import parse as _parse_version
ModuleNotFoundError: No module named 'packaging'

**Comment by marwafar** [comment]
fixed after using pip install packaging
