### ISSUE TITLE
Unable to use custom xc functional

### ISSUE THREAD

**Issue by bikashkanungo** [pyscf/pyscf#2092]
Hi PySCF developers,

I'm new to using PySCF. I wanted to plugin my own XC functional using the define_xc_() interface in the dft module. To begin with, I attempted to run the example that demonstrates the use of custom XC functional (https://github.com/pyscf/pyscf/blob/master/examples/dft/24-define_xc_functional.py). However, running it throws the following error:

```
Traceback (most recent call last):
  File "custom_xc_test.py", line 63, in <module>
    mf.kernel()
  File "<string>", line 2, in kernel
  File "/home/biku/miniconda3/lib/python3.8/site-packages/pyscf/scf/hf.py", line 1779, in scf
    kernel(self, self.conv_tol, self.conv_tol_grad,
  File "/home/biku/miniconda3/lib/python3.8/site-packages/pyscf/scf/hf.py", line 124, in kernel
    vhf = mf.get_veff(mol, dm)
  File "/home/biku/miniconda3/lib/python3.8/site-packages/pyscf/dft/rks.py", line 80, in get_veff
    n, exc, vxc = ni.nr_rks(mol, ks.grids, ks.xc, dm, max_memory=max_memory)
  File "/home/biku/miniconda3/lib/python3.8/site-packages/pyscf/dft/numint.py", line 1158, in nr_rks
    for i, ao, mask, wv in block_loop(ao_deriv):
  File "/home/biku/miniconda3/lib/python3.8/site-packages/pyscf/dft/numint.py", line 1138, in block_loop
    exc, vxc = ni.eval_xc_eff(xc_code, rho, deriv=1, xctype=xctype)[:2]
  File "/home/biku/miniconda3/lib/python3.8/site-packages/pyscf/dft/numint.py", line 2696, in eval_xc_eff
    out = self.libxc.eval_xc1(xc_code, rho, spin, deriv, omega)
  File "/home/biku/miniconda3/lib/python3.8/site-packages/pyscf/dft/libxc.py", line 1599, in eval_xc1
    out = _eval_xc(xc_code, rho, spin, deriv=deriv, omega=omega)
  File "/home/biku/miniconda3/lib/python3.8/site-packages/pyscf/dft/libxc.py", line 1654, in _eval_xc
    rho = rho.reshape(spin+1,nvar,ngrids)
ValueError: cannot reshape array of size 120224 into shape (1,1,30056)
```

The custom_xc_test.py is just a copy of the example link provided above. 

I used `pip install --prefer-binary pyscf` to install my PySCF.

I would really appreciate it if you can help me figure out how to use a custom XC functional. 

Regards,
Bikash

**Comment by tberkel** [comment]
I can reproduce this error with a new version compiled from source, so it's not the installation. Thanks for reporting the error.

**Comment by fishjojo** [comment]
You may use PySCF v5.3. v5.4 has introduced a new convention for the `eval_xc` function, which is now the `eval_xc_eff` function that is used by default. This is a backward compatibility issue that should be fixed.
