### ISSUE TITLE
Unable to Install PyScf with [all] Extensions

### ISSUE THREAD

**Issue by JaafarMehrez** [pyscf/pyscf#2099]
On Mac M1 chip and inside a virtual environment where all dependencies are already installed, I am trying to install pyscf along all the extensions using `pip install pyscf[all]`  upon which I am getting the following error: 
```
setuptools.installer and fetch_build_eggs are deprecated.
      !!

              ********************************************************************************
              Requirements should be satisfied by a PEP 517 installer.
              If you are using pip, you can try `pip install --use-pep517`.
              ********************************************************************************

      !!
```
following that I tried to run `pip install --use-pep517 pyscf[all]`, upon which I will get the following error: 

```
 × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      **************************************************
      * numpy was not installed in your system.  Please run
      *     pip install numpy
      * before installing pyscf.
      **************************************************
      Traceback (most recent call last):
        File "/Users/jm/miniconda3/envs/dft/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/jm/miniconda3/envs/dft/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/jm/miniconda3/envs/dft/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/sv/p893skhd53z1sh_0fgwlc_0w0000gn/T/pip-build-env-ejep_s3r/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/private/var/folders/sv/p893skhd53z1sh_0fgwlc_0w0000gn/T/pip-build-env-ejep_s3r/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/sv/p893skhd53z1sh_0fgwlc_0w0000gn/T/pip-build-env-ejep_s3r/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/private/var/folders/sv/p893skhd53z1sh_0fgwlc_0w0000gn/T/pip-build-env-ejep_s3r/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 36, in <module>
        File "<string>", line 29, in <module>
      ModuleNotFoundError: No module named 'numpy'
```
Which is mainly complaining that numpy is not installed, however I have numpy installed in that virtual environment to its latest version, confirmed with pip list  `numpy  1.26.4`

Any suggestion for solving this issue would be appreciated. Thanks

**Comment by sunqm** [comment]
The error message looks like the failure is due to numpy installation? Can you try install dependencies and extensions one by one to identify the error?
```
pip install numpy
pip install pyscf-forge 
pip install "pyberny>=0.6.2" 
pip install "geometric>=0.9.7.2" 
pip install pyscf-qsdopt
pip install pyscf-doci 
pip install pyscf-properties 
pip install pyscf-semiempirical 
pip install cppe
pip install pyqmc
pip install basis-set-exchange
pip install pyscf-dispersion
```

**Comment by verena-neufeld** [comment]
Hi @JaafarMehrez , thanks for your question. Has it been answered and can this issue be closed?
