### ISSUE TITLE
Questions about the ccecp of Mo atom

### ISSUE THREAD

**Issue by Yongda1** [pyscf/pyscf#2128]
Excuse me, I want to calculate of MoS2. But Pyscf tells me " Basis data not found". Any way to solve it?

Best regards
Yongda

**Comment by tberkel** [comment]
Not all atoms have basis sets from all basis set families. It appears PySCF doesn't have any ccECP basis sets for Mo. If you find one that exists, you can enter it yourself manually, as shown in `pyscf/examples/gto/04-input_basis.py`.

**Comment by shivupa** [comment]
Mo and S are available at https://pseudopotentiallibrary.org/ if they haven't been added to PySCF yet

These two examples will be helpful on how to load a basis + ecp
https://github.com/pyscf/pyscf/blob/master/examples/gto/04-input_basis.py
https://github.com/pyscf/pyscf/blob/master/examples/gto/05-input_ecp.py

**Comment by shivupa** [comment]
Yes I was going to say always use the corresponding basis set for the respective pseudopotential. The basis sets are also provided at the link I sent in various formats

**Comment by Yongda1** [comment]
Thanks. I only see the pseudopotential. Could you tell the where to find the corresponding basis?

**Comment by shivupa** [comment]
Yeah so on the website there are files like `ATOM.ccecp.CODE` where `ATOM` is the atom you want and `CODE` is some software package. Those files are the pseudopotentials.

The basis sets are the `ATOM.BASIS.CODE` where `BASIS` is something like `augccpvdz`. 

Pick the `CODE` based on what pyscf can parse. I'm not sure what ecp formats pyscf can parse. Maybe NWCHEM? The example can help with choosing the right format. 

Also:
For Mo, you have the choice of a SOREP or AREP, with and without spin orbit effects. And for S you have a choice of core sizes (a different number of electrons replaced). You will need to chose what pseudopotentials you want based on your scientific problem. 

A good starting place might be the AREP for Mo and the larger core for S (more electrons replace). If possible compare the properties you want to calculate with pseudopotentials to all-electron results.

**Comment by Yongda1** [comment]
Thank you very much ! I will try it !

**Comment by Yongda1** [comment]
Sorry, I got one more problem. I got an error , invalid literal for int() with base 10: '69.256405  -0.000019'. It looks like Pyscf is trying to interpret the input by CP2K format. Does pyscf support Periodic boundary condition?

**Comment by shivupa** [comment]
Can you post the python file you are trying to run with the `gto.basis.parse_ecp` and `gto.parse` commands? I recommend using NWCHEM formats for the basis and ECPs. PySCF can use that format.

PySCF does support PBC and there are several examples here https://github.com/pyscf/pyscf/tree/master/examples/pbc

**Comment by Yongda1** [comment]
I solved it. I used gto from pyscf.pbc, that is why I got the error abour format. But another problem happened about ecp part. Thanks.
[MoS2.txt](https://github.com/pyscf/pyscf/files/14577032/MoS2.txt)

**Comment by Yongda1** [comment]
[MoS2.txt](https://github.com/pyscf/pyscf/files/14577072/MoS2.txt)
Thanks. I solved it. I used the gto from pyscf.pbc. But another problem about ecp part happened. Please help me.

**Comment by Yongda1** [comment]
Any mistakes about the input file? Thanks.

**Comment by shivupa** [comment]
Can you copy and paste the input as a code block (use 3 back ticks to open a code block)? I can't open the text file

Also post the error message. It is easier to debug if I see the message.

**Comment by Yongda1** [comment]
Thanks!
```python
import numpy
from pyscf import gto
from pyscf.pbc import gto as pgto
from pyscf.pbc import scf

def make_cell():
    cell = pgto.Cell()
    cell.atom = """
    Mo 2.98392066 1.72276739 6.32032794
    Mo 0.00000000 3.44553479 19.17046565
    S 0.00000000 3.44553479  3.33770143
    S 0.00000000 3.44553479  9.30295445
    S 2.98392066 1.72276739  16.18783914
    S 2.98392066 1.72276739  22.15309216
    """
    cell.basis = {'Mo': gto.parse('''
Mo S
     69.256405  -0.000019
     36.439356   0.001566
     19.172619  -0.028400
     10.087701   0.209329
      5.307658  -0.374473
      2.792632  -0.425216
      1.469347   0.424867
      0.773099   0.676129
      0.406767   0.310600
      0.214021   0.025503
      0.112608   0.004380
      0.059249  -0.004375
      0.031174  -0.001251
Mo S
     69.256405   0.000003
     36.439356  -0.000430
     19.172619   0.008527
     10.087701  -0.066553
      5.307658   0.129519
      2.792632   0.133264
      1.469347  -0.157887
      0.773099  -0.319833
      0.406767  -0.229575
      0.214021  -0.022854
      0.112608   0.401381
      0.059249   0.458608
      0.031174   0.353669
Mo S
     69.256405  -0.000072
     36.439356  -0.000488
     19.172619   0.017400
     10.087701  -0.147523
      5.307658   0.300343
      2.792632   0.328314
      1.469347  -0.487559
      0.773099  -1.076705
      0.406767  -0.076225
      0.214021   1.649122
      0.112608   0.511357
      0.059249  -0.618570
      0.031174  -0.664542
Mo S
     69.256405  -0.000454
     36.439356   0.001112
     19.172619   0.022079
     10.087701  -0.234779
      5.307658   0.518803
      2.792632   0.714395
      1.469347  -1.846476
      0.773099  -1.796154
      0.406767   4.372657
      0.214021  -0.434280
      0.112608  -2.676955
      0.059249   0.444245
      0.031174   0.970937
Mo S
      0.031174   1.000000
Mo P
     77.150367   0.000003
     40.594908   0.000075
     21.360190  -0.002401
     11.239285   0.035359
      5.913876  -0.141836
      3.111758  -0.082811
      1.637342   0.327357
      0.861535   0.474165
      0.453322   0.300669
      0.238528   0.076103
      0.125509   0.010565
      0.066040   0.000312
      0.034749   0.000334
Mo P
     77.150367  -0.000012
     40.594908   0.000018
     21.360190   0.001168
     11.239285  -0.021143
      5.913876   0.091995
      3.111758   0.047665
      1.637342  -0.248952
      0.861535  -0.430199
      0.453322  -0.106808
      0.238528   0.519713
      0.125509   0.525571
      0.066040   0.149464
      0.034749   0.008371
Mo P
     77.150367   0.000038
     40.594908  -0.000142
     21.360190  -0.001183
     11.239285   0.028673
      5.913876  -0.134756
      3.111758  -0.061086
      1.637342   0.496626
      0.861535   0.572118
      0.453322  -0.621235
      0.238528  -0.939479
      0.125509   0.285982
      0.066040   0.716320
      0.034749   0.222142
Mo P
     77.150367  -0.000560
     40.594908   0.002616
     21.360190  -0.005256
     11.239285  -0.026721
      5.913876   0.167775
      3.111758   0.261337
      1.637342  -1.452417
      0.861535  -0.146436
      0.453322   2.634034
      0.238528  -1.499901
      0.125509  -1.091350
      0.066040   0.865530
      0.034749   0.400963
Mo P
      0.034749   1.000000
Mo D
     67.297671   0.000088
     35.419488  -0.000427
     18.641658   0.002143
      9.811305  -0.002314
      5.163795  -0.015767
      2.717761   0.056271
      1.430387   0.203165
      0.752828   0.299890
      0.396221   0.299775
      0.208536   0.232455
      0.109755   0.127672
      0.057765   0.038964
      0.030402   0.003430
Mo D
     67.297671  -0.000116
     35.419488   0.000565
     18.641658  -0.002949
      9.811305   0.003632
      5.163795   0.020398
      2.717761  -0.091207
      1.430387  -0.319761
      0.752828  -0.384649
      0.396221  -0.032169
      0.208536   0.392896
      0.109755   0.404265
      0.057765   0.166215
      0.030402   0.021087
Mo D
     67.297671  -0.000173
     35.419488   0.000846
     18.641658  -0.004528
      9.811305   0.006114
      5.163795   0.032626
      2.717761  -0.179375
      1.430387  -0.628235
      0.752828  -0.082344
      0.396221   0.920012
      0.208536   0.254355
      0.109755  -0.533406
      0.057765  -0.344247
      0.030402  -0.048462
Mo D
      0.030402   1.000000
Mo F
      1.220300   1.000000
Mo F
      0.333200   1.000000
Mo G
      0.732400   1.000000'''), 'S': gto.parse('''
      S S
        14.052570 0.002102
        7.864913 -0.011042
        4.401818 0.086618
        2.463600 -0.271004
        1.378823 -0.151274
        0.771696 0.136044
        0.431901 0.394360
        0.241726 0.432098
        0.135289 0.230974
        0.075718 0.051205
      S S
        0.833303 1.000000
      S S
        0.149345 1.000000
      S P
        6.808844 -0.003573
        3.941560 0.001903
        2.281723 -0.065016
        1.320863 0.042305
        0.764632 0.158772
        0.442637 0.278172
        0.256237 0.293821
        0.148333 0.248015
        0.085868 0.114905
        0.049708 0.032934
      S P
        0.708198 1.000000
      S P
        0.114216 1.000000
      S D
        0.921034 1.000000
      S D
        0.289603 1.000000
      S F
        0.565677 1.000000''')},
    cell.a = """
    5.96784131, 0.00000000, 0.00000000
    -2.98392065, 5.16830218, 0.00000000
    0.0, 0.0, 90.70685438"""
    cell.unit = "B"
    cell.verbose = 0
    cell.ecp = {'Mo': gto.basis.parse_ecp('''
ecp
Mo nelec 28
Mo ul
1   10.993527   14.000000
3   11.015078  153.909378
2   10.365343  -91.434311
2    6.281056  -16.945728
Mo s
2   10.079375  180.089303
2    6.321328   16.961392
2    4.386730   24.723630
Mo p
2    9.027487  123.680940
2    6.340373   16.933336
2    3.910532   18.784314
Mo d
2    7.378964   48.289191
2    6.390417   16.932154
2    2.774830    7.940102
'''), 'S': gto.basis.parse_ecp('''S nelec 10
S ul
1 6.151144 6.000000
3 11.561575 36.906864
2 5.390961 -19.819533
S S
2 16.117687 15.925748
2 3.608629 38.515895
S P
2 6.228956 8.062221
2 2.978074 18.737525''')}
    cell.build()
    return cell


def run_scf(nk):
    cell = make_cell()
    kmf = scf.KRHF(cell, exxdiv=None).density_fit()
    kmf.kpts = cell.make_kpts([nk, nk, nk])
    kmf.chkfile = "MoS2.chkfile"
    ehf = kmf.kernel()
    print("EHF", ehf)
    return cell, kmf

cell, kmf = run_scf(nk=1)
``` 
error message
```python
C:\Windows\system32\wsl.exe --distribution Ubuntu --exec /bin/sh -c "export PYCHARM_DISPLAY_PORT=63342 && export PYTHONPATH='/mnt/f/PYQMC-learning:/mnt/d/pycharm-pro/PyCharm 2022.1.1/plugins/python/helpers/pycharm_matplotlib_backend:/mnt/d/pycharm-pro/PyCharm 2022.1.1/plugins/python/helpers/pycharm_display' && export PYTHONUNBUFFERED=1 && export PYTHONIOENCODING=UTF-8 && export PYCHARM_HOSTED=1 && cd /mnt/f/PYQMC-learning/PyqmcJ && /home/yongda/anaconda3/bin/python3 /mnt/f/PYQMC-learning/PyqmcJ/MoS2-pyscf.py"
/home/yongda/anaconda3/lib/python3.10/site-packages/pyscf/dft/libxc.py:772: UserWarning: Since PySCF-2.3, B3LYP (and B3P86) are changed to the VWN-RPA variant, the same to the B3LYP functional in Gaussian and ORCA (issue 1480). To restore the VWN5 definition, you can put the setting "B3LYP_WITH_VWN5 = True" in pyscf_conf.py
  warnings.warn('Since PySCF-2.3, B3LYP (and B3P86) are changed to the VWN-RPA variant, '
Traceback (most recent call last):
  File "/mnt/f/PYQMC-learning/PyqmcJ/MoS2-pyscf.py", line 269, in <module>
    cell, kmf = run_scf(nk=1)
  File "/mnt/f/PYQMC-learning/PyqmcJ/MoS2-pyscf.py", line 261, in run_scf
    cell = make_cell()
  File "/mnt/f/PYQMC-learning/PyqmcJ/MoS2-pyscf.py", line 256, in make_cell
    cell.build()
  File "/home/yongda/anaconda3/lib/python3.10/site-packages/pyscf/pbc/gto/cell.py", line 1371, in build
    mole.Mole.build(self, False, parse_arg, *args, **kwargs)
  File "/home/yongda/anaconda3/lib/python3.10/site-packages/pyscf/gto/mole.py", line 2534, in build
    self._basis = self.format_basis(_basis)
  File "/home/yongda/anaconda3/lib/python3.10/site-packages/pyscf/pbc/gto/cell.py", line 1566, in format_basis
    return format_basis(basis_tab)
  File "/home/yongda/anaconda3/lib/python3.10/site-packages/pyscf/pbc/gto/cell.py", line 172, in format_basis
    return mole.format_basis(fmt_basis)
  File "/home/yongda/anaconda3/lib/python3.10/site-packages/pyscf/gto/mole.py", line 459, in format_basis
    fmt_basis[symb] = basis_converter(symb, atom_basis)
  File "/home/yongda/anaconda3/lib/python3.10/site-packages/pyscf/gto/mole.py", line 488, in converter
    or not isinstance(raw_basis[0][0], int)):
KeyError: 0
```

**Comment by shivupa** [comment]
```
      S D
        0.921034 1.000000
      S D
        0.289603 1.000000
      S F
        0.565677 1.000000''')}, <----
    cell.a = """
```
 Remove this comma. Python is trying to continue this line but you are done constructing the dictionary

**Comment by Yongda1** [comment]
Thanks!

**Comment by Yongda1** [comment]
Sorry. I have one more problem about memory.  I removed this comma then used this modifed input. 
```python
WARN: memory usage of outcore_auxe2 may be 18.10 times over max_memory
``` 
This is the output from slurm.
```python

/var/spool/slurmd/job99055/slurm_script: line 18: 36934 Killed                  python periodic_j3.py > output
slurmstepd: error: Detected 1 oom-kill event(s) in StepId=99055.batch. Some of your processes may have been killed
 by the cgroup out-of-memory handler.
``` 

I am using one node with one GPU on Devana. For quantum espresso, one node is enough for unit cell MoS2. Is there a way to solve it?

**Comment by tberkel** [comment]
You can set `mol.max_memory` (in MB) to override the default, which is 4000 (4 GB).

But separately, I recommend working your way up to the calculation you want to do, to get a sense for the cost (time and memory) of the calculations. For example, start with a single layer of MoS2 (your input looks like a bilayer) and the smallest basis set available, smallest kpt mesh, etc. Then increase as needed/possible.

**Comment by Yongda1** [comment]
Thanks! Have a nice day!

**Comment by shivupa** [comment]
Good advice. Also @Yongda1 if your problem has been solved please close this issue! Feel free to open another issue in the future if anything else goes wrong
