### ISSUE TITLE
memory use for double-layer hBN

### ISSUE THREAD

**Issue by Yongda1** [pyscf/pyscf#2137]
Sorry for this basic question, I need calculate supercell double-layer hBN then use these orbitals to construct single determinant. But I dont know why Pyscf is always telling me that memory is not enough. Here, I show my input , output, and slurm script.  Thanks. 
```python
import numpy
from pyscf import gto
from pyscf.pbc import gto as pgto
from pyscf.pbc import scf,dft

def make_cell():
    cell = pgto.Cell()
    cell.atom = """
    B 0.000000000         1.450551157         1.926816255
    B -1.256214235         3.626378038         1.926816255
    B -2.512428302         5.802204627         1.926816255
    B 2.512428302         1.450551157         1.926816255
    B 1.256214067         3.626378038         1.926816255
    B 0.000000000         5.802204627         1.926816255
    B 5.024856661         1.450551157         1.926816255
    B 3.768642426         3.626378038         1.926816255
    B 2.512428359         5.802204627         1.926816255
    B 1.256214151         0.725275578         5.780448392
    B 0.000000000         2.901102313         5.780448392
    B -1.256214179         5.076929097         5.780448392
    B 3.768642622         0.725275578         5.780448392
    B 2.512428471         2.901102313         5.780448392
    B 1.256214292         5.076929097         5.780448392
    B 6.281070756         0.725275578         5.780448392
    B 5.024856605         2.901102313         5.780448392
    B 3.768642426         5.076929097         5.780448392
    N 0.000000000         1.450551157         5.780448392
    N -1.256214235         3.626378038         5.780448392
    N -2.512428302         5.802204627         5.780448392
    N 2.512428302         1.450551157         5.780448392
    N 1.256214067         3.626378038         5.780448392
    N 0.000000000         5.802204627         5.780448392
    N 5.024856661         1.450551157         5.780448392
    N 3.768642426         3.626378038         5.780448392
    N 2.512428359         5.802204627         5.780448392
    N 1.256214151         0.725275578         1.926816255
    N 0.000000000         2.901102313         1.926816255
    N -1.256214179         5.076929097         1.926816255
    N 3.768642622         0.725275578         1.926816255
    N 2.512428471         2.901102313         1.926816255
    N 1.256214292         5.076929097         1.926816255
    N 6.281070756         0.725275578         1.926816255
    N 5.024856605         2.901102313         1.926816255
    N 3.768642426         5.076929097         1.926816255
"""
    cell.basis = {'B': gto.parse('''
B s
11.76050 -0.0036757
5.150520 0.0250517
2.578276 -0.1249228
1.290648 -0.0662874
0.646080 0.1007341
0.323418 0.3375492
0.161898 0.4308431
0.081044 0.2486558
0.040569 0.0317295
B s
0.422217 1.000000
B s
0.305133 1.000000
B s
0.082968 1.000000
B p
7.470701 0.0047397
3.735743 0.0376009
1.868068 0.0510600
0.934132 0.1456587
0.467115 0.2237933
0.233582 0.3199467
0.116803 0.2850185
0.058408 0.1448808
0.029207 0.0176962
B p
0.447031 1.000000
B p
0.196614 1.000000
B p
0.066445 1.000000
B d
1.142614 1.000000
B d
0.410733 1.000000
B d
0.149100 1.000000
B f
0.870011 1.000000
B f
0.315902 1.000000
B g
0.710746 1.000000'''), 'N': gto.parse('''
N S
42.693822 -0.0009357
19.963207 0.0063295
9.3345971 0.0105038
4.9278187 -0.1653735
2.040920 -0.0005352
0.967080 0.2452063
0.476131 0.4582128
0.211443 0.3641224
0.098869 0.0620406
N S
1.625001 1.0000000
N S
0.310826 1.0000000
N S
0.135764 1.0000000
N P
18.925871 0.0073505
9.225603 0.0292844
4.581431 0.0652168
2.300164 0.1405153
1.154825 0.2328188
0.582039 0.2989556
0.290535 0.2802507
0.145867 0.1527995
0.073234 0.0355475
N P
1.020750 1.0000000
N P
0.413103 1.0000000
N P
0.140736 1.0000000
N D
3.028459 1.0000000
N D
1.009895 1.0000000
N D
0.346233 1.0000000
N F
2.024747 1.0000000
N F
0.691129 1.0000000
N G
1.357512 1.0000000''')}
    cell.a = """
        7.5372848511         0.0000000000         0.0000000000
       -3.7686424255         6.5274801566         0.0000000000
        0.0000000000         0.0000000000        25.0000000000"""
    cell.unit = "A"
    cell.verbose = 5
    cell.exp_to_discard = 0.1
    cell.ecp = {'B': gto.basis.parse_ecp('''
B nelec 2
B ul
1 31.49298 3.00000
3 22.56509 94.47895
2 8.64669 -9.74800
B S
2 4.06246 20.74800
'''), 'N': gto.basis.parse_ecp('''
N nelec 2
N ul
1 12.91881 3.25000
1 9.22825 1.75000
3 12.96581 41.98612
3 8.05477 16.14945
2 12.54876 -26.09522
2 7.53360 -10.32626
N S
2 9.41609 34.77692
2 8.16694 15.20330
''')}
    cell.build()
    return cell


def run_scf(nk):
    cell = make_cell()
    cell.max_memory = 60000
    kmf = dft.KRKS(cell).density_fit()
    kmf.kpts = cell.make_kpts([nk, nk, 1])
    kmf.xc = 'PBE'
    kmf.max_cycle = 100
    kmf.chkfile = "hBN.chkfile"
    ehf = kmf.kernel()
    print("EHF", ehf)
    return cell, kmf

cell, kmf = run_scf(nk=1)

``` 
```python
Traceback (most recent call last):
  File "/home/yongda1/test-hBN-pyscf/supercell_3_3_1/hBN.py", line 179, in <module>
    cell, kmf = run_scf(nk=1)
  File "/home/yongda1/test-hBN-pyscf/supercell_3_3_1/hBN.py", line 175, in run_scf
    ehf = kmf.kernel()
  File "<string>", line 2, in kernel
  File "/home/yongda1/software/pyscf/pyscf/scf/hf.py", line 1783, in scf
    kernel(self, self.conv_tol, self.conv_tol_grad,
  File "/home/yongda1/software/pyscf/pyscf/scf/hf.py", line 126, in kernel
    vhf = mf.get_veff(mol, dm)
  File "/home/yongda1/software/pyscf/pyscf/pbc/dft/krks.py", line 104, in get_veff
    vj = ks.get_j(cell, dm, hermi, kpts, kpts_band)
  File "/home/yongda1/software/pyscf/pyscf/pbc/scf/khf.py", line 511, in get_j
    return self.get_jk(cell, dm_kpts, hermi, kpts, kpts_band,
  File "/home/yongda1/software/pyscf/pyscf/pbc/scf/khf.py", line 529, in get_jk
    vj, vk = self.with_df.get_jk(dm_kpts, hermi, kpts, kpts_band,
  File "/home/yongda1/software/pyscf/pyscf/pbc/df/df.py", line 445, in get_jk
    vj = df_jk.get_j_kpts(self, dm, hermi, kpts, kpts_band)
  File "/home/yongda1/software/pyscf/pyscf/pbc/df/df_jk.py", line 80, in get_j_kpts
    mydf.build(j_only=True, kpts_band=kpts_band)
  File "/home/yongda1/software/pyscf/pyscf/pbc/df/df.py", line 262, in build
    self._make_j3c(self.cell, self.auxcell, None, cderi)
  File "/home/yongda1/software/pyscf/pyscf/pbc/df/df.py", line 289, in _make_j3c
    dfbuilder.make_j3c(cderi_file, j_only=j_only, dataname=self._dataname,
  File "/home/yongda1/software/pyscf/pyscf/pbc/df/rsdf_builder.py", line 1002, in make_j3c
    make_cderi(kpt, kpt_ij_idx, cd_j2c)
  File "/home/yongda1/software/pyscf/pyscf/pbc/df/rsdf_builder.py", line 994, in make_cderi
    feri[f'{dataname}/{idx}/{istep}'] = cderi
  File "/home/yongda1/.local/lib/python3.10/site-packages/h5py/_hl/group.py", line 483, in __setitem__
    ds = self.create_dataset(None, data=obj)
  File "/home/yongda1/.local/lib/python3.10/site-packages/h5py/_hl/group.py", line 183, in create_dataset
    dsid = dataset.make_new_dset(group, shape, dtype, data, name, **kwds)
  File "/home/yongda1/.local/lib/python3.10/site-packages/h5py/_hl/dataset.py", line 166, in make_new_dset
    dset_id.write(h5s.ALL, h5s.ALL, data)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 282, in h5py.h5d.DatasetID.write
  File "h5py/_proxy.pyx", line 115, in h5py._proxy.dset_rw
OSError: [Errno 28] Can't synchronously write data (file write failed: time = Wed Mar 20 14:03:36 2024
, filename = '/tmp/tmp1b18gge_', file descriptor = 5, errno = 28, error message = 'No space left on device', buf = 0x2ba68f
a6e1d8, total write size = 1679452728, bytes this sub-write = 1679452728, bytes actually written = 18446744073709551615, of
fset = 0)


``` 
```python
#!/bin/bash
#SBATCH --account=***
#SBATCH --partition=short
#SBATCH --time=24:00:00
#SBATCH -J "***"       #JOB NAME
#SBATCH -N 1                  #NUMBER OF NODES
#SBATCH --ntasks-per-node=1  #NUMBER OF TASKS PER NODE
#SBATCH --cpus-per-task=1
#SBATCH -o test.%J.out        #STDOUT FILE, %J will be replaced by JOB_ID
#SBATCH -e test.%J.err        #STDERR FILE
#module load intel             #LOAD THE MPI ENVIRONMENT
module load Python/3.10.8-GCCcore-12.2.0
module load cuda/12.0.1
module load OpenMPI/4.1.4-GCC-12.2.0
module load OpenBLAS/0.3.21-GCC-12.2.0
#export MPICC= $(which mpicc)
export PYTHONPATH=/home/yongda1/software/pyscf:$PYTHONPATH
#mpirun python hBN.py > output
python hBN.py > output
exit

```

**Comment by fishjojo** [comment]
How many basis functions are there. The error is due to not enough disk space for storing the GDF integrals.

**Comment by Yongda1** [comment]
Thanks. I am using cc-PVQZ.

**Comment by verena-neufeld** [comment]
Hi @Yongda1 , thanks! Has your question been answered or should this issue stay open?

**Comment by sunqm** [comment]
The error is due to the limited size of the disk for temporary files. Please set the environment `TMPDIR=/path/to/scratch/` or `PYSCF_TMPDIR=/path/to/scratch` to change the location for temporary storage.

**Comment by Yongda1** [comment]
Thanks.
