### ISSUE TITLE
Time reversal symmetry not working

### ISSUE THREAD

**Issue by efertitta** [pyscf/pyscf#2155]
I noticed a potential bug when using time reversal symmetry

When constructing the kpoints with `cell.make_kpts` and using `time_reversal_symmetry=True` I get the following error:
```
Traceback (most recent call last):
  File "/cluster/projects/nn8040k/SEP-QUEST/BIGMAP/LiCoO2/KPOINTS/FORGEORGE/Imag_Fmatrix/Time_reversal/Embedding.py", line 34, in <module>
    mf.kernel()
  File "<string>", line 2, in kernel
  File "/cluster/home/edoardof/.local/lib/python3.11/site-packages/pyscf/scf/hf.py", line 1685, in scf
    kernel(self, self.conv_tol, self.conv_tol_grad,
  File "/cluster/home/edoardof/.local/lib/python3.11/site-packages/pyscf/scf/hf.py", line 128, in kernel
    vhf = mf.get_veff(mol, dm)
          ^^^^^^^^^^^^^^^^^^^^
  File "/cluster/home/edoardof/.local/lib/python3.11/site-packages/pyscf/pbc/scf/khf.py", line 629, in get_veff
    vj, vk = self.get_jk(cell, dm_kpts, hermi, kpts, kpts_band)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/home/edoardof/.local/lib/python3.11/site-packages/pyscf/pbc/scf/khf_ksymm.py", line 248, in get_jk
    vj, vk = self.with_df.get_jk(dm_kpts, hermi, kpts.kpts, kpts_band,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/home/edoardof/.local/lib/python3.11/site-packages/pyscf/pbc/df/df.py", line 434, in get_jk
    vk = df_jk.get_k_kpts(self, dm, hermi, kpts, kpts_band, exxdiv)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/home/edoardof/.local/lib/python3.11/site-packages/pyscf/pbc/df/df_jk.py", line 178, in get_k_kpts
    mydf.build(kpts_band=kpts_band)
  File "/cluster/home/edoardof/.local/lib/python3.11/site-packages/pyscf/pbc/df/df.py", line 259, in build
    self._make_j3c(self.cell, self.auxcell, None, cderi)
  File "/cluster/home/edoardof/.local/lib/python3.11/site-packages/pyscf/pbc/df/df.py", line 275, in _make_j3c
    kpts_union = unique(numpy.vstack([self.kpts, self.kpts_band]))[0]
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/home/edoardof/.local/lib/python3.11/site-packages/numpy/core/shape_base.py", line 289, in vstack
    return _nx.concatenate(arrs, 0, dtype=dtype, casting=casting)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

As shown in the error, in `pyscf/pbc/df/df.py` at line 275 `kpts_union = unique(numpy.vstack([self.kpts, self.kpts_band]))[0]` is called which is supposed to stack the two arrays `self.kpts` and `self.kpts_band`
However if `time_reversal_symmetry` is called upon in `cell.make_kpts`, `self.kpts` is created via a different library (`pyscf.pbc.lib.kpts.make_kpts`, see line 921 of `pyscf/pbc/gto/cell.py`) which returns a `KPoints` class object rather than an array
I tried to add just this one line above line 275 in `pyscf/pbc/df/df.py`:
`self.kpts = self.kpts.kpts`

This calls for the kpts array stored in the `KPoints` object and everything runs smoothly and `time_reversal_symmetry` is kept

Can this be fixed in a similar way in the source code? Thanks

**Comment by obackhouse** [comment]
could this be solved in a more general fashion by adding
```
def __array__(self):
    return self.kpts
```
to the `KPoints` class? Perhaps there may be unintended consequences due to the obvious loss of information here.

**Comment by fishjojo** [comment]
Hi @efertitta, what version of PySCF were you using? Thanks.

**Comment by efertitta** [comment]
Hi @fishjojo, the issue occurred both in 2.3.0 and 2.5.0

**Comment by verena-neufeld** [comment]
Hi @efertitta , thanks! @efertitta and @fishjojo is this resolved now?
