### ISSUE TITLE
Hessian for ROHF

### ISSUE THREAD

**Issue by cychow2** [pyscf/pyscf#2250]
Hi!

I was trying to compute the Hessian with ROHF for a molecule by
```python
import pyscf.gto
import pyscf.scf


mol = pyscf.gto.Mole()
mol.atom = "mol_relaxed.xyz"
mol.basis = {"C": "cc-pvdz", "H": "cc-pvdz", "O": "cc-pvdz", "Co": "cc-pvdz"}
mol.verbose = 4
mol.charge = 2
mol.spin = 3
mol.build()


mf = pyscf.scf.ROHF(mol).x2c().density_fit()
mf.run()

hessian = mf.Hessian().kernel()
```

However, I got the error
```
Traceback (most recent call last):
  File "/projects/research/smm/vibrational_modes.py", line 19, in <module>
    hessian = mf.Hessian().kernel()
              ^^^^^^^^^^^^^^^^^^^^^
  File "/projects/.conda/envs/pyscf/lib/python3.11/site-packages/pyscf/hessian/rhf.py", line 593, in kernel
    de = self.hess_elec(mo_energy, mo_coeff, mo_occ, atmlst=atmlst)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/projects/.conda/envs/pyscf/lib/python3.11/site-packages/pyscf/hessian/uhf.py", line 52, in hess_elec
    de2 = hessobj.partial_hess_elec(mo_energy, mo_coeff, mo_occ, atmlst,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/projects/.conda/envs/pyscf/lib/python3.11/site-packages/pyscf/df/hessian/uhf.py", line 45, in partial_hess_elec
    e1, ej, ek = _partial_hess_ejk(hessobj, mo_energy, mo_coeff, mo_occ,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/projects/.conda/envs/pyscf/lib/python3.11/site-packages/pyscf/df/hessian/uhf.py", line 61, in _partial_hess_ejk
    nao, nmo = mo_coeff[0].shape
    ^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)
```

Upon investigating the source code, I noticed that the following function in `pyscf/df/df_jk.py` seems to create a UHF Hessian object for an ROHF mf object, which probably leads to the above shape error because an ROHF `mo_coeff` array is only 2-dimensional, unlike a UHF `mo_coeff` array that has an extra dimension for alpha and beta spins.
```python
def Hessian(self):
        from pyscf.df.hessian import rhf, uhf, rks, uks
        if isinstance(self, (scf.uhf.UHF, scf.rohf.ROHF)):
            if isinstance(self, scf.hf.KohnShamDFT):
                return uks.Hessian(self)
            else:
                return uhf.Hessian(self)
        elif isinstance(self, scf.rhf.RHF):
            if isinstance(self, scf.hf.KohnShamDFT):
                return rks.Hessian(self)
            else:
                return rhf.Hessian(self)
        else:
            raise NotImplementedError
```

Is this a bug and is there an easy workaround?
Thanks!

**Comment by sunqm** [comment]
This is a bug.

**Comment by sunqm** [comment]
ROHF Hessian was disabled by PR #2259. If you’d like to access this feature in PySCF, feel free to reopen the issue and add the "feature request" label.
