### ISSUE TITLE
pyscf 2.6.0 does not work

### ISSUE THREAD

**Issue by susilehtola** [pyscf/pyscf#2272]
Trying to run a straightforward DFT calculation in pyscf 2.6.0 leads to failure
```
Traceback (most recent call last):
  File "/usr/lib64/python3.12/ctypes/__init__.py", line 450, in __getattr__
    dll = self._dlltype(name)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/ctypes/__init__.py", line 379, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: libpbc.so: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/qtp02.py", line 15, in <module>
    mol = pyscf.M(
          ^^^^^^^^
  File "/usr/lib64/python3.12/site-packages/pyscf/__init__.py", line 108, in M
    from pyscf import __all__
  File "/usr/lib64/python3.12/site-packages/pyscf/__all__.py", line 2, in <module>
    from .post_scf import *  # noqa: F403
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/site-packages/pyscf/post_scf.py", line 1, in <module>
    from . import mp, ci, cc, mcscf, fci, tdscf
  File "/usr/lib64/python3.12/site-packages/pyscf/tdscf/__init__.py", line 21, in <module>
    from pyscf.tdscf import ghf
  File "/usr/lib64/python3.12/site-packages/pyscf/tdscf/ghf.py", line 27, in <module>
    from pyscf import dft
  File "/usr/lib64/python3.12/site-packages/pyscf/dft/__init__.py", line 29, in <module>
    from pyscf.dft import libxc
  File "/usr/lib64/python3.12/site-packages/pyscf/dft/libxc.py", line 32, in <module>
    from pyscf.dft import xc_deriv
  File "/usr/lib64/python3.12/site-packages/pyscf/dft/xc_deriv.py", line 28, in <module>
    libdft = lib.load_library('libdft')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/site-packages/pyscf/lib/misc.py", line 93, in load_library
    return numpy.ctypeslib.load_library(libname, _loaderpath)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/site-packages/numpy/ctypeslib.py", line 158, in load_library
    return ctypes.cdll[libpath]
           ~~~~~~~~~~~^^^^^^^^^
  File "/usr/lib64/python3.12/ctypes/__init__.py", line 457, in __getitem__
    return getattr(self, name)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/ctypes/__init__.py", line 452, in __getattr__
    raise AttributeError(name)
AttributeError: /usr/lib64/python3.12/site-packages/pyscf/lib/libdft.so. Did you mean: '/usr/lib64/python3.12/site-packages/pyscf/lib/libcc.so'?
```
due to the added dependency on libpbc in libdft. The issue can be resolved by loading libpbc before libdft.

**Comment by sunqm** [comment]
I'll close this issue now, as the RPATH setting is typically not a concern when installing the PySCF package via pip, conda, or by following the installation manual https://pyscf.org/install.html
