### ISSUE TITLE
CASSCF wfnsym not consistent during iteration

### ISSUE THREAD

**Issue by Lex-Y-Darkblade** [pyscf/pyscf#2383]
I'm tring to use symmetry adapted CASSCF to scan an energy curve of a carbon dimer. Yet with a slightly larger bond length, the SCF iteration always raises a RuntimeError. Here are my code and the output:

```
from pyscf import gto, scf, mcscf
import numpy as np


mol = gto.M(
    atom = """
    C 0 0 0
    C 0 0 1.66
    """, 
    basis = "def2-qzvppd",
    spin = 0,
    charge = 0,
    unit = "angstrom",
    symmetry = True
    )

mf = mol.RHF()
mf.irrep_nelec = { 'A1g': 4, 'A1u': 4, 'E1gx': 2, 'E1gy': 2}
mf.verbose = 4
mf.kernel()

mc = mcscf.CASSCF(mf, 10, 8)
mc.verbose = 4
mc.max_cycle_macro = 300
mc.fix_spin_(ss=0.00)
mc.fcisolver.wfnsym = 'A1g'
ncore = { "A1g":1, "A1u":1, }
ncas = { "A1g":3, "A1u":3, "E1gx":1, "E1gy":1, "E1ux":1, "E1uy":1, }
mo = mcscf.sort_mo_by_irrep(mc, mf.mo_coeff, ncas, ncore)
mc.kernel(mo)
```

> ******** <class 'pyscf.scf.hf_symm.SymAdaptedRHF'> ********
> method = SymAdaptedRHF
> initial guess = minao
> damping factor = 0
> 
> level_shift factor = 0
> DIIS = <class 'pyscf.scf.diis.CDIIS'>
> diis_start_cycle = 1
> diis_space = 8
> diis_damp = 0
> SCF conv_tol = 1e-09
> SCF conv_tol_grad = None
> SCF max_cycles = 50
> direct_scf = True
> direct_scf_tol = 1e-13
> chkfile to save SCF result = /tmp/tmpzpqezuo5
> max_memory 4000 MB (current use 105 MB)
> Set gradient conv threshold to 3.16228e-05
> Initial guess from minao.
> init E= -74.9299059852803
> HOMO (E1gy) = 0.050068269107646  LUMO (A1g) = -0.155906517926889
> 
> WARN: A1g LUMO -0.155906517926889 < system HOMO 0.050068269107646
> 
> 
> WARN: E1gx HOMO 0.050068269107646 > system LUMO -0.155906517926889
> 
> 
> WARN: E1gy HOMO 0.050068269107646 > system LUMO -0.155906517926889
> 
> cycle= 1 E= -74.5038287665031  delta_E= 0.426  |g|= 0.524  |ddm|=  1.4
> HOMO (E1gy) = -0.345778051583188  LUMO (E1ux) = -0.287251936443513
> cycle= 2 E= -74.6177971031156  delta_E= -0.114  |g|= 0.252  |ddm|= 0.728
> HOMO (E1gy) = -0.241120165473605  LUMO (E1ux) = -0.152577905330979
> cycle= 3 E= -74.6326856325605  delta_E= -0.0149  |g|= 0.0358  |ddm|= 0.226
> HOMO (E1gy) = -0.228741193884975  LUMO (E1ux) = -0.133157848012872
> cycle= 4 E= -74.6332048322451  delta_E= -0.000519  |g|= 0.00432  |ddm|= 0.116
> HOMO (E1gy) = -0.228646788857981  LUMO (E1ux) = -0.132999124953633
> cycle= 5 E= -74.6332209680164  delta_E= -1.61e-05  |g|= 0.000602  |ddm|= 0.0239
> HOMO (E1gy) = -0.22856433122238  LUMO (E1ux) = -0.132929901304751
> cycle= 6 E= -74.6332211912459  delta_E= -2.23e-07  |g|= 0.000134  |ddm|= 0.00164
> HOMO (E1gy) = -0.228566474114761  LUMO (E1ux) = -0.132923681539384
> cycle= 7 E= -74.6332212032463  delta_E= -1.2e-08  |g|= 2.38e-05  |ddm|= 0.000185
> HOMO (E1gy) = -0.228564946508847  LUMO (E1ux) = -0.132922816352848
> cycle= 8 E= -74.6332212035689  delta_E= -3.23e-10  |g|= 3.06e-06  |ddm|= 5.97e-05
> HOMO (E1gy) = -0.228565339090271  LUMO (E1ux) = -0.132923431317173
> Extra cycle  E= -74.6332212035738  delta_E= -4.89e-12  |g|= 9.92e-07  |ddm|= 7.77e-06
> converged SCF energy = -74.6332212035738
> ncore for each irreps {'A1g': 1, 'A1u': 1}
> ncas for each irreps {'A1g': 3, 'A1u': 3, 'E1gx': 1, 'E1gy': 1, 'E1ux': 1, 'E1uy': 1}
> (0-based) caslst = [ 2  3  4  5  6  7  8  9 10 18]
> 
> ******** <class 'pyscf.mcscf.mc1step_symm.SymAdaptedCASSCF'> ********
> CAS (4e+4e, 10o), ncore = 2, nvir = 114
> max_cycle_macro = 300
> max_cycle_micro = 4
> conv_tol = 1e-07
> conv_tol_grad = None
> orbital rotation max_stepsize = 0.02
> orbital rotation threshold for CI restart = 0.01
> augmented hessian ah_max_cycle = 30
> augmented hessian ah_conv_tol = 1e-12
> augmented hessian ah_linear dependence = 1e-14
> augmented hessian ah_level shift = 1e-08
> augmented hessian ah_start_tol = 2.5
> augmented hessian ah_start_cycle = 3
> augmented hessian ah_grad_trust_region = 3
> kf_trust_region = 3
> kf_interval = 4
> ci_response_space = 4
> ci_grad_trust_region = 3
> with_dep4 0
> natorb = False
> canonicalization = True
> sorting_mo_energy = False
> ao2mo_level = 2
> chkfile = /tmp/tmpzpqezuo5
> max_memory 4000 MB (current use 435 MB)
> internal_rotation = False
> ******** <class 'pyscf.fci.addons.SpinPenaltyFCISolver'> ********
> max. cycles = 50
> conv_tol = 1e-08
> davidson only = True
> linear dependence = 1e-12
> level shift = 0.001
> max iter space = 12
> max_memory 4000 MB
> nroots = 1
> pspace_size = 400
> spin = None
> Input CI wfn symmetry = A1g
> Symmetries of active orbitals: A1g A1u E1gx E1gy E1uy E1ux A1g A1u A1g A1u
> Active space CI wfn symmetry = A1g
> CASCI E = -75.4545926073472  S^2 = 0.0000000
> Set conv_tol_grad to 0.000316228
> macro iter   1 ( 21 JK    4 micro), CASSCF E = -75.5170185710947  dE = -6.24259637e-02  S^2 = 0.0000000
>                |grad[o]|=0.244  |grad[c]|=0.0573  |ddm|=0.118  |maxRot[o]|=0.313
> macro iter   2 ( 21 JK    4 micro), CASSCF E = -75.5400794819328  dE = -2.30609108e-02  S^2 = 0.0000000
>                |grad[o]|=0.118  |grad[c]|=0.0226  |ddm|=0.0345  |maxRot[o]|=0.314
> macro iter   3 ( 21 JK    4 micro), CASSCF E = -75.5499509498548  dE = -9.87146792e-03  S^2 = 0.0000000
>                |grad[o]|= 0.05  |grad[c]|=0.016  |ddm|=0.0112  |maxRot[o]|=0.275
> macro iter   4 ( 21 JK    4 micro), CASSCF E = -75.5538055301204  dE = -3.85458027e-03  S^2 = 0.0000000
>                |grad[o]|=0.0179  |grad[c]|=0.00683  |ddm|=0.016  |maxRot[o]|=0.301
> macro iter   5 ( 15 JK    4 micro), CASSCF E = -75.5543453995065  dE = -5.39869386e-04  S^2 = 0.0000000
>                |grad[o]|=0.0197  |grad[c]|=0.00371  |ddm|=0.0232  |maxRot[o]|=0.0635
> macro iter   6 ( 15 JK    4 micro), CASSCF E = -75.5545582699969  dE = -2.12870490e-04  S^2 = 0.0000000
>                |grad[o]|=0.015  |grad[c]|=0.00211  |ddm|=0.0258  |maxRot[o]|=0.0315
> Traceback (most recent call last):
>   File "/home/lexlee/2024-08-U2/test.py", line 30, in <module>
>     mc.kernel(mo)
>   File "/home/lexlee/.local/lib/python3.9/site-packages/pyscf/mcscf/mc1step_symm.py", line 73, in kernel
>     _kern(self, mo_coeff,
>   File "/home/lexlee/.local/lib/python3.9/site-packages/pyscf/mcscf/mc1step.py", line 454, in kernel
>     e_tot, e_cas, fcivec = casscf.casci(mo, fcivec, eris, log, locals())
>   File "/home/lexlee/.local/lib/python3.9/site-packages/pyscf/mcscf/mc1step.py", line 878, in casci
>     e_tot, e_cas, fcivec = casci.kernel(fcasci, mo_coeff, ci0, log,
>   File "/home/lexlee/.local/lib/python3.9/site-packages/pyscf/mcscf/casci.py", line 608, in kernel
>     e_tot, fcivec = casci.fcisolver.kernel(h1eff, eri_cas, ncas, nelecas,
>   File "/home/lexlee/.local/lib/python3.9/site-packages/pyscf/fci/direct_spin1_symm.py", line 767, in kernel
>     wfnsym_ir = self.guess_wfnsym(norb, nelec, ci0, orbsym, wfnsym, **kwargs)
>   File "/home/lexlee/.local/lib/python3.9/site-packages/pyscf/fci/direct_spin1_symm.py", line 585, in guess_wfnsym
>     raise RuntimeError(f'Input wfnsym {wfnsym} is not consistent with '
> RuntimeError: Input wfnsym A1g is not consistent with fcivec symmetry 1

I have read the examples about symmetry adapted CASSCF but I still don't know what should I do to fix that. I really appreciate for the help, thanks!

**Comment by Lex-Y-Darkblade** [comment]
The problem has been fixed by [#2395](https://github.com/pyscf/pyscf/pull/2395), thanks!
