### ISSUE TITLE
SOC example gives error

### ISSUE THREAD

**Issue by simonganne01** [pyscf/pyscf#2436]
Hello Everyone, 

I get the following error when I run example examples/pbc/33-soc_integrals.py. Apparently there is a function deprecated. But what function should I use instead?

`
WARN: Function deprecated. Call pbc.df.gdf_builder.estimate_ke_cutoff_for_eta instead.

/usr/local/lib/python3.10/dist-packages/pyscf/gto/mole.py:1286: UserWarning: Function mol.dumps drops attribute _mesh because it is not JSON-serializable
  warnings.warn(msg)
Traceback (most recent call last):
  File "/home/simon/PySCF/examples/soc.py", line 125, in <module>
    soc_pbc = get_pbc_pvxp(cell)
  File "/home/simon/PySCF/examples/soc.py", line 93, in get_pbc_pvxp
    soc_mat = mydf._int_nuc_vloc(nuccell, kpts_lst, 'int3c2e_pvxp1_sph',
  File "/usr/local/lib/python3.10/dist-packages/pyscf/pbc/df/aft.py", line 180, in _int_nuc_vloc
    raise DeprecationWarning
DeprecationWarning`

**Comment by lzwlewis** [comment]
Hi,
To my limited knowledge, you may refer to this new function [https://github.com/pyscf/pyscf/blob/master/pyscf/pbc/x2c/x2c1e.py#L200](url) and this paper [https://arxiv.org/abs/2302.11307](url) for more information.

**Comment by sunqm** [comment]
Please refer to the relevant implementation 
 https://github.com/pyscf/pyscf/blob/a0665c4a7bf54e33f01295b3eea390be7a17d76d/pyscf/pbc/x2c/x2c1e.py#L220
