### ISSUE TITLE
error recovering Fock matrix after COSMO calculation

### ISSUE THREAD

**Issue by kvkarandashev** [pyscf/pyscf#2447]
The following script successfully prints out the exchange and Coulomb matrices observed after a Hartree-Fock + COSMO calculation, but fails to do so for the Fock matrix:
```
from pyscf import M
from pyscf.solvent import DDCOSMO

mol = M(atom="H 0. 0. 0.; H 0. 0. 1.")
mf = mol.RHF()

cosmo_mf = DDCOSMO(mf)
cosmo_mf.with_solvent.eps = 78.4

cosmo_mf.run()

# this works
print(cosmo_mf.get_k())
print(cosmo_mf.get_j())
# this does not work
print(cosmo_mf.get_fock())
```
The output is:
```
converged SCF energy = -1.06630467027465
[[1.03648882 0.83831468]
 [0.83831468 1.03648882]]
[[1.25044062 0.62436288]
 [0.62436288 1.25044062]]
Traceback (most recent call last):
  File "/home/konst/test_folder/pyscf/solvation/minimal_example.py", line 16, in <module>
    print(cosmo_mf.get_fock())
          ^^^^^^^^^^^^^^^^^^^
  File "/home/konst/miniconda3/lib/python3.12/site-packages/pyscf/solvent/_attach_solvent.py", line 100, in get_fock
    vhf = self.get_veff(self.mol, dm)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/konst/miniconda3/lib/python3.12/site-packages/pyscf/solvent/_attach_solvent.py", line 85, in get_veff
    with_solvent.e, with_solvent.v = with_solvent.kernel(dm)
                                     ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/konst/miniconda3/lib/python3.12/site-packages/pyscf/solvent/ddcosmo.py", line 773, in kernel
    self.e, self.v = self._get_vind(dm)
                     ^^^^^^^^^^^^^^^^^^
  File "/home/konst/miniconda3/lib/python3.12/site-packages/pyscf/solvent/ddcosmo.py", line 800, in _get_vind
    dm = dm[0] + dm[1]
         ~~^^^
TypeError: 'NoneType' object is not subscriptable
```

**Comment by kvkarandashev** [comment]
> It can be solved by passing the dm to the get_fock function like this. print(cosmo_mf.get_fock(dm=cosmo_mf.make_rdm1()))

Thank you for the quick reply! It should do as a temporary solution for now.

**Comment by tberkel** [comment]
Thanks both. If these seems like a bug, please feel free to submit a PR.

**Comment by JangidBhavnesh** [comment]
Sure.
 I will add this.
