### ISSUE TITLE
Restarting calculation fails in this case with multigrid

### ISSUE THREAD

**Issue by computative** [pyscf/pyscf#2468]
I am trying to perform gradients calculation on a laptop based on a rks-calculation that happened on a cluster. My script simulates this by first fitting with the `RKS` object `nf` which saves a chk-file (this is the simulated cluster). Then make a new rks-object called `mf` where I read in the chk-file and do not invoke the mf.kernel (this is the simulated laptop). This way I can calculate the gradient on the laptop based on what the cluster did. But this fails because of `AttributeError`. I tried to do a workaround to fix the problem.

```
import numpy 
import pyscf
from pyscf.pbc import gto, dft
from pyscf import data
import numpy as np
from pyscf.pbc.dft import numint, multigrid


# change this path to whatever you want
chkpath = '/path/to/chkfile/name.chk'


cell = gto.Cell()
cell.a = '''
3.5668  0       0
0       3.5668  0
0       0       3.5668'''
cell.atom = '''C     0.      0.      0.    
              C     0.8917  0.8917  0.8917
              C     1.7834  1.7834  0.    
              C     2.6751  2.6751  0.8917
              C     1.7834  0.      1.7834
              C     2.6751  0.8917  2.6751
              C     0.      1.7834  1.7834
              C     0.8917  2.6751  2.6751'''

cell.verbose = 5
cell.basis = 'gth-szv'
cell.pseudo = "gth-pade"

cell.ke_cutoff = 500  # kinetic energy cutoff in a.u.
cell.precision = 1e-6
cell.use_loose_rcut = True # integral screening based on shell radii
cell.use_particle_mesh_ewald = True # use particle mesh ewald for nuclear repulsion
cell.build()


nf = dft.RKS(cell)
nf.xc = "LDA, VWN"
nf.chkfile = chkpath
nf.conv_tol = 1e-8
nf.with_df = multigrid.MultiGridFFTDF2(cell)
nf.with_df.ngrids = 4 # number of sets of grid points
nf.kernel()
nf.dump_scf_summary()

"""
This works...
"""
from pyscf.pbc.grad import rks as rks_grad
grad = rks_grad.Gradients(nf)
grad.kernel()

"""
...but after reading in the ao_coeffs from chk, ...
"""

mf = dft.RKS(cell)
mf.conv_tol = 1e-8
mf.with_df = multigrid.MultiGridFFTDF2(cell)
mf.with_df.ngrids = 4 # number of sets of grid points
mf.xc = "LDA, VWN"
mf.__dict__.update(pyscf.pbc.scf.chkfile.load(chkpath, 'scf'))
mf.converged = True

"""
... I get unwanted behaviour
"""

grad = rks_grad.Gradients(mf)
g = grad.kernel()
```

This is the traceback I am getting.

```
Traceback (most recent call last):
  File "~/Desktop/scipt.py", line 93, in <module>
    g = grad.kernel()
        ^^^^^^^^^^^^^
  File "~/Programs/anaconda3/lib/python3.11/site-packages/pyscf/grad/rhf.py", line 415, in kernel
    de = self.grad_elec(mo_energy, mo_coeff, mo_occ, atmlst)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/Programs/anaconda3/lib/python3.11/site-packages/pyscf/pbc/grad/rhf.py", line 61, in grad_elec
    h1ao += -mf.with_df.get_vpploc_part1_ip1(kpts=kpt.reshape(-1,3))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'MultiGridFFTDF2' object has no attribute 'get_vpploc_part1_ip1'
```

The workaround I attempted to use is to read in a value for `vpplocG_part1` from a h5-file that I got from the first calculation (`nf.with_df-instance`), and set it to that value after loading the chk-file in the `mf`-instance.
```
setattr(mf.with_df, "vpplocG_part1", array)
```

Here is the workaround in action:

```
import numpy 
import pyscf
from pyscf.pbc import gto, dft
from pyscf import data
import numpy as np
from pyscf.pbc.dft import numint, multigrid


# change this path to whatever you want
chkpath = '/path/to/chkfile/name.chk'

def chkappend(path, group, key, array):
    import h5py
    try:
        with h5py.File(path, "a") as hdf:
            try:
                del hdf[f"{group}/{key}"]
            finally:
                hdf.create_dataset(f"{group}/{key}", data=array)
    except ValueError:
        print("WARN: Unable to append {key} to {group}. Perhaps {path} doesn't exist")


cell = gto.Cell()
cell.a = '''
3.5668  0       0
0       3.5668  0
0       0       3.5668'''
cell.atom = '''C     0.      0.      0.    
              C     0.8917  0.8917  0.8917
              C     1.7834  1.7834  0.    
              C     2.6751  2.6751  0.8917
              C     1.7834  0.      1.7834
              C     2.6751  0.8917  2.6751
              C     0.      1.7834  1.7834
              C     0.8917  2.6751  2.6751'''

cell.verbose = 5
cell.basis = 'gth-szv'
cell.pseudo = "gth-pade"

cell.ke_cutoff = 500  # kinetic energy cutoff in a.u.
cell.precision = 1e-6
cell.use_loose_rcut = True # integral screening based on shell radii
cell.use_particle_mesh_ewald = True # use particle mesh ewald for nuclear repulsion
cell.build()


nf = dft.RKS(cell)
nf.xc = "LDA, VWN"
nf.chkfile = chkpath
nf.conv_tol = 1e-8
nf.with_df = multigrid.MultiGridFFTDF2(cell)
nf.with_df.ngrids = 4 # number of sets of grid points
nf.kernel()
nf.dump_scf_summary()

"""
This works...
"""
from pyscf.pbc.grad import rks as rks_grad
grad = rks_grad.Gradients(nf)
grad.kernel()

"""
...but after reading in the ao_coeffs from chk, ...
"""

mf = dft.RKS(cell)
mf.conv_tol = 1e-8
mf.with_df = multigrid.MultiGridFFTDF2(cell)
mf.with_df.ngrids = 4 # number of sets of grid points
mf.xc = "LDA, VWN"
mf.__dict__.update(pyscf.pbc.scf.chkfile.load(chkpath, 'scf'))
for attr, value in pyscf.pbc.scf.chkfile.load(chkpath, 'with_df').items():
    setattr(mf.with_df, attr, value)
mf.converged = True


"""
... now this works
"""

grad = rks_grad.Gradients(mf)
g = grad.kernel()
```

**Comment by fishjojo** [comment]
Thanks. Restarting the calculation from a chkfile was not considered. I'll fix this in the next release.
