### ISSUE TITLE
Error of EOM-CC with AO direct method

### ISSUE THREAD

**Issue by JunboLu** [pyscf/pyscf#2491]
Dear developer:
  I am use AO direct EOM-CC to get the EA of relatively large system. The eom-cc code in my input script is:
mycc = cc.RCCSD(mf)
mycc.direct = True
mycc.ccsd()

eea,cea = mycc.eaccsd(nroots=1)

 But I get an error:
Traceback (most recent call last):
  File "/mnt/sg001/home/fz_sustech_ljb/WORK/lujb/embedding/UO22+/BASIS_SET_TEST/HL/AUG_CC_PVDZ/input.py", line 160, in <module>
    eea,cea = mycc.eaccsd(nroots=1)
  File "/mnt/sg001/home/fz_sustech_ljb/bin/pyscf-2.0.1/pyscf/cc/ccsd.py", line 1101, in eaccsd
    return eom_rccsd.EOMEA(self).kernel(nroots, left, koopmans, guess,
  File "/mnt/sg001/home/fz_sustech_ljb/bin/pyscf-2.0.1/pyscf/cc/eom_rccsd.py", line 599, in eaccsd
    return ipccsd(eom, nroots, left, koopmans, guess, partition, eris, imds)
  File "/mnt/sg001/home/fz_sustech_ljb/bin/pyscf-2.0.1/pyscf/cc/eom_rccsd.py", line 249, in ipccsd
    = kernel(eom, nroots, koopmans, guess, left, eris=eris, imds=imds)
  File "/mnt/sg001/home/fz_sustech_ljb/bin/pyscf-2.0.1/pyscf/cc/eom_rccsd.py", line 41, in kernel
    imds = eom.make_imds(eris)
  File "/mnt/sg001/home/fz_sustech_ljb/bin/pyscf-2.0.1/pyscf/cc/eom_rccsd.py", line 932, in make_imds
    imds.make_ea(self.partition)
  File "/mnt/sg001/home/fz_sustech_ljb/bin/pyscf-2.0.1/pyscf/cc/eom_rccsd.py", line 1825, in make_ea
    self.Wvvvv = imd.Wvvvv(t1, t2, eris)
  File "/mnt/sg001/home/fz_sustech_ljb/bin/pyscf-2.0.1/pyscf/cc/rintermediates.py", line 184, in Wvvvv
    Wabcd += np.asarray(_get_vvvv(eris)).transpose(0,2,1,3)
  File "/mnt/sg001/home/fz_sustech_ljb/bin/pyscf-2.0.1/pyscf/cc/rintermediates.py", line 233, in _get_vvvv
    elif eris.vvvv.ndim == 2:
AttributeError: 'NoneType' object has no attribute 'ndim'
  Could anyone give a help?
  With my best regards,
  Junbo

**Comment by tberkel** [comment]
Sorry, EOM-CC calculations do not currently support AO direct. Only ground-state CC supports AO direct.
