### ISSUE TITLE
ImportError with fuse_auxcell in mpi4pyscf PBC module 

### ISSUE THREAD

**Issue by hfranc** [pyscf/pyscf#2498]
I have been trying to run some examples from the mpi4pyscf documentation, specifically those using the PBC (periodic boundary conditions) module. The specific example is from the user guide: [(https://github.com/pyscf/mpi4pyscf/blob/1f6ff4e18b5c4270f2a0c515aeab7a4363f4a844/examples/01-parallel_krhf-diamond.py](url). Neither that example nor others seem to work, unfortunately with my implementation. I have installed PySCF 2.7.0 and mpi4pyscf 0.3.1 (including a recent patch fix [https://github.com/pyscf/mpi4pyscf/pull/33/files](url) ). My machine has OpenMPI 4.1.5 and the Intel 2023.2.0 compilers for parallel calculations.

$ procs=2 
$ mpirun -np ${procs} python 01-parallel_krhf-diamond.py

I get the following error regardless of the number of processes ($procs) specified:

 Traceback (most recent call last):
  File "/home/hifr/testing_pyscf/parallel_sol/01_diam.py", line 3, in <module>
    from mpi4pyscf.pbc import df
  File "/home/hifr/miniconda3/envs/py4vasp_env/lib/python3.12/site-packages/mpi4pyscf/pbc/__init__.py", line 2, in <module>
    from . import df
  File "/home/hifr/miniconda3/envs/py4vasp_env/lib/python3.12/site-packages/mpi4pyscf/pbc/df/__init__.py", line 1, in <module>
    from . import df
  File "/home/hifr/miniconda3/envs/py4vasp_env/lib/python3.12/site-packages/mpi4pyscf/pbc/df/df.py", line 18, in <module>
    from pyscf.pbc.df.df import fuse_auxcell, make_modrho_basis, unique
ImportError: cannot import name 'fuse_auxcell' from 'pyscf.pbc.df.df' (/home/hifr/pyscf/pyscf/pbc/df/df.py). Did you mean: 'make_auxcell'?

Could anyone provide guidance on resolving this issue? Thank you!

**Comment by gkc1000** [comment]
I think this is just because some name changes since the pyscf version number was changed. @fishjojo can you make that patch to change the name? Probably also, we should have mpi4pyscf tested on the github actions. @sunqm what do you think?

**Comment by fishjojo** [comment]
The pbc df module is outdated. Please try using `pyscf <= 2.0` for now.

**Comment by MNovotny2** [comment]
Hi, I just wanted to ask if there has been any progress on this, since I am experiencing the same problem in PySCF-2.8.0 and 
mpi4pyscf 0.3.1. The suggested solution (pyscf <= 2.0) is not ideal for me since I would like to utilize cell and k-point symmetry which are implemented only in the newer versions.
Thank you!

**Comment by fishjojo** [comment]
@MNovotny2 I will try to fix this once I have time. Hopefully next month.

**Comment by MNovotny2** [comment]
Thank you very much for the quick reply. Looking forward for the update.
