### ISSUE TITLE
AssertionError when I use analyze () function in state-average calculations

### ISSUE THREAD

**Issue by jamcas** [pyscf/pyscf#299]
Here is my code;
```
from pyscf import gto, scf, mcscf
mol = gto.M(atom="N 0 0 0; N 0 0 1", basis="ccpvdz")
mol.verbose = 4
mol.build()
mf = scf.RHF(mol).run()
mc = mcscf.CASSCF(mf, 6, 6)
mc.state_average_([0.5, 0.5])
mc.kernel()
mc.analyze()
Traceback (most recent call last):
  File "test.py", line 17, in <module>
    mc.analyze()
  File "/home/chenh/anaconda3/lib/python3.6/site-packages/pyscf/mcscf/casci.py", line 91, in analyze
    casdm1a, casdm1b = casscf.fcisolver.make_rdm1s(civec, ncas, nelecas)
  File "/home/chenh/anaconda3/lib/python3.6/site-packages/pyscf/mcscf/addons.py", line 650, in make_rdm1s
    dm1s = fcibase_class.make_rdm1s(self, ci0, norb, nelec, *args, **kwargs)
  File "/home/chenh/anaconda3/lib/python3.6/site-packages/pyscf/fci/direct_spin1.py", line 755, in make_rdm1s
    return make_rdm1s(fcivec, norb, nelec, link_index)
  File "/home/chenh/anaconda3/lib/python3.6/site-packages/pyscf/fci/direct_spin1.py", line 277, in make_rdm1s
    norb, nelec, link_index)
  File "/home/chenh/anaconda3/lib/python3.6/site-packages/pyscf/fci/rdm.py", line 101, in make_rdm1_spin1
    assert(cibra.size == na*nb)
AssertionError
```
I love this software and i also want to know how to get the occupations and CI coefficients of each state in dmrg state-average calculation.

**Comment by sunqm** [comment]
I'm not able to reproduce the error using the github head version. Which version do you see
```
python -c 'import pyscf; print(pyscf.__version__)'
```

**Comment by jamcas** [comment]
My version is 1.6.1. I just tried again, and the same problem came up.

**Comment by tberkel** [comment]
I also can't reproduce this error.  `cibra.size` and `na*nb` are both `400` when I run your example.  What do you get?  Can you include all of the output from your script, with high verbosity?  When cloning the latest version, did you also re-build?

**Comment by jamcas** [comment]
Maybe it was because I overwrote the original file directly when I upgraded, and the problem disappeared after I uninstalled and reinstalled the latest version.
