### ISSUE TITLE
RSH DFT failure

### ISSUE THREAD

**Issue by hebrewsnabla** [pyscf/pyscf#303]
I got an error when doing RSH DFT(wB97X-D, wB97X-V, MN15-SX, etc.). Error message is as follows.
```Traceback (most recent call last):
  File "eda_w3.py", line 10, in <module>  
    dmlist, submflist, coords, charges = gfea.run_pyscf(gjflist,verbose, max_memory, method)  
  File "/home/wsr/gfea/gfea.py", line 146, in run_pyscf
    submf.kernel()
  File "/home/wsr/pyscf/lib/misc.py", line 578, in aliased_fn
    return fn(*args, **kwargs)
  File "/home/wsr/pyscf/scf/hf.py", line 1476, in scf
    conv_check=self.conv_check, **kwargs)
  File "/home/wsr/pyscf/scf/hf.py", line 143, in kernel
    vhf = mf.get_veff(mol, dm)
  File "/home/wsr/pyscf/dft/rks.py", line 130, in get_veff
    vklr = _get_k_lr(mol, dm, omega, hermi)
  File "/home/wsr/pyscf/dft/rks.py", line 157, in _get_k_lr
    vklr = jk.get_jk(mol, dms, ['ijkl,jk->il']*len(dms))
  File "/home/wsr/pyscf/scf/jk.py", line 167, in get_jk
    vhfopt=vhfopt, shls_slice=shls_slice)
  File "/home/wsr/pyscf/scf/_vhf.py", line 361, in direct_bindm
    assert(dms[i].shape == get_dims(dmsym, shls_slice, ao_loc))
AssertionError
```
It seems that only RSH XC will trigger `dms[i].shape == get_dims(dmsym, shls_slice, ao_loc)` failure  in _vhf.py, which comes from `_get_k_lr` in rks.py. However, this routine does not contain anything related to XC functional itself. So maybe something goes wrong in `direct_bindm` or `get_dims(dmsym, shls_slice, ao_loc)`.
My test example is a tripeptide, using 6-31G(d,p) basis. Very small molecule and very small basis won't trigger the error above.

**Comment by sunqm** [comment]
This is fixed in latest updates 277bb2c
