### ISSUE TITLE
Error in parsing last element in some basis sets

### ISSUE THREAD

**Issue by markdewing** [pyscf/pyscf#380]
Some basis sets contain an ECP section after the all-electron basis sets.   The splitting in parse_nwchem.py includes this section when selecting the final atom in the basis, and this results in a parse error.

Reproducer:
```
from pyscf import gto,scf

mol = gto.M(atom='Rn 0 0 0', basis='def2-svp')
```
Error:
```
Traceback (most recent call last):
  File "simple_repo.py", line 4, in <module>
    mol = gto.M(atom='Rn 0 0 0', basis='def2-svp')
  File "/home/physics/codes/pyscf/pyscf/pyscf/gto/mole.py", line 93, in M
    mol.build(**kwargs)
  File "/home/physics/codes/pyscf/pyscf/pyscf/gto/mole.py", line 2075, in build
    self._basis = self.format_basis(_basis)
  File "/home/physics/codes/pyscf/pyscf/pyscf/gto/mole.py", line 2166, in format_basis
    return format_basis(basis_tab)
  File "/home/physics/codes/pyscf/pyscf/pyscf/gto/mole.py", line 390, in format_basis
    bset = convert(str(atom_basis), stdsymb)
  File "/home/physics/codes/pyscf/pyscf/pyscf/gto/mole.py", line 378, in convert
    return basis.load(basis_name, symb)
  File "/home/physics/codes/pyscf/pyscf/pyscf/gto/basis/__init__.py", line 437, in load
    b = parse_nwchem.load(os.path.join(_BASIS_DIR, basmod), symb, optimize)
  File "/home/physics/codes/pyscf/pyscf/pyscf/gto/basis/parse_nwchem.py", line 101, in load
    return _parse(search_seg(basisfile, symb), optimize)
  File "/home/physics/codes/pyscf/pyscf/pyscf/gto/basis/parse_nwchem.py", line 226, in _parse
    key = dat.split()[1]
IndexError: list index out of range
```

One possible fix is to include END in the BASIS_SET_DELIMITER regex in parse_nwchem.py
```
BASIS_SET_DELIMITER = re.compile('# *BASIS SET.*\n|END\n')
```

**Comment by sunqm** [comment]
Thanks for the suggestion of possible fix. Included in the latest commit.
