### ISSUE TITLE
TypeError during the Qmmm-CASCI calculation

### ISSUE THREAD

**Issue by jamcas** [pyscf/pyscf#391]
```
from pyscf import gto, dft, mcscf, qmmm, dmrgscf
mol = gto.M(atom="H 0 0 0; F 0 0 1", basis="ccpvdz",verbose=4)
mol.build()

mf = dft.RKS(mol)
mf.xc = 'b3lyp'
mf.__dict__.update(lib.chkfile.load('test.chk', 'scf')

mc = mcscf.CASCI(mf, 4, 4)
mc.fcisolver = dmrgscf.DMRGCI(mol)
mc = qmmm.mm_charge(mc, [(0.5,0.6,0.8)], [-0.3])
mc.kernel()

Traceback (most recent call last):
  File "test.py", line 34, in <module>
    mc.kernel()
  File "/home/chenh/anaconda3/lib/python3.6/site-packages/pyscf/mcscf/casci.py", line 809, in kernel
    self.dump_flags(log)
TypeError: dump_flags() takes 1 positional argument but 2 were given
```

**Comment by sunqm** [comment]
Fixed in 47b54c1
