### ISSUE TITLE
2rdm memory error 

### ISSUE THREAD

**Issue by BogdanRutskoy** [pyscf/pyscf#442]
Dear pyscf delelopers,

I try to calculate of second order reduced density matrix by lambda-CCSD(T) method for dimer methane in cc-pvdz basis set. I use this code:
 https://github.com/pyscf/pyscf/blob/master/pyscf/cc/ccsd_t_rdm_slow.py#L115
 
but I get messege about error:

Traceback (most recent call last):
  File "./CH4_vdz_bf.inp", line 193, in <module>
    l1, l2 = ccsd_t_lambda.kernel(mcc, eris, t1, t2)[1:]
  File "/usr/pyscf/pyscf/cc/ccsd_t_lambda_slow.py", line 40, in kernel
    verbose, make_intermediates, update_lambda)
  File "/usr/pyscf/pyscf/cc/ccsd_lambda.py", line 51, in kernel
    imds = fintermediates(mycc, t1, t2, eris)
  File "/usr/pyscf/pyscf/cc/ccsd_t_lambda_slow.py", line 66, in make_intermediates
    + numpy.einsum('ck,ijab->ijkabc', eris.fock[nocc:,:nocc], t2)) / d3
MemoryError

Could you asnswer me? Is this problem concerned with small memory of device or is this bug?

**Comment by sunqm** [comment]
The MemoryError means the code failed to allocated a huge memory. ccsd_t_rdm_slow is just the slow version to provide a reference of  of ccsd(t) density matrices. It's not optimized for memory footprint and CPU cost . This implementation allocates a 6D tensor to hold t3 amplitudes which causes huge memory consumption.
