### ISSUE TITLE
mol.build() fails with symmetry in index error

### ISSUE THREAD

**Issue by susilehtola** [pyscf/pyscf#452]
```
from pyscf import gto

mol = gto.Mole()
mol.build(
        atom = '''
Fe 0.000000 0.000000 0.015198 
C 0.000000 0.000000 -1.938396 
C 0.000000 -1.394127 -1.614155 
C -1.207349 0.697064 -1.614155 
C 1.207349 0.697064 -1.614155 
H -0.922915 -1.965174 -1.708739 
H 0.922915 -1.965174 -1.708739 
H -1.240433 1.781855 -1.708739 
H -2.163348 0.183319 -1.708739 
H 2.163348 0.183319 -1.708739 
H 1.240433 1.781855 -1.708739 
C 0.000000 1.558543 0.887110 
C 1.349738 -0.779272 0.887110 
C -1.349738 -0.779272 0.887110 
O 0.000000 2.572496 1.441607 
O 2.227847 -1.286248 1.441607 
O -2.227847 -1.286248 1.441607
''',
        basis = 'def2svp',
        symmetry = True
)
```

crashes with
```
Traceback (most recent call last):
  File "<stdin>", line 22, in <module>
  File "/home/work/pyscf/pyscf/gto/mole.py", line 2153, in build
    symm.symm_adapted_basis(self, self.groupname, eql_atoms)
  File "/home/work/pyscf/pyscf/symm/basis.py", line 93, in symm_adapted_basis
    idx = ao_loc[op_id] + n
IndexError: index 1 is out of bounds for axis 0 with size 1
```

running on current master.

**Comment by sunqm** [comment]
Fixed in commit e4f27fa5daff47d573a70fc0853d78da9977d5d6
