### ISSUE TITLE
How to performe Nevpt2 during the spin-mix state-average caculation?

### ISSUE THREAD

**Issue by jamcas** [pyscf/pyscf#459]
I do a state-average over 1 doublet + 2 quartet +3 sextet, and then do Nevpt2 calculations on them separately :
```
# casscf
weights = numpy.ones(3)/3
solver1 = fci.direct_spin1.FCI(mol)
solver1.spin = 5
solver1 = fci.addons.fix_spin(solver1, ss=8.75)
solver1.nroots = 1
solver2 = fci.direct_spin1.FCI(mol)
solver2.spin = 1
solver2 = fci.addons.fix_spin(solver2, ss=0.75)
solver2.nroots = 1
solver3 = fci.direct_spin1.FCI(mol)
solver3.spin = 3
solver3 = fci.addons.fix_spin(solver3, ss=3.75)
solver3.nroots = 1

mc = mcscf.CASCI(mf, 11, 11)
mcscf.state_average_mix_(mc, [solver1, solver2, solver3], weights)
mo = lib.chkfile.load('IS3-M4-AVDZ-SPIN=3-CAS-24.chk', 'mcscf/mo_coeff')
mc.kernel(mo)

mrpt.nevpt2.NEVPT(mc,root=0).kernel()
mrpt.nevpt2.NEVPT(mc,root=1).kernel()
mrpt.nevpt2.NEVPT(mc,root=2).kernel()

Traceback (most recent call last):
  File "IS3-M4-AVDZ-SPIN=3-CAS.py", line 79, in <module>
    mrpt.nevpt2.NEVPT(mc,root=0).kernel()
  File "/home/chenh/anaconda3/lib/python3.6/site-packages/pyscf/mrpt/nevpt2.py", line 677, in kernel
    raise RuntimeError('State-average FCI solver object cannot be used '
RuntimeError: State-average FCI solver object cannot be used in NEVPT2 calculation.
A separated multi-root CASCI calculation is required for NEVPT2 method. See examples/mrpt/41-for_state_average.py.
```
I have tried to follow the examples/mrpt/41-for_state_average.py, but i can't get the spin-mix state-average result:
```
mc = mcscf.CASCI(mf, 11, 11)
mc.fcisolver.nroots = 3
mo = lib.chkfile.load('IS3-M4-AVDZ-SPIN=3-CAS-24.chk', 'mcscf/mo_coeff')
mc.kernel(mo)
```
I noticed a similar example in dmrg, I noticed a similar example in dmrg but it doesn't seem to apply:
```
mc = dmrgscf.DMRGSCF(mf, 6, 6)
weights = [.5, .25, .25]
solver1 = dmrgscf.DMRGCI(mol)
solver1.scratchDirectory = '/scratch/solver1'
solver1.nroots = 1
solver1.wfnsym = 'a1g'
solver1.spin = 2  # nelec_alpha - nelec_beta
solver2 = dmrgscf.DMRGCI(mol)
solver2.scratchDirectory = '/scratch/solver2'
solver2.nroots = 2
solver2.wfnsym = 'a1u'
mcscf.state_average_mix_(mc, [solver1, solver2], weights)
mc.kernel()

mc.fcisolver = solver1
mrpt.NEVPT(mc, root=0).compress_approx(maxM=100).run()

mc.fcisolver = solver2
mrpt.NEVPT(mc, root=1).compress_approx(maxM=100).run()

```

**Comment by jamcas** [comment]
I found a workaround, first we should do casci calculation separately to get the wfn for different spin, and then we can performe the nevpt2: 
```
mo = lib.chkfile.load('xxxxx.chk','mcscf/mo_coeff') # mo is from the spin-mix state-average calculation

# For the doublet
mc = mcscf.CASCI(mf, 11, 11)
mc.fcisolver.spin = 1
mc.fix_spin_(ss=0.75)
mc.kernel(mo)

mrpt.nevpt2.NEVPT(mc).kernel()

# For the quartet
mc = mcscf.CASCI(mf, 11, 11)
mc.fcisolver.spin = 3
mc.fix_spin_(ss=3.75)
mc.kernel(mo)

mrpt.nevpt2.NEVPT(mc).kernel()

# For the sextet
mc = mcscf.CASCI(mf, 11, 11)
mc.fcisolver.spin = 5
mc.fix_spin_(ss=8.75)
mc.kernel(mo)

mrpt.nevpt2.NEVPT(mc).kernel()
```
