### ISSUE TITLE
Cannot update to version 1.7 on Catalina Mac OS

### ISSUE THREAD

**Issue by Albert65** [pyscf/pyscf#479]
Dear All,

Update to version 1.7 on Catalina Mac OS fails:
```
pip3 install --upgrade pyscf
```

Tried suggested workaround, but still the same problem, although BLAS was found (without exporting LDFLAGS flag, BLAS cannot be resolved as well), for example:

```
export LDFLAGS='-L/usr/lib/ -L/usr/local/lib/python3.7/site-packages/pyscf/lib/ -lblas -libcint'; export PYSCF_INC_DIR=/usr/local/lib/python3.7/site-packages/pyscf/lib/:/usr/lib:${PYSCF_INC_DIR}; pip3 install --upgrade pyscf
```

Output:
```
  Using cached https://files.pythonhosted.org/packages/b5/f4/ed70c61541d134c1a6c78cc1723ceab9144ce7a8cf60344862151c0f492e/pyscf-1.7.0.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /usr/local/opt/python/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/7t/y7kjr2ls357cdxw4xgrvcm4c0000gn/T/pip-install-tcewosdj/pyscf/setup.py'"'"'; __file__='"'"'/private/var/folders/7t/y7kjr2ls357cdxw4xgrvcm4c0000gn/T/pip-install-tcewosdj/pyscf/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/7t/y7kjr2ls357cdxw4xgrvcm4c0000gn/T/pip-install-tcewosdj/pyscf/pip-egg-info
         cwd: /private/var/folders/7t/y7kjr2ls357cdxw4xgrvcm4c0000gn/T/pip-install-tcewosdj/pyscf/
    Complete output (12 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/7t/y7kjr2ls357cdxw4xgrvcm4c0000gn/T/pip-install-tcewosdj/pyscf/setup.py", line 354, in <module>
        raise RuntimeError
    RuntimeError
    ****************************************************************
    *** WARNING: libcint library not found.
    * You can download libcint library from http://github.com/sunqm/libcint
    * May need to set PYSCF_INC_DIR if libcint library was not installed in the
    * system standard install path (/usr, /usr/local, etc). Eg
    *   export PYSCF_INC_DIR=/path/to/libcint:/path/to/other/lib
    ****************************************************************
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by gkc1000** [comment]
Did you see libcint downloaded and built during the installation process?
If you simply do pip3 install (without --upgrade) does it work?

**Comment by Albert65** [comment]
Minutes ago reinstalled python3. This is the output:
```
pip3 install pyscf
Looking in indexes: https://pypi.org/simple, 
Collecting pyscf
  Using cached https://files.pythonhosted.org/packages/b5/f4/ed70c61541d134c1a6c78cc1723ceab9144ce7a8cf60344862151c0f492e/pyscf-1.7.0.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /usr/local/opt/python/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/7t/y7kjr2ls357cdxw4xgrvcm4c0000gn/T/pip-install-sb58f37r/pyscf/setup.py'"'"'; __file__='"'"'/private/var/folders/7t/y7kjr2ls357cdxw4xgrvcm4c0000gn/T/pip-install-sb58f37r/pyscf/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/7t/y7kjr2ls357cdxw4xgrvcm4c0000gn/T/pip-install-sb58f37r/pyscf/pip-egg-info
         cwd: /private/var/folders/7t/y7kjr2ls357cdxw4xgrvcm4c0000gn/T/pip-install-sb58f37r/pyscf/
    Complete output (12 lines):
    ****************************************************************
    *** WARNING: BLAS library not found.
    * You can include the BLAS library in the global environment LDFLAGS, eg
    *   export LDFLAGS='-L/path/to/blas/lib -lblas'
    * or specify the BLAS library path in  PYSCF_INC_DIR
    *   export PYSCF_INC_DIR=/path/to/blas/lib:/path/to/other/lib
    ****************************************************************
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/7t/y7kjr2ls357cdxw4xgrvcm4c0000gn/T/pip-install-sb58f37r/pyscf/setup.py", line 245, in <module>
        raise RuntimeError
    RuntimeError
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output. 
```
Nothing new. Now, redefining LDFLAGS to fix BLAS problem:
```
 export LDFLAGS='-L/usr/lib -lblas'; pip3 install pyscf
Looking in indexes: https://pypi.org/simple, 
Collecting pyscf
  Using cached https://files.pythonhosted.org/packages/b5/f4/ed70c61541d134c1a6c78cc1723ceab9144ce7a8cf60344862151c0f492e/pyscf-1.7.0.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /usr/local/opt/python/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/7t/y7kjr2ls357cdxw4xgrvcm4c0000gn/T/pip-install-r0161amr/pyscf/setup.py'"'"'; __file__='"'"'/private/var/folders/7t/y7kjr2ls357cdxw4xgrvcm4c0000gn/T/pip-install-r0161amr/pyscf/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/7t/y7kjr2ls357cdxw4xgrvcm4c0000gn/T/pip-install-r0161amr/pyscf/pip-egg-info
         cwd: /private/var/folders/7t/y7kjr2ls357cdxw4xgrvcm4c0000gn/T/pip-install-r0161amr/pyscf/
    Complete output (12 lines):
    ****************************************************************
    *** WARNING: libcint library not found.
    * You can download libcint library from http://github.com/sunqm/libcint
    * May need to set PYSCF_INC_DIR if libcint library was not installed in the
    * system standard install path (/usr, /usr/local, etc). Eg
    *   export PYSCF_INC_DIR=/path/to/libcint:/path/to/other/lib
    ****************************************************************
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/7t/y7kjr2ls357cdxw4xgrvcm4c0000gn/T/pip-install-r0161amr/pyscf/setup.py", line 354, in <module>
        raise RuntimeError
    RuntimeError
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
However,
```
pip3 install 'pyscf==1.6.5'
```
works just fine.

**Comment by Albert65** [comment]
On CentOS 7 the new version pyscf==1.7.0 installs without issues.

**Comment by sunqm** [comment]
Pip wheels for mac are available now.
