### ISSUE TITLE
IndexError when parsing ECP

### ISSUE THREAD

**Issue by jamcas** [pyscf/pyscf#504]
```
import os
from functools import reduce
from pyscf import gto, scf, dft, lib, tools
from pyscf.lo import orth
import sys
from pyscf.tools import molden
import numpy

os.system('date')

mol = gto.Mole()
mol.verbose = 4
mol.atom = (
'''
C           0.36936800      0.63267200      1.18377900
C           0.37021200     -0.63276700     -1.18359300
Ta         -1.04710500     -0.00107400      0.00013700
V           1.57453700      0.90513200     -0.23255800
V           1.57573800     -0.90357000      0.23274900
'''
)
mol.basis = {
'C': 'aug-cc-pvdz',
'V': 'aug-cc-pvdz',
'Ta': gto.basis.parse('''
Ta    S
     29.8670000              0.0287250             -0.0091320              0.0324720              0.0000000
     18.7203000             -0.1985810              0.0630170             -0.1723550              0.0000000
     11.7533000              0.4482880             -0.1437480              0.3341840              0.0000000
      4.5708900             -0.7983960              0.2705360             -0.5725580              0.0000000
      0.9478400              0.8861040             -0.4015970              1.3652610              0.0000000
      0.4340380              0.4136940             -0.3195670             -0.6032250              0.0000000
      0.1050310              0.0121460              0.6651050             -1.7315730              0.0000000
      0.0389480              0.0000000              0.0000000              0.0000000              1.0000000
Ta    S
      0.0144000              1.0000000
Ta    P
      7.3652400              0.1796820             -0.0508780             -0.0697670              0.0000000
      4.7544000             -0.5211000              0.1495500              0.2016550              0.0000000
      2.9959500              0.1911040             -0.0507540             -0.0482900              0.0000000
      0.9941230              0.6464550             -0.2483790             -0.4247200              0.0000000
      0.4196000              0.4240400             -0.1478010             -0.1275720              0.0000000
      0.1182390              0.0425600              0.5415390              0.9415430              0.0000000
      0.0401010              0.0000000              0.0000000              0.0000000              1.0000000
Ta    P
      0.0136000              1.0000000
Ta    D
      7.5616000              0.0178690             -0.0205840              0.0000000
      4.7408700             -0.0661360              0.0780240              0.0000000
      1.1697500              0.2554580             -0.3544000              0.0000000
      0.4793100              0.4454920             -0.5155940              0.0000000
      0.1837040              0.4029670              0.4207610              0.0000000
      0.0644090              0.0000000              0.0000000              1.0000000
Ta    D
      0.0226000              1.0000000
Ta    F
      0.3735000              1.0000000
Ta    F
      0.1286000              1.0000000
''')}
mol.ecp =  {'Ta':gto.basis.parse_ecp('''
Ta nelec 60
Ta ul
2       1.00000000             0.00000000
Ta S
2      10.31806900           454.60064900
4      10.54026700             2.83797500
2       2.57472600            -0.81473600
Ta P
2       8.74334200            96.91078300
2       7.91622300           195.85043200
4       9.27573600             4.81252400
4       8.10167500             6.33851200
2       2.07712700            -0.45917300
2       2.75037200            -0.64458600
Ta D
2       5.44731400            45.96997600
2       5.21254500            69.63897200
4       5.88435800             0.80293300
4       5.64957900             0.42959500
2       1.38818000            -0.30722700
2       1.29439800            -0.46156000
Ta F
2       2.16127500             5.75777300
2       2.12593900             7.67816700
Ta G
2       3.14592000            -5.68406600
2       3.12794200            -7.06231300
''')}
mol.spin = 2
mol.charge = -1
mol.max_memory = 60000
mol.build()
Traceback (most recent call last):
  File "Ta-IS4-M3-AVDZ-DFT.py", line 89, in <module>
    ''')}
  File "/home/chenh/anaconda3/lib/python3.6/site-packages/pyscf/gto/basis/__init__.py", line 330, in parse_ecp
    return parse_nwchem.parse_ecp(string, symb)
  File "/home/chenh/anaconda3/lib/python3.6/site-packages/pyscf/gto/basis/parse_nwchem.py", line 128, in parse_ecp
    return _parse_ecp(ecptxt)
  File "/home/chenh/anaconda3/lib/python3.6/site-packages/pyscf/gto/basis/parse_nwchem.py", line 371, in _parse_ecp
    by_ang[l].append([float(x) for x in line[1:]])
IndexError: list index out of range
```

**Comment by bogdanoff** [comment]
> 4      10.54026700             2.83797500

This Ta ECP60MDF is a rare case with 'r-exponent' of 2 (first number is 4).
I found only two others, namely I ECP28MDF and Hf ECP60MDF.
The following patch fixes the IndexError, but I'm not sure if it leads to correct calculation.
One should probably verify with Molpro, Molcas or some other code.
```
diff --git a/pyscf/gto/basis/parse_nwchem.py b/pyscf/gto/basis/parse_nwchem.py
index 3e3e128b6..0ff5cddc5 100644
--- a/pyscf/gto/basis/parse_nwchem.py
+++ b/pyscf/gto/basis/parse_nwchem.py
@@ -367,7 +367,7 @@ def _parse_ecp(raw_ecp):
                 ecp_add.append([-1])
             else:
                 ecp_add.append([MAPSPDF[key]])
-            by_ang = [[], [], [], []]
+            by_ang = [[], [], [], [], []]
             ecp_add[-1].append(by_ang)
         else:
             line = dat.replace('D','e').split()
```

**Comment by jamcas** [comment]
This patch fixes the  IndexError, however the calculation is wrong:
pyscf:-2021.58975313749
molpro:-2021.87909401

**Comment by sunqm** [comment]
It needs also a fix in the C code. r^4 was not supported

**Comment by sunqm** [comment]
Was the latest commit fix the problem? @jamcas

**Comment by jamcas** [comment]
Yes, it fixs. Thaks for your help! @sunqm
