### ISSUE TITLE
KeyError for custom basis sets with ghost atoms and SAD guess

### ISSUE THREAD

**Issue by susilehtola** [pyscf/pyscf#536]
The input
```
from pyscf import gto
from pyscf import scf

mol = gto.M(
    verbose = 4,
    symmetry= 0,
    spin = 0,
    atom = '''                                                                                                                                                                                
C 0.0 0.0 -1                                                                                                                                                                                  
ghost_Mg 0.0 0.0 0.0                                                                                                                                                                          
C 0.0 0.0 1                                                                                                                                                                                   
    ''',
    basis = {
        'C' : gto.basis.load('ugbs.nw', 'C'),
        'Mg' : gto.basis.load('ugbs.nw', 'Mg'),
    }
)

method = scf.RHF(mol)
method.init_guess = 'atom'
method.kernel()
```
gives the error
```
Traceback (most recent call last):
  File "test.py", line 24, in <module>
    method.kernel()
  File "/home/work/pyscf/pyscf/lib/misc.py", line 601, in aliased_fn
    return getattr(self, fname)(*args, **kwargs)
  File "/home/work/pyscf/pyscf/scf/hf.py", line 1630, in scf
    conv_check=self.conv_check, **kwargs)
  File "/home/work/pyscf/pyscf/scf/hf.py", line 122, in kernel
    dm = mf.get_init_guess(mol, mf.init_guess)
  File "/home/work/pyscf/pyscf/scf/hf.py", line 1563, in get_init_guess
    dm = self.init_guess_by_atom(mol)
  File "/home/work/pyscf/pyscf/scf/hf.py", line 1519, in init_guess_by_atom
    return init_guess_by_atom(mol)
  File "/home/work/pyscf/pyscf/scf/hf.py", line 468, in init_guess_by_atom
    e_hf, e, c, occ = atm_scf[symb]
KeyError: 'GHOST-Mg'
```

**Comment by sunqm** [comment]
Fixed in commit 7bc880e8954c4ab3845b3efb686dd747aa3c52ef
