### ISSUE TITLE
AttributeError: module 'pyscf.gto.basis.minao' has no attribute 'Ta'

### ISSUE THREAD

**Issue by jamcas** [pyscf/pyscf#675]
I found that Ta is indeed in miao.py but it is commented out, so can it be used directly?

This is my input:
```
import os
from pyscf import gto, scf, dft, mcscf, lib, mrpt, fci, mo_mapping
from pyscf.mcscf import dmet_cas, avas
import sys
from pyscf.tools import molden
import numpy

os.system('date')

mol = gto.Mole()
mol.verbose = 4
mol.atom = (
'''
Ta                -1.15901900   -0.02697800   -0.08819000
V                  0.90124100    1.39821300   -0.01873200
V                  1.30888800   -0.92272700    0.35572300
C                  0.18689800    0.37877800    1.37893800
C                  3.08296700   -0.70634200   -0.57151700
C                  2.54006000    0.48324200   -0.60456500
C                 -0.18068600   -1.65014900   -0.42168200
'''
)
mol.basis = {'C':'aug-cc-pvdz','V':'aug-cc-pvdz','Ta':gto.basis.parse('''
Ta    S
     29.8670000              0.0287250             -0.0091320              0.0324720              0.0000000
     18.7203000             -0.1985810              0.0630170             -0.1723550              0.0000000
     11.7533000              0.4482880             -0.1437480              0.3341840              0.0000000
      4.5708900             -0.7983960              0.2705360             -0.5725580              0.0000000
      0.9478400              0.8861040             -0.4015970              1.3652610              0.0000000
      0.4340380              0.4136940             -0.3195670             -0.6032250              0.0000000
      0.1050310              0.0121460              0.6651050             -1.7315730              0.0000000
      0.0389480              0.0000000              0.0000000              0.0000000              1.0000000
Ta    S
      0.0144000              1.0000000
Ta    P
      7.3652400              0.1796820             -0.0508780             -0.0697670              0.0000000
      4.7544000             -0.5211000              0.1495500              0.2016550              0.0000000
      2.9959500              0.1911040             -0.0507540             -0.0482900              0.0000000
      0.9941230              0.6464550             -0.2483790             -0.4247200              0.0000000
      0.4196000              0.4240400             -0.1478010             -0.1275720              0.0000000
      0.1182390              0.0425600              0.5415390              0.9415430              0.0000000
      0.0401010              0.0000000              0.0000000              0.0000000              1.0000000
Ta    P
      0.0136000              1.0000000
Ta    D
      7.5616000              0.0178690             -0.0205840              0.0000000
      4.7408700             -0.0661360              0.0780240              0.0000000
      1.1697500              0.2554580             -0.3544000              0.0000000
      0.4793100              0.4454920             -0.5155940              0.0000000
      0.1837040              0.4029670              0.4207610              0.0000000
      0.0644090              0.0000000              0.0000000              1.0000000
Ta    D
      0.0226000              1.0000000
Ta    F
      0.3735000              1.0000000
Ta    F
      0.1286000              1.0000000
''')}
mol.ecp =  {'Ta':gto.basis.parse_ecp('''
Ta nelec 60
Ta ul
2       1.00000000             0.00000000
Ta S
2      10.31806900           454.60064900
4      10.54026700             2.83797500
2       2.57472600            -0.81473600
Ta P
2       8.74334200            96.91078300
2       7.91622300           195.85043200
4       9.27573600             4.81252400
4       8.10167500             6.33851200
2       2.07712700            -0.45917300
2       2.75037200            -0.64458600
Ta D
2       5.44731400            45.96997600
2       5.21254500            69.63897200
4       5.88435800             0.80293300
4       5.64957900             0.42959500
2       1.38818000            -0.30722700
2       1.29439800            -0.46156000
Ta F
2       2.16127500             5.75777300
2       2.12593900             7.67816700
Ta G
2       3.14592000            -5.68406600
2       3.12794200            -7.06231300
''')}
mol.spin = 0
mol.charge = -1
mol.max_memory = 60000
mol.build()

# dft
mf = dft.UKS(mol)
mf.max_cycle = 500
mf.xc = 'b88,pw91'
mf.__dict__.update(lib.chkfile.load('TaV2C4-IS4-M1-AVDZ.chk', 'scf'))

#avas
cas_list = ['Ta 5d', 'Ta 6s']
norb, ne_act, mo = avas.avas(mf, cas_list)

```

My output:
```
** AVAS **
UHF/UKS object is found.  AVAS takes alpha orbitals only
  Total number of HF MOs  is equal to    264
  Number of occupied HF MOs is equal to  42
/home/chenh/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "TaV2C4-IS4-M1-AVDZ-SHCI.py", line 117, in <module>
    norb, ne_act, mo = avas.avas(mf, cas_list)
  File "/home/chenh/anaconda3/lib/python3.6/site-packages/pyscf/mcscf/avas.py", line 118, in kernel
    pmol.build(False, False)
  File "/home/chenh/anaconda3/lib/python3.6/site-packages/pyscf/gto/mole.py", line 2274, in build
    self._basis = self.format_basis(_basis)
  File "/home/chenh/anaconda3/lib/python3.6/site-packages/pyscf/gto/mole.py", line 2356, in format_basis
    return format_basis(basis_tab)
  File "/home/chenh/anaconda3/lib/python3.6/site-packages/pyscf/gto/mole.py", line 424, in format_basis
    bset = convert(str(atom_basis), stdsymb)
  File "/home/chenh/anaconda3/lib/python3.6/site-packages/pyscf/gto/mole.py", line 412, in convert
    return basis.load(basis_name, symb)
  File "/home/chenh/anaconda3/lib/python3.6/site-packages/pyscf/gto/basis/__init__.py", line 464, in load
    b = mod.__getattribute__(symb)
AttributeError: module 'pyscf.gto.basis.minao' has no attribute 'Ta'

```

**Comment by sunqm** [comment]
Heavy elements for MINAO was enabled in commit 4345720dd1b7f8025c4879316d987dae156ab126.

Modules PiOS, AVAS and IAO for heavy elements will be affected. Tests for these methods were carried out on systems with light elements only. Please double check whether your results make sense.

**Comment by sunqm** [comment]
Heavy elements for MINAO was enabled in commit 4345720dd1b7f8025c4879316d987dae156ab126.

Modules PiOS, AVAS and IAO for heavy elements will be affected. Tests for these methods were carried out on systems with light elements only. Please double check whether your results make sense.

**Comment by jamcas** [comment]
Ok, thaks
