### ISSUE TITLE
Error using Pennylane qchem 

### ISSUE THREAD

**Issue by zohimchandani** [pyscf/pyscf#691]
I want to use the `convert_observable` function from here for which I have used `pip install pennylane-qchem` however I am getting the error message:

```
(base) C:\WINDOWS\system32>pip install pennylane-qchem
Collecting pennylane-qchem
  Using cached PennyLane_Qchem-0.11.0-py3-none-any.whl (39 kB)
Requirement already satisfied: openfermion in c:\users\zohim\anaconda3\lib\site-packages (from pennylane-qchem) (0.11.0)
Collecting openfermionpsi4
  Using cached openfermionpsi4-0.4.tar.gz (12 kB)
Collecting openfermionpyscf
  Using cached openfermionpyscf-0.4.tar.gz (13 kB)
Collecting pyscf<=1.7.1
  Using cached pyscf-1.7.1.tar.gz (5.9 MB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\zohim\anaconda3\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\zohim\\AppData\\Local\\Temp\\pip-install-wc2e6dle\\pyscf\\setup.py'"'"'; __file__='"'"'C:\\Users\\zohim\\AppData\\Local\\Temp\\pip-install-wc2e6dle\\pyscf\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\zohim\AppData\Local\Temp\pip-pip-egg-info-rbknba0z'
         cwd: C:\Users\zohim\AppData\Local\Temp\pip-install-wc2e6dle\pyscf\
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\zohim\AppData\Local\Temp\pip-install-wc2e6dle\pyscf\setup.py", line 207, in <module>
        for x in blas_libraries]
      File "C:\Users\zohim\AppData\Local\Temp\pip-install-wc2e6dle\pyscf\setup.py", line 207, in <listcomp>
        for x in blas_libraries]
      File "C:\Users\zohim\AppData\Local\Temp\pip-install-wc2e6dle\pyscf\setup.py", line 148, in search_lib_path
        paths = os.environ.get(LD_LIBRARY_PATH, '').split(os.pathsep)
    NameError: name 'LD_LIBRARY_PATH' is not defined
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

Any ideas? Thanks in advance.

**Comment by yangcal** [comment]
Hi Zohim,

pyscf currently does not support windows platform

**Comment by gkc1000** [comment]
Are you using linux subsystem for windows? Although PySCF has not been tested with windows, it may be possible to use it via the linux subsystem. Then there is a bash shell and you can export LD_LIBRARY_PATH=[path_to_pyscf/pyscf/lib]

**Comment by zohimchandani** [comment]
Yes, it works fine on Windows Subsystem for Linux

**Comment by gkc1000** [comment]
Ok, then I will close this issue.
