### ISSUE TITLE
sgx is not working with pip installed pyscf

### ISSUE THREAD

**Issue by levineds** [pyscf/pyscf#733]
Running the example given in the documentation, I got the error:

Traceback (most recent call last):
  File "test.py", line 12, in <module>
    mf.kernel()
  File "/home/levineds/.local/lib/python3.6/site-packages/pyscf/lib/misc.py", line 598, in aliased_fn
    return getattr(self, fname)(*args, **kwargs)
  File "/home/levineds/.local/lib/python3.6/site-packages/pyscf/scf/hf.py", line 1637, in scf
    self.build(self.mol)
  File "/home/levineds/.local/lib/python3.6/site-packages/pyscf/sgx/sgx.py", line 104, in build
    self.with_df.build(level=self.with_df.grids_level_i)
  File "/home/levineds/.local/lib/python3.6/site-packages/pyscf/sgx/sgx.py", line 236, in build
    self._opt = _make_opt(self.mol)
  File "/home/levineds/.local/lib/python3.6/site-packages/pyscf/sgx/sgx.py", line 170, in _make_opt
    'SGXsetnr_direct_scf')
  File "/home/levineds/.local/lib/python3.6/site-packages/pyscf/scf/_vhf.py", line 46, in __init__
    self.prescreen = prescreen
  File "/home/levineds/.local/lib/python3.6/site-packages/pyscf/scf/_vhf.py", line 81, in prescreen
    self._this.contents.fprescreen = _fpointer(v)
  File "/home/levineds/.local/lib/python3.6/site-packages/pyscf/scf/_vhf.py", line 26, in _fpointer
    return ctypes.c_void_p(_ctypes.dlsym(libcvhf._handle, name))
OSError: /home/levineds/.local/lib/python3.6/site-packages/pyscf/lib/libcvhf.so: undefined symbol: SGXnr_ovlp_prescreen

**Comment by sunqm** [comment]
Fixed in pyscf-2.1
