### ISSUE TITLE
Can't install on Windows by PIP !

### ISSUE THREAD

**Issue by xushengun** [pyscf/pyscf#750]
ERROR: Command errored out with exit status 1:
     command: 'D:\Anaconda3\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\a\\AppData\\Local\\Temp\\pip-install-6l4zl87_\\pyscf\\setup.py'"'"'; __file__='"'"'C:\\Users\\a\\AppData\\Local\\Temp\\pip-install-6l4zl87_\\pyscf\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\a\AppData\Local\Temp\pip-pip-egg-info-_bim4wiv'
         cwd: C:\Users\a\AppData\Local\Temp\pip-install-6l4zl87_\pyscf\
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\a\AppData\Local\Temp\pip-install-6l4zl87_\pyscf\setup.py", line 206, in <module>
        blas_path_guess = [search_lib_path('lib'+x+so_ext, blas_lib_dir)
      File "C:\Users\a\AppData\Local\Temp\pip-install-6l4zl87_\pyscf\setup.py", line 206, in <listcomp>
        blas_path_guess = [search_lib_path('lib'+x+so_ext, blas_lib_dir)
      File "C:\Users\a\AppData\Local\Temp\pip-install-6l4zl87_\pyscf\setup.py", line 148, in search_lib_path
        paths = os.environ.get(LD_LIBRARY_PATH, '').split(os.pathsep)
    NameError: name 'LD_LIBRARY_PATH' is not defined
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by sunqm** [comment]
PySCF does not support native windows platform. You can run it under ubuntu subsystem on windows 10

**Comment by gaurabthapa** [comment]
How do I install it using ubuntu subsystem on windows 10. I have already turned on WSL and intalled ubuntu, please share the code used to install PySCF. I have tried
 "pip install pyscf"
"Command 'pip' not found, but there are 18 similar ones."
, then i tried "sudo pip install pyscf
sudo: pip: command not found"

**Comment by jamesETsmith** [comment]
@gaurabthapa. I'm not very familiar with WSL, but it seems like you need to install pip. When you're in WSL try the following:
```bash
sudo apt update
sudo apt install python3-pip
```
If you need more info about installing `pip` see [this article](https://linuxize.com/post/how-to-install-pip-on-ubuntu-20.04/) or try searching around on Google.

Once that's installed you can try `pip install pyscf`. As a sidenote, you should _almost never_ use `sudo` with pip install. If you don't have root privileges, just you the `--user` flag, e.g. `pip install pyscf --user` (see this [SO answer](https://stackoverflow.com/questions/42988977/what-is-the-purpose-of-pip-install-user) for more details).

**Comment by gaurabthapa** [comment]
I installed pip but the error is still the same, also tried pip install pyscf --user

root@DESKTOP:~# pip3 --version
pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.8)
root@DESKTOP:~# pip install pyscf

Command 'pip' not found, but there are 18 similar ones.

root@DESKTOP:~#

**Comment by yangcal** [comment]
> I installed pip but the error is still the same, also tried pip install pyscf --user
> 
> root@DESKTOP:~# pip3 --version pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.8) root@DESKTOP:~# pip install pyscf
> 
> Command 'pip' not found, but there are 18 similar ones.
> 
> root@DESKTOP:~#
> 
> I appreciate your help.

Do you have multiple versions of python on your system? If that's the case, you might have pip2, pip3 etc, pointing to different versions of your python.

**Comment by mussard** [comment]
You might want to ensure the pip/python pair by running `python -m pip install pyscf`. A good mock run for that command is to compare the outputs for example of `python -m pip --version` and `python3 -m pip --version` to see where are your pips located. (Then again your problem might be another one altogether!)

**Comment by gaurabthapa** [comment]
Thanks for your comment. After I tried `pip3 intsall pyscf --user,` it installed pyscf.

**Comment by jamesETsmith** [comment]
If there are any further questions related to this, feel free to reopen.
