### ISSUE TITLE
Magnetizability calculations not working

### ISSUE THREAD

**Issue by susilehtola** [pyscf/pyscf#759]
Trying to run any of the codes in `pyscf/prop/magnetizability` gives a runtime error, for example
```
$ python rhf.py 
output file: /dev/null
Traceback (most recent call last):
  File "rhf.py", line 292, in <module>
    m = mag.kernel()
  File "rhf.py", line 250, in kernel
    mag_dia = self.dia(self.gauge_orig)
  File "rhf.py", line 72, in dia
    vs = jk.get_jk(mol, [dm0]*3, ['ijkl,ji->s2kl',
  File "/home/work/pyscf/pyscf/scf/jk.py", line 160, in get_jk
    raise RuntimeError('Scripts unsupported %s' % scripts)
RuntimeError: Scripts unsupported ['ijkl,ji->s2kl', 'ijkl,jk->s1il', 'ijkl,li->s1kj']
```
Are these routines included in the tests?

**Comment by vandan-revanur** [comment]
This directory no longer exists in the current master, as of 02 Aug 2026. 
@fishjojo can this issue be closed?
