### ISSUE TITLE
Conda builds > 1.7.1 use glibc that is too new

### ISSUE THREAD

**Issue by matt-chan** [pyscf/pyscf#771]
Hi,

Conda builds of PySCF that are newer than 1.7.1 link to a version of glibc (2.24 I think) which isn't present in clusters running CentOS7. This causes segfaults on those machines. 

This happens because Conda is leaking the glibc version present on the packager's machine. Is it possible to rebuild them from a docker container or a machine that has an older version of glibc so they'll work with more clusters? I think the real solution might be to fix the sysroot in the cmake script though: https://docs.conda.io/projects/conda-build/en/latest/resources/compiler-tools.html?highlight=glibc#an-aside-on-cmake-and-sysroots

Thanks!

**Comment by sunqm** [comment]
Sounds weird that the glibc version causes segfault. Is the core dump file
accessible? Can you post gdb bt info?

On Wed, Nov 25, 2020 at 08:28:27AM -0800, Matthew Chan wrote:
> Hi,
> 
> Conda builds of PySCF that are newer than 1.7.1 link to a version of glibc (2.24 I think) which isn't present in clusters running CentOS7. This causes segfaults on those machines. 
> 
> This happens because Conda is leaking the glibc version present on the packager's machine. Is it possible to rebuild them from a docker container or a machine that has an older version of glibc so they'll work with more clusters? I think the real solution might be to fix the sysroot in the cmake script though: https://docs.conda.io/projects/conda-build/en/latest/resources/compiler-tools.html?highlight=glibc#an-aside-on-cmake-and-sysroots
> 
> Thanks!
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/pyscf/pyscf/issues/771

--

**Comment by matt-chan** [comment]
Hi Qiming,

Sorry I checked again and it wasn't a segfault. It's an OSError raised by failed linking. Also the glibc that got leaked was 2.29, not 2.24.

Here's the error:

```
>>> import pyscf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mattchan/miniconda3/envs/test/lib/python3.7/site-packages/pyscf/__init__.py", line 72, in <module>
    from pyscf import gto
  File "/home/mattchan/miniconda3/envs/test/lib/python3.7/site-packages/pyscf/gto/__init__.py", line 19, in <module>
    from pyscf.gto import mole
  File "/home/mattchan/miniconda3/envs/test/lib/python3.7/site-packages/pyscf/gto/mole.py", line 42, in <module>
    from pyscf.gto import moleintor
  File "/home/mattchan/miniconda3/envs/test/lib/python3.7/site-packages/pyscf/gto/moleintor.py", line 29, in <module>
    libcgto = lib.load_library('libcgto')
  File "/home/mattchan/miniconda3/envs/test/lib/python3.7/site-packages/pyscf/lib/misc.py", line 69, in load_library
    return numpy.ctypeslib.load_library(libname, _loaderpath)
  File "/home/mattchan/miniconda3/envs/test/lib/python3.7/site-packages/numpy/ctypeslib.py", line 150, in load_library
    return ctypes.cdll[libpath]
  File "/home/mattchan/miniconda3/envs/test/lib/python3.7/ctypes/__init__.py", line 439, in __getitem__
    return getattr(self, name)
  File "/home/mattchan/miniconda3/envs/test/lib/python3.7/ctypes/__init__.py", line 434, in __getattr__
    dll = self._dlltype(name)
  File "/home/mattchan/miniconda3/envs/test/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /home/mattchan/miniconda3/envs/test/lib/python3.7/site-packages/pyscf/lib/libcgto.so)
```

Thanks!
Matt

**Comment by br2575** [comment]
I am also having the same issue trying to set up PySCF to run on XSEDE's new Expanse supercomputer. Any luck in fixing it? Should we just use older PySCF for now?

**Comment by sunqm** [comment]
A new release of pyscf-1.7 is uploaded to conda cloud. It was built on a relatively old linux environment (cent os 7). It should solve this issue
