### ISSUE TITLE
libcint.so.2.8 is built but not installed

### ISSUE THREAD

**Issue by yurivict** [pyscf/pyscf#86]
```
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from pyscf import gto, scf
  File "/usr/local/lib/python2.7/site-packages/pyscf/__init__.py", line 118, in <module>
    from pyscf import gto
  File "/usr/local/lib/python2.7/site-packages/pyscf/gto/__init__.py", line 7, in <module>
    from pyscf.gto import mole
  File "/usr/local/lib/python2.7/site-packages/pyscf/gto/mole.py", line 22, in <module>
    from pyscf.gto import moleintor
  File "/usr/local/lib/python2.7/site-packages/pyscf/gto/moleintor.py", line 10, in <module>
    libcgto = pyscf.lib.load_library('libcgto')
  File "/usr/local/lib/python2.7/site-packages/pyscf/lib/misc.py", line 41, in load_library
    return numpy.ctypeslib.load_library(libname, _loaderpath)
  File "/usr/local/lib/python2.7/site-packages/numpy/ctypeslib.py", line 150, in load_library
    return ctypes.cdll[libpath]
  File "/usr/local/lib/python2.7/ctypes/__init__.py", line 437, in __getitem__
    return getattr(self, name)
  File "/usr/local/lib/python2.7/ctypes/__init__.py", line 432, in __getattr__
    dll = self._dlltype(name)
  File "/usr/local/lib/python2.7/ctypes/__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: Shared object "libcint.so.2.8" not found, required by "libcgto.so"
```

**Comment by sunqm** [comment]
When the python package is installed, libcint and other external libraries (libxc, xcfun) are supposed to be built independently or be installed by the package manager.  This works all right on conda cloud (https://anaconda.org/pyqc/pyscf). The rpath and the runtime LD_LIBRARY_PATH are fixed by conda build system, consistently.  I didn't test how to install by hand.  Probably, rpath will cause some errors if using the default compiling options.  So CMAKE_SKIP_RPATH may be required when building libcint and other underlying libraries.

**Comment by yurivict** [comment]
I run cmake/gmake first, python setup.py install after this, and it fails to install libcint.so.2.8. I could make the installation work only because rpath was saved into the installed libraries.
