### ISSUE TITLE
"from pyscf.dft import xcfun" fails with 1.7.6

### ISSUE THREAD

**Issue by eljost** [pyscf/pyscf#872]
Dear developers,
after upgrading to the new prebuilt 1.7.6 release from PyPI the import statement `from pyscf.dft import xcfun` raises an OSError.
```
Python 3.9.2 (default, Feb 20 2021, 18:40:11) 
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyscf.dft import xcfun
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/johannes/programme/pysis_venv/lib/python3.9/site-packages/pyscf/dft/xcfun.py", line 32, in <module>
    _itrf = lib.load_library('libxcfun_itrf')
  File "/home/johannes/programme/pysis_venv/lib/python3.9/site-packages/pyscf/lib/misc.py", line 68, in load_library
    return numpy.ctypeslib.load_library(libname, _loaderpath)
  File "/home/johannes/programme/pysis_venv/lib/python3.9/site-packages/numpy/ctypeslib.py", line 153, in load_library
    raise OSError("no file with expected extension")
OSError: no file with expected extension
```

The same import worked fine with `pyscf 1.7.5.1` found on PyPI.

Is the exclusion of xcfun from the PyPI-release intended, because nothing is mentioned in the release notes?

All the best,
Johannes

**Comment by sunqm** [comment]
It's an issue of packaging. Linux wheels have been rebuilt

**Comment by eljost** [comment]
Thanks for the quick reply and quick fix. It works now.
