### ISSUE TITLE
order (MRO) error when DF-CASSCF is initialized on top of a DF-SCF object

### ISSUE THREAD

**Issue by hongzhouye** [pyscf/pyscf#874]
# Issue
The following script (taken from the DF section of the user doc)
```Python
from pyscf import gto, scf, mcscf
mol = gto.M(atom='N 0 0 0; N 0 0 1.2', basis='def2-tzvp')
mf = scf.RHF(mol).density_fit().run()
mc = mcscf.CASSCF(mf, 8, 10).density_fit().run()
```
crashes with an error
```
Traceback (most recent call last):
  File "casdf.py", line 4, in <module>
    mc = mcscf.CASSCF(mf, 8, 10).density_fit().run()
  File "/Users/hzye/local/opt/pyscf/pyscf/mcscf/casci.py", line 1023, in density_fit
    return df.density_fit(self, auxbasis, with_df)
  File "/Users/hzye/local/opt/pyscf/pyscf/mcscf/df.py", line 70, in density_fit
    class DFCASSCF(_DFCASSCF, casscf_class):
TypeError: Cannot create a consistent method resolution
order (MRO) for bases _DFCASSCF, DFCASSCF
```
# (Possible) Reason
`pyscf.mcscf.df.density_fit()` is called twice: first in [this line](https://github.com/pyscf/pyscf/blob/master/pyscf/mcscf/__init__.py#L204) upon initialization, then by the user explicitly calling `density_fit`. When it's in `density_fit` for the second time, `casscf` is already a `_DFCASSCF` object, which triggers the above error in [this line](https://github.com/pyscf/pyscf/blob/master/pyscf/mcscf/df.py#L70).
# Proposed fix
Insert the following after [this line](https://github.com/pyscf/pyscf/blob/master/pyscf/mcscf/df.py#L68)
```Python
            # ...
            # with_df.auxbasis = auxbasis

    if isinstance(casscf, _DFCASSCF):
        if casscf.with_df is None:
            casscf.with_df = with_df
        elif getattr(casscf.with_df, 'auxbasis', None) != auxbasis:
            #logger.warn(casscf, 'DF might have been initialized twice.')
            casscf = copy.copy(casscf)
            casscf.with_df = with_df
        return casscf

    # class DFCASSCF(_DFCASSCF, casscf_class):
        # ...
```

**Comment by sunqm** [comment]
Thanks for the proposed fix. Would you mind to open a PR to fix this error?
